import type { PlayerCardData, Tier } from '@/types/player';

export const FALLBACK_PLAYERS: PlayerCardData[] = [
  // ── ICONS ──
  {
    id: 'fb-icon-1',
    name: 'Pelé',
    tier: 'ICON',
    position: 'CF/CAM',
    club: 'Santos FC',
    nation: 'Brazil',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Pele_con_brasil_%28cropped%29.jpg/330px-Pele_con_brasil_%28cropped%29.jpg',
    kitNumber: 10,
  },
  {
    id: 'fb-icon-2',
    name: 'Diego Maradona',
    tier: 'ICON',
    position: 'CAM/ST',
    club: 'SSC Napoli',
    nation: 'Argentina',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Argentina_celebrando_copa_%28cropped%29.jpg/330px-Argentina_celebrando_copa_%28cropped%29.jpg',
    kitNumber: 10,
  },
  {
    id: 'fb-icon-3',
    name: 'Zinedine Zidane',
    tier: 'ICON',
    position: 'CAM/CM',
    club: 'Real Madrid',
    nation: 'France',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg/330px-Zinedine_Zidane_by_Tasnim_03.jpg',
    kitNumber: 5,
  },
  {
    id: 'fb-icon-4',
    name: 'Paolo Maldini',
    tier: 'ICON',
    position: 'CB/LB',
    club: 'AC Milan',
    nation: 'Italy',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Paolo_Maldini_2008.jpg/330px-Paolo_Maldini_2008.jpg',
    kitNumber: 3,
  },
  {
    id: 'fb-icon-5',
    name: 'Johan Cruyff',
    tier: 'ICON',
    position: 'CF/LW',
    club: 'FC Barcelona',
    nation: 'Netherlands',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Johan_Cruijff_1974c.jpg/330px-Johan_Cruijff_1974c.jpg',
    kitNumber: 14,
  },
  {
    id: 'fb-icon-6',
    name: 'Ronaldo Nazário',
    tier: 'ICON',
    position: 'ST',
    club: 'Real Madrid',
    nation: 'Brazil',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Ronaldo_smiling.jpg/330px-Ronaldo_smiling.jpg',
    kitNumber: 9,
  },
  {
    id: 'fb-icon-7',
    name: 'Ronaldinho',
    tier: 'ICON',
    position: 'LW/CAM',
    club: 'FC Barcelona',
    nation: 'Brazil',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ronaldinho_061115.jpg/330px-Ronaldinho_061115.jpg',
    kitNumber: 10,
  },
  {
    id: 'fb-icon-8',
    name: 'Lev Yashin',
    tier: 'ICON',
    position: 'GK',
    club: 'Dynamo Moscow',
    nation: 'Russia',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Lev_Yashin_1966.jpg/330px-Lev_Yashin_1966.jpg',
    kitNumber: 1,
  },

  // ── HEROES ──
  {
    id: 'fb-hero-1',
    name: 'Yaya Touré',
    tier: 'HERO',
    position: 'CM/CDM',
    club: 'Manchester City',
    nation: 'Ivory Coast',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Yaya_Toure_2018.jpg/330px-Yaya_Toure_2018.jpg',
    kitNumber: 42,
  },
  {
    id: 'fb-hero-2',
    name: 'Diego Forlán',
    tier: 'HERO',
    position: 'ST/CF',
    club: 'Atlético de Madrid',
    nation: 'Uruguay',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Diego_Forlan_2010.jpg/330px-Diego_Forlan_2010.jpg',
    kitNumber: 7,
  },
  {
    id: 'fb-hero-3',
    name: 'Claudio Marchisio',
    tier: 'HERO',
    position: 'CM/LM',
    club: 'Juventus',
    nation: 'Italy',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Claudio_Marchisio_2015.jpg/330px-Claudio_Marchisio_2015.jpg',
    kitNumber: 8,
  },
  {
    id: 'fb-hero-4',
    name: 'David Ginola',
    tier: 'HERO',
    position: 'LM/LW',
    club: 'Newcastle United',
    nation: 'France',
    isLegend: true,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/David_Ginola_2015.jpg/330px-David_Ginola_2015.jpg',
    kitNumber: 14,
  },
  {
    id: 'fb-hero-5',
    name: 'Lucio',
    tier: 'HERO',
    position: 'CB',
    club: 'Inter Milan',
    nation: 'Brazil',
    isLegend: true,
    kitNumber: 3,
  },

  // ── MASTERS ──
  {
    id: 'fb-master-1',
    name: 'Kylian Mbappé',
    tier: 'ULTIMATE',
    position: 'ST/LW',
    club: 'Real Madrid',
    nation: 'France',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg/500px-Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg',
    kitNumber: 9,
  },
  {
    id: 'fb-master-2',
    name: 'Erling Haaland',
    tier: 'ULTIMATE',
    position: 'ST',
    club: 'Manchester City',
    nation: 'Norway',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg/500px-Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg',
    kitNumber: 9,
  },
  {
    id: 'fb-master-3',
    name: 'Vinicius Jr.',
    tier: 'ULTIMATE',
    position: 'LW/LM',
    club: 'Real Madrid',
    nation: 'Brazil',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg/500px-Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg',
    kitNumber: 7,
  },
  {
    id: 'fb-master-4',
    name: 'Kevin De Bruyne',
    tier: 'ULTIMATE',
    position: 'CAM/CM',
    club: 'Manchester City',
    nation: 'Belgium',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_201807091.jpg/330px-Kevin_De_Bruyne_201807091.jpg',
    kitNumber: 17,
  },
  {
    id: 'fb-master-5',
    name: 'Harry Kane',
    tier: 'ULTIMATE',
    position: 'ST',
    club: 'Bayern Munich',
    nation: 'England',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Harry_Kane_2018.jpg/330px-Harry_Kane_2018.jpg',
    kitNumber: 9,
  },
  {
    id: 'fb-master-6',
    name: 'Mohamed Salah',
    tier: 'ULTIMATE',
    position: 'RW',
    club: 'Liverpool',
    nation: 'Egypt',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Mohamed_Salah_Argentina_v_Egypt_7_July_2026-163_%28cropped%29.jpg/500px-Mohamed_Salah_Argentina_v_Egypt_7_July_2026-163_%28cropped%29.jpg',
    kitNumber: 11,
  },

  // ── ELITE PLUS ──
  {
    id: 'fb-eliteplus-1',
    name: 'Jude Bellingham',
    tier: 'MASTER',
    position: 'CAM/CM',
    club: 'Real Madrid',
    nation: 'England',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Jude_Bellingham_2024_%28cropped%29.jpg/330px-Jude_Bellingham_2024_%28cropped%29.jpg',
    kitNumber: 5,
  },
  {
    id: 'fb-eliteplus-2',
    name: 'Bukayo Saka',
    tier: 'MASTER',
    position: 'RW/RM',
    club: 'Arsenal',
    nation: 'England',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Bukayo_Saka_2024_%28cropped%29.jpg/330px-Bukayo_Saka_2024_%28cropped%29.jpg',
    kitNumber: 7,
  },
  {
    id: 'fb-eliteplus-3',
    name: 'Rodri',
    tier: 'MASTER',
    position: 'CDM/CM',
    club: 'Manchester City',
    nation: 'Spain',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Rodri_2024_%28cropped%29.jpg/330px-Rodri_2024_%28cropped%29.jpg',
    kitNumber: 16,
  },
  {
    id: 'fb-eliteplus-4',
    name: 'Virgil van Dijk',
    tier: 'MASTER',
    position: 'CB',
    club: 'Liverpool',
    nation: 'Netherlands',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Virgil_van_Dijk_2024.jpg/330px-Virgil_van_Dijk_2024.jpg',
    kitNumber: 4,
  },
  {
    id: 'fb-eliteplus-5',
    name: 'Thibaut Courtois',
    tier: 'MASTER',
    position: 'GK',
    club: 'Real Madrid',
    nation: 'Belgium',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Thibaut_Courtois_2018.jpg/330px-Thibaut_Courtois_2018.jpg',
    kitNumber: 1,
  },

  // ── ELITE ──
  {
    id: 'fb-elite-1',
    name: 'Declan Rice',
    tier: 'ELITE',
    position: 'CDM/CM',
    club: 'Arsenal',
    nation: 'England',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Declan_Rice_2024_%28cropped%29.jpg/330px-Declan_Rice_2024_%28cropped%29.jpg',
    kitNumber: 41,
  },
  {
    id: 'fb-elite-2',
    name: 'William Saliba',
    tier: 'ELITE',
    position: 'CB',
    club: 'Arsenal',
    nation: 'France',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/William_Saliba_2024.jpg/330px-William_Saliba_2024.jpg',
    kitNumber: 2,
  },
  {
    id: 'fb-elite-3',
    name: 'Rafael Leão',
    tier: 'ELITE',
    position: 'LW/LM',
    club: 'AC Milan',
    nation: 'Portugal',
    kitNumber: 10,
  },
  {
    id: 'fb-elite-4',
    name: 'Federico Valverde',
    tier: 'ELITE',
    position: 'CM/RM',
    club: 'Real Madrid',
    nation: 'Uruguay',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Federico_Valverde_2024.jpg/330px-Federico_Valverde_2024.jpg',
    kitNumber: 8,
  },
  {
    id: 'fb-elite-5',
    name: 'Alisson Becker',
    tier: 'ELITE',
    position: 'GK',
    club: 'Liverpool',
    nation: 'Brazil',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Alisson_Becker_2018.jpg/330px-Alisson_Becker_2018.jpg',
    kitNumber: 1,
  },

  // ── GOLD ──
  {
    id: 'fb-gold-1',
    name: 'Bruno Guimarães',
    tier: 'GOLD',
    position: 'CM/CDM',
    club: 'Newcastle United',
    nation: 'Brazil',
    kitNumber: 39,
  },
  {
    id: 'fb-gold-2',
    name: 'Darwin Núñez',
    tier: 'GOLD',
    position: 'ST/LW',
    club: 'Liverpool',
    nation: 'Uruguay',
    kitNumber: 9,
  },
  {
    id: 'fb-gold-3',
    name: 'Gabriel Martinelli',
    tier: 'GOLD',
    position: 'LW/LM',
    club: 'Arsenal',
    nation: 'Brazil',
    kitNumber: 11,
  },
  {
    id: 'fb-gold-4',
    name: 'Micky van de Ven',
    tier: 'GOLD',
    position: 'CB',
    club: 'Tottenham Hotspur',
    nation: 'Netherlands',
    kitNumber: 37,
  },
  {
    id: 'fb-gold-5',
    name: 'David Raya',
    tier: 'GOLD',
    position: 'GK',
    club: 'Arsenal',
    nation: 'Spain',
    kitNumber: 22,
  },

  // ── SILVER ──
  {
    id: 'fb-silver-1',
    name: 'Archie Gray',
    tier: 'SILVER',
    position: 'RB/CM',
    club: 'Tottenham Hotspur',
    nation: 'England',
    kitNumber: 14,
  },
  {
    id: 'fb-silver-2',
    name: 'Kobbie Mainoo',
    tier: 'SILVER',
    position: 'CM/CDM',
    club: 'Manchester United',
    nation: 'England',
    kitNumber: 37,
  },
  {
    id: 'fb-silver-3',
    name: 'Rico Lewis',
    tier: 'SILVER',
    position: 'RB/LB',
    club: 'Manchester City',
    nation: 'England',
    kitNumber: 82,
  },

  // ── BRONZE ──
  {
    id: 'fb-bronze-1',
    name: 'Ethan Nwaneri',
    tier: 'BRONZE',
    position: 'CAM/RW',
    club: 'Arsenal',
    nation: 'England',
    kitNumber: 53,
  },
  {
    id: 'fb-bronze-2',
    name: 'Shea Lacey',
    tier: 'BRONZE',
    position: 'RW/CAM',
    club: 'Manchester United',
    nation: 'England',
    kitNumber: 72,
  },
];
