import { RankQuestionInput, validateQuestionBank } from "../rank/validate";

export const initialRankQuestions: RankQuestionInput[] = [
  // ── 1. CLUBS & TROPHIES: Premier League Era Titles ─────────────────
  {
    slug: "pl-titles-era-1992-2026",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 clubs by Premier League titles won",
      ar: "رتّب الأندية الخمسة حسب عدد مرات الفوز بالدوري الإنجليزي الممتاز",
    },
    subtitle: {
      en: "Premier League era only, 1992–93 to present",
      ar: "حقبة البريميرليج فقط من 1992–93 حتى الآن",
    },
    metricLabel: { en: "Titles", ar: "ألقاب" },
    direction: "desc",
    difficulty: "EASY",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["premier-league", "clubs", "trophies", "england"],
    answers: [
      {
        answerKey: "pl_manu",
        name: { en: "Manchester United", ar: "مانشستر يونايتد" },
        media: { type: "club", fallbackText: "MU" },
        value: 13,
        valueLabel: { en: "13 Titles", ar: "13 لقب" },
        correctRank: 1,
      },
      {
        answerKey: "pl_mancity",
        name: { en: "Manchester City", ar: "مانشستر سيتي" },
        media: { type: "club", fallbackText: "MC" },
        value: 8,
        valueLabel: { en: "8 Titles", ar: "8 ألقاب" },
        correctRank: 2,
      },
      {
        answerKey: "pl_chelsea",
        name: { en: "Chelsea", ar: "تشيلسي" },
        media: { type: "club", fallbackText: "CHE" },
        value: 5,
        valueLabel: { en: "5 Titles", ar: "5 ألقاب" },
        correctRank: 3,
      },
      {
        answerKey: "pl_arsenal",
        name: { en: "Arsenal", ar: "أرسنال" },
        media: { type: "club", fallbackText: "ARS" },
        value: 4,
        valueLabel: { en: "4 Titles", ar: "4 ألقاب" },
        correctRank: 4,
      },
      {
        answerKey: "pl_liverpool",
        name: { en: "Liverpool", ar: "ليفربول" },
        media: { type: "club", fallbackText: "LIV" },
        value: 2,
        valueLabel: { en: "2 Titles", ar: "لقبان" },
        correctRank: 5,
      },
    ],
  },

  // ── 2. TOURNAMENTS & STATS: Total Goals in World Cup Editions ─────
  {
    slug: "world-cup-total-goals-by-edition",
    scopeType: "PER_COMPETITION",
    title: {
      en: "Rank these 5 FIFA World Cup editions by total goals scored",
      ar: "رتّب نسخ كأس العالم الخمسة حسب إجمالي الأهداف المسجلة في البطولة",
    },
    subtitle: {
      en: "All tournament matches included",
      ar: "شامل جميع مباريات البطولة",
    },
    metricLabel: { en: "Goals", ar: "أهداف" },
    direction: "desc",
    difficulty: "MEDIUM",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["world-cup", "tournaments", "goals"],
    answers: [
      {
        answerKey: "wc_2026",
        name: { en: "2026 World Cup", ar: "كأس العالم 2026" },
        subText: { en: "USA / Canada / Mexico", ar: "أمريكا / كندا / المكسيك" },
        media: { type: "tournament", fallbackText: "WC26" },
        value: 308,
        valueLabel: { en: "308 Goals", ar: "308 أهداف" },
        correctRank: 1,
      },
      {
        answerKey: "wc_2022",
        name: { en: "2022 World Cup", ar: "كأس العالم 2022" },
        subText: { en: "Qatar", ar: "قطر" },
        media: { type: "tournament", fallbackText: "WC22" },
        value: 172,
        valueLabel: { en: "172 Goals", ar: "172 هدف" },
        correctRank: 2,
      },
      {
        answerKey: "wc_2014",
        name: { en: "2014 World Cup", ar: "كأس العالم 2014" },
        subText: { en: "Brazil", ar: "البرازيل" },
        media: { type: "tournament", fallbackText: "WC14" },
        value: 171,
        valueLabel: { en: "171 Goals", ar: "171 هدف" },
        correctRank: 3,
      },
      {
        answerKey: "wc_2018",
        name: { en: "2018 World Cup", ar: "كأس العالم 2018" },
        subText: { en: "Russia", ar: "روسيا" },
        media: { type: "tournament", fallbackText: "WC18" },
        value: 169,
        valueLabel: { en: "169 Goals", ar: "169 هدف" },
        correctRank: 4,
      },
      {
        answerKey: "wc_2010",
        name: { en: "2010 World Cup", ar: "كأس العالم 2010" },
        subText: { en: "South Africa", ar: "جنوب أفريقيا" },
        media: { type: "tournament", fallbackText: "WC10" },
        value: 145,
        valueLabel: { en: "145 Goals", ar: "145 هدف" },
        correctRank: 5,
      },
    ],
  },

  // ── 3. SEASONS & POINTS: Domestic League Points ─────────────────────
  {
    slug: "club-seasons-points-record-set-1",
    scopeType: "PER_SEASON",
    title: {
      en: "Rank these 5 club-seasons by points won in their domestic league",
      ar: "رتّب مواسم الأندية الخمسة حسب عدد النقاط التي حققها الفريق في الدوري المحلي",
    },
    subtitle: {
      en: "Top-flight domestic league points total",
      ar: "إجمالي النقاط في الدوري المحلي للدرجة الأولى",
    },
    metricLabel: { en: "Points", ar: "نقاط" },
    direction: "desc",
    difficulty: "HARD",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["club-seasons", "points", "records"],
    answers: [
      {
        answerKey: "cs_juve_1314",
        name: { en: "Juventus (2013–14)", ar: "يوفنتوس (2013–14)" },
        subText: { en: "Serie A", ar: "الدوري الإيطالي" },
        media: { type: "club", fallbackText: "JUV" },
        value: 102,
        valueLabel: { en: "102 Points", ar: "102 نقطة" },
        correctRank: 1,
      },
      {
        answerKey: "cs_liv_1819",
        name: { en: "Liverpool (2018–19)", ar: "ليفربول (2018–19)" },
        subText: { en: "Premier League", ar: "الدوري الإنجليزي" },
        media: { type: "club", fallbackText: "LIV" },
        value: 97,
        valueLabel: { en: "97 Points", ar: "97 نقطة" },
        correctRank: 2,
      },
      {
        answerKey: "cs_mancity_2122",
        name: { en: "Man City (2021–22)", ar: "مانشستر سيتي (2021–22)" },
        subText: { en: "Premier League", ar: "الدوري الإنجليزي" },
        media: { type: "club", fallbackText: "MC" },
        value: 93,
        valueLabel: { en: "93 Points", ar: "93 نقطة" },
        correctRank: 3,
      },
      {
        answerKey: "cs_barca_0809",
        name: { en: "Barcelona (2008–09)", ar: "برشلونة (2008–09)" },
        subText: { en: "La Liga", ar: "الدوري الإسباني" },
        media: { type: "club", fallbackText: "FCB" },
        value: 87,
        valueLabel: { en: "87 Points", ar: "87 نقطة" },
        correctRank: 4,
      },
      {
        answerKey: "cs_bayern_1920",
        name: { en: "Bayern Munich (2019–20)", ar: "بايرن ميونخ (2019–20)" },
        subText: { en: "Bundesliga (34 games)", ar: "الدوري الألماني (34 مباراة)" },
        media: { type: "club", fallbackText: "BAY" },
        value: 82,
        valueLabel: { en: "82 Points", ar: "82 نقطة" },
        correctRank: 5,
      },
    ],
  },

  // ── 4. NATIONAL TEAMS: World Cup Titles ────────────────────────────
  {
    slug: "world-cup-titles-national-teams",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 national teams by FIFA World Cup titles won",
      ar: "رتّب المنتخبات الخمسة حسب عدد مرات الفوز بكأس العالم",
    },
    subtitle: {
      en: "From 1930 through 2026",
      ar: "من 1930 وحتى بطولة 2026",
    },
    metricLabel: { en: "World Cups", ar: "كؤوس عالم" },
    direction: "desc",
    difficulty: "EASY",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["national-teams", "world-cup", "titles"],
    answers: [
      {
        answerKey: "nt_brazil",
        name: { en: "Brazil", ar: "البرازيل" },
        media: { type: "nation", fallbackText: "BRA" },
        value: 5,
        valueLabel: { en: "5 Titles", ar: "5 ألقاب" },
        correctRank: 1,
      },
      {
        answerKey: "nt_germany",
        name: { en: "Germany", ar: "ألمانيا" },
        media: { type: "nation", fallbackText: "GER" },
        value: 4,
        valueLabel: { en: "4 Titles", ar: "4 ألقاب" },
        correctRank: 2,
      },
      {
        answerKey: "nt_argentina",
        name: { en: "Argentina", ar: "الأرجنتين" },
        media: { type: "nation", fallbackText: "ARG" },
        value: 3,
        valueLabel: { en: "3 Titles", ar: "3 ألقاب" },
        correctRank: 3,
      },
      {
        answerKey: "nt_france",
        name: { en: "France", ar: "فرنسا" },
        media: { type: "nation", fallbackText: "FRA" },
        value: 2,
        valueLabel: { en: "2 Titles", ar: "لقبان" },
        correctRank: 4,
      },
      {
        answerKey: "nt_england",
        name: { en: "England", ar: "إنجلترا" },
        media: { type: "nation", fallbackText: "ENG" },
        value: 1,
        valueLabel: { en: "1 Title", ar: "لقب واحد" },
        correctRank: 5,
      },
    ],
  },

  // ── 5. PLAYER STINTS: Cristiano Ronaldo League Goals by Stint ─────
  {
    slug: "cr7-league-goals-by-stint",
    scopeType: "PLAYER_STINTS",
    title: {
      en: "Rank these 5 stints of Cristiano Ronaldo by league goals scored",
      ar: "رتّب فترات كريستيانو رونالدو الخمسة حسب عدد أهدافه في الدوري",
    },
    subtitle: {
      en: "Domestic top-flight league goals for each club",
      ar: "أهداف الدوري المحلي مع كل نادٍ خلال الفترة",
    },
    metricLabel: { en: "Goals", ar: "أهداف" },
    direction: "desc",
    difficulty: "HARD",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["cr7", "ronaldo", "stints", "goals"],
    answers: [
      {
        answerKey: "cr7_rma",
        name: { en: "Cristiano Ronaldo", ar: "كريستيانو رونالدو" },
        subText: { en: "Real Madrid (2009–18)", ar: "ريال مدريد (2009–18)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/real-madrid.png", fallbackText: "CR7" },
        value: 312,
        valueLabel: { en: "312 Goals", ar: "312 هدف" },
        correctRank: 1,
      },
      {
        answerKey: "cr7_nassr",
        name: { en: "Cristiano Ronaldo", ar: "كريستيانو رونالدو" },
        subText: { en: "Al-Nassr (2023–present)", ar: "النصر (2023–حتى الآن)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/al-nassr.png", fallbackText: "CR7" },
        value: 103,
        valueLabel: { en: "103 Goals", ar: "103 أهداف" },
        correctRank: 2,
      },
      {
        answerKey: "cr7_manu1",
        name: { en: "Cristiano Ronaldo", ar: "كريستيانو رونالدو" },
        subText: { en: "Man United (2003–09)", ar: "مانشستر يونايتد (2003–09)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/man-utd.png", fallbackText: "CR7" },
        value: 84,
        valueLabel: { en: "84 Goals", ar: "84 هدف" },
        correctRank: 3,
      },
      {
        answerKey: "cr7_juve",
        name: { en: "Cristiano Ronaldo", ar: "كريستيانو رونالدو" },
        subText: { en: "Juventus (2018–21)", ar: "يوفنتوس (2018–21)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/juventus.png", fallbackText: "CR7" },
        value: 81,
        valueLabel: { en: "81 Goals", ar: "81 هدف" },
        correctRank: 4,
      },
      {
        answerKey: "cr7_sporting",
        name: { en: "Cristiano Ronaldo", ar: "كريستيانو رونالدو" },
        subText: { en: "Sporting CP (2002–03)", ar: "سبورتينغ (2002–03)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/sporting.png", fallbackText: "CR7" },
        value: 3,
        valueLabel: { en: "3 Goals", ar: "3 أهداف" },
        correctRank: 5,
      },
    ],
  },

  // ── 6. CLUBS & TROPHIES: European Cup / UCL Titles ────────────────
  {
    slug: "ucl-titles-clubs-all-time",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 clubs by European Cup / UEFA Champions League titles",
      ar: "رتّب الأندية الخمسة حسب عدد ألقاب دوري أبطال أوروبا",
    },
    subtitle: {
      en: "European Cup and Champions League eras combined",
      ar: "مع احتساب حقبة كأس أوروبا ودوري الأبطال معًا",
    },
    metricLabel: { en: "Titles", ar: "ألقاب" },
    direction: "desc",
    difficulty: "EASY",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["champions-league", "ucl", "clubs", "europe"],
    answers: [
      {
        answerKey: "ucl_realmadrid",
        name: { en: "Real Madrid", ar: "ريال مدريد" },
        media: { type: "club", fallbackText: "RMA" },
        value: 15,
        valueLabel: { en: "15 Titles", ar: "15 لقب" },
        correctRank: 1,
      },
      {
        answerKey: "ucl_acmilan",
        name: { en: "AC Milan", ar: "ميلان" },
        media: { type: "club", fallbackText: "ACM" },
        value: 7,
        valueLabel: { en: "7 Titles", ar: "7 ألقاب" },
        correctRank: 2,
      },
      {
        answerKey: "ucl_bayern",
        name: { en: "Bayern Munich", ar: "بايرن ميونخ" },
        media: { type: "club", fallbackText: "BAY" },
        value: 6,
        valueLabel: { en: "6 Titles", ar: "6 ألقاب" },
        correctRank: 3,
      },
      {
        answerKey: "ucl_barcelona",
        name: { en: "Barcelona", ar: "برشلونة" },
        media: { type: "club", fallbackText: "FCB" },
        value: 5,
        valueLabel: { en: "5 Titles", ar: "5 ألقاب" },
        correctRank: 4,
      },
      {
        answerKey: "ucl_ajax",
        name: { en: "Ajax", ar: "أياكس" },
        media: { type: "club", fallbackText: "AJX" },
        value: 4,
        valueLabel: { en: "4 Titles", ar: "4 ألقاب" },
        correctRank: 5,
      },
    ],
  },

  // ── 7. PLAYER STATS: UEFA Champions League All-Time Top Scorers ──
  {
    slug: "ucl-all-time-top-scorers",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 players by UEFA Champions League goals scored",
      ar: "رتّب اللاعبين الخمسة حسب عدد أهدافهم في دوري أبطال أوروبا",
    },
    subtitle: {
      en: "Excluding qualifying rounds, through 2025–26",
      ar: "مع استبعاد الأدوار التمهيدية، حتى نهاية موسم 2025–26",
    },
    metricLabel: { en: "Goals", ar: "أهداف" },
    direction: "desc",
    difficulty: "MEDIUM",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["ucl", "champions-league", "goals", "messi", "ronaldo"],
    answers: [
      {
        answerKey: "ucl_cr7",
        name: { en: "Cristiano Ronaldo", ar: "كريستيانو رونالدو" },
        media: { type: "player", fallbackText: "CR7" },
        value: 140,
        valueLabel: { en: "140 Goals", ar: "140 هدف" },
        correctRank: 1,
      },
      {
        answerKey: "ucl_messi",
        name: { en: "Lionel Messi", ar: "ليونيل ميسي" },
        media: { type: "player", fallbackText: "LM10" },
        value: 129,
        valueLabel: { en: "129 Goals", ar: "129 هدف" },
        correctRank: 2,
      },
      {
        answerKey: "ucl_lewa",
        name: { en: "Robert Lewandowski", ar: "روبرت ليفاندوفسكي" },
        media: { type: "player", fallbackText: "RL9" },
        value: 109,
        valueLabel: { en: "109 Goals", ar: "109 أهداف" },
        correctRank: 3,
      },
      {
        answerKey: "ucl_benzema",
        name: { en: "Karim Benzema", ar: "كريم بنزيما" },
        media: { type: "player", fallbackText: "KB9" },
        value: 90,
        valueLabel: { en: "90 Goals", ar: "90 هدف" },
        correctRank: 4,
      },
      {
        answerKey: "ucl_raul",
        name: { en: "Raúl González", ar: "راؤول غونزاليس" },
        media: { type: "player", fallbackText: "RG7" },
        value: 71,
        valueLabel: { en: "71 Goals", ar: "71 هدف" },
        correctRank: 5,
      },
    ],
  },

  // ── 8. NATIONAL TEAMS: World Cup Total Matches Won ───────────────
  {
    slug: "world-cup-matches-won-national-teams",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 men's national teams by FIFA World Cup matches won",
      ar: "رتّب المنتخبات الخمسة حسب عدد مباريات الفوز في نهائيات كأس العالم",
    },
    subtitle: {
      en: "All finals tournament matches from 1930 through 2026",
      ar: "شامل جميع مباريات النهائيات من 1930 وحتى 2026",
    },
    metricLabel: { en: "Wins", ar: "انتصارات" },
    direction: "desc",
    difficulty: "MEDIUM",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["national-teams", "world-cup", "wins"],
    answers: [
      {
        answerKey: "wcw_brazil",
        name: { en: "Brazil", ar: "البرازيل" },
        media: { type: "nation", fallbackText: "BRA" },
        value: 79,
        valueLabel: { en: "79 Wins", ar: "79 فوز" },
        correctRank: 1,
      },
      {
        answerKey: "wcw_germany",
        name: { en: "Germany", ar: "ألمانيا" },
        media: { type: "nation", fallbackText: "GER" },
        value: 70,
        valueLabel: { en: "70 Wins", ar: "70 فوز" },
        correctRank: 2,
      },
      {
        answerKey: "wcw_argentina",
        name: { en: "Argentina", ar: "الأرجنتين" },
        media: { type: "nation", fallbackText: "ARG" },
        value: 54,
        valueLabel: { en: "54 Wins", ar: "54 فوز" },
        correctRank: 3,
      },
      {
        answerKey: "wcw_france",
        name: { en: "France", ar: "فرنسا" },
        media: { type: "nation", fallbackText: "FRA" },
        value: 45,
        valueLabel: { en: "45 Wins", ar: "45 فوز" },
        correctRank: 4,
      },
      {
        answerKey: "wcw_spain",
        name: { en: "Spain", ar: "إسبانيا" },
        media: { type: "nation", fallbackText: "ESP" },
        value: 38,
        valueLabel: { en: "38 Wins", ar: "38 فوز" },
        correctRank: 5,
      },
    ],
  },

  // ── 9. PLAYER STINTS: Lionel Messi League Goals by Stint ─────────
  {
    slug: "messi-league-goals-by-stint",
    scopeType: "PLAYER_STINTS",
    title: {
      en: "Rank these 5 stints of Lionel Messi by league goals scored",
      ar: "رتّب فترات ليونيل ميسي الخمسة حسب عدد أهدافه في الدوري",
    },
    subtitle: {
      en: "Domestic top-flight league goals for each club",
      ar: "أهداف الدوري المحلي مع كل نادٍ خلال الفترة",
    },
    metricLabel: { en: "Goals", ar: "أهداف" },
    direction: "desc",
    difficulty: "HARD",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["messi", "barcelona", "stints", "goals"],
    answers: [
      {
        answerKey: "messi_barca",
        name: { en: "Lionel Messi", ar: "ليونيل ميسي" },
        subText: { en: "Barcelona (2004–21)", ar: "برشلونة (2004–21)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/barcelona.png", fallbackText: "LM10" },
        value: 474,
        valueLabel: { en: "474 Goals", ar: "474 هدف" },
        correctRank: 1,
      },
      {
        answerKey: "messi_miami",
        name: { en: "Lionel Messi", ar: "ليونيل ميسي" },
        subText: { en: "Inter Miami (2023–present)", ar: "إنتر ميامي (2023–حتى الآن)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/inter-miami.png", fallbackText: "LM10" },
        value: 74,
        valueLabel: { en: "74 Goals", ar: "74 هدف" },
        correctRank: 2,
      },
      {
        answerKey: "messi_psg",
        name: { en: "Lionel Messi", ar: "ليونيل ميسي" },
        subText: { en: "PSG (2021–23)", ar: "باريس سان جيرمان (2021–23)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/psg.png", fallbackText: "LM10" },
        value: 22,
        valueLabel: { en: "22 Goals", ar: "22 هدف" },
        correctRank: 3,
      },
      {
        answerKey: "messi_barca_b",
        name: { en: "Lionel Messi", ar: "ليونيل ميسي" },
        subText: { en: "Barcelona B (2004–05)", ar: "برشلونة ب (2004–05)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/barcelona.png", fallbackText: "LM10" },
        value: 6,
        valueLabel: { en: "6 Goals", ar: "6 أهداف" },
        correctRank: 4,
      },
      {
        answerKey: "messi_barca_c",
        name: { en: "Lionel Messi", ar: "ليونيل ميسي" },
        subText: { en: "Barcelona C (2003–04)", ar: "برشلونة ج (2003–04)" },
        media: { type: "player", secondaryBadgeUrl: "/badges/barcelona.png", fallbackText: "LM10" },
        value: 5,
        valueLabel: { en: "5 Goals", ar: "5 أهداف" },
        correctRank: 5,
      },
    ],
  },

  // ── 10. NATIONAL TEAMS: World Cup Total Goals Scored ──────────────
  {
    slug: "world-cup-total-goals-national-teams",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 national teams by total FIFA World Cup goals scored",
      ar: "رتّب المنتخبات الخمسة حسب إجمالي أهدافها في نهائيات كأس العالم",
    },
    subtitle: {
      en: "From 1930 through 2026 tournaments",
      ar: "من 1930 وحتى بطولة 2026",
    },
    metricLabel: { en: "Goals", ar: "أهداف" },
    direction: "desc",
    difficulty: "MEDIUM",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["national-teams", "world-cup", "goals"],
    answers: [
      {
        answerKey: "wcg_brazil",
        name: { en: "Brazil", ar: "البرازيل" },
        media: { type: "nation", fallbackText: "BRA" },
        value: 247,
        valueLabel: { en: "247 Goals", ar: "247 هدف" },
        correctRank: 1,
      },
      {
        answerKey: "wcg_germany",
        name: { en: "Germany", ar: "ألمانيا" },
        media: { type: "nation", fallbackText: "GER" },
        value: 232,
        valueLabel: { en: "232 Goals", ar: "232 هدف" },
        correctRank: 2,
      },
      {
        answerKey: "wcg_argentina",
        name: { en: "Argentina", ar: "الأرجنتين" },
        media: { type: "nation", fallbackText: "ARG" },
        value: 155,
        valueLabel: { en: "155 Goals", ar: "155 هدف" },
        correctRank: 3,
      },
      {
        answerKey: "wcg_france",
        name: { en: "France", ar: "فرنسا" },
        media: { type: "nation", fallbackText: "FRA" },
        value: 145,
        valueLabel: { en: "145 Goals", ar: "145 هدف" },
        correctRank: 4,
      },
      {
        answerKey: "wcg_spain",
        name: { en: "Spain", ar: "إسبانيا" },
        media: { type: "nation", fallbackText: "ESP" },
        value: 105,
        valueLabel: { en: "105 Goals", ar: "105 أهداف" },
        correctRank: 5,
      },
    ],
  },

  // ── 11. CLUBS: South American Copa Libertadores Titles ───────────
  {
    slug: "copa-libertadores-titles",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 South American clubs by CONMEBOL Libertadores titles",
      ar: "رتّب الأندية الخمسة حسب عدد ألقاب كوبا ليبرتادوريس",
    },
    subtitle: {
      en: "From competition start in 1960 through 2026",
      ar: "من أول نسخة عام 1960 وحتى 2026",
    },
    metricLabel: { en: "Titles", ar: "ألقاب" },
    direction: "desc",
    difficulty: "HARD",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["copa-libertadores", "south-america", "clubs", "conmebol"],
    answers: [
      {
        answerKey: "lib_independiente",
        name: { en: "Independiente", ar: "إنديبندينتي" },
        subText: { en: "Argentina", ar: "الأرجنتين" },
        media: { type: "club", fallbackText: "IND" },
        value: 7,
        valueLabel: { en: "7 Titles", ar: "7 ألقاب" },
        correctRank: 1,
      },
      {
        answerKey: "lib_boca",
        name: { en: "Boca Juniors", ar: "بوكا جونيورز" },
        subText: { en: "Argentina", ar: "الأرجنتين" },
        media: { type: "club", fallbackText: "BOC" },
        value: 6,
        valueLabel: { en: "6 Titles", ar: "6 ألقاب" },
        correctRank: 2,
      },
      {
        answerKey: "lib_penarol",
        name: { en: "Peñarol", ar: "بينيارول" },
        subText: { en: "Uruguay", ar: "أوروجواي" },
        media: { type: "club", fallbackText: "PEN" },
        value: 5,
        valueLabel: { en: "5 Titles", ar: "5 ألقاب" },
        correctRank: 3,
      },
      {
        answerKey: "lib_river",
        name: { en: "River Plate", ar: "ريفر بليت" },
        subText: { en: "Argentina", ar: "الأرجنتين" },
        media: { type: "club", fallbackText: "RIV" },
        value: 4,
        valueLabel: { en: "4 Titles", ar: "4 ألقاب" },
        correctRank: 4,
      },
      {
        answerKey: "lib_santos",
        name: { en: "Santos FC", ar: "سانتوس" },
        subText: { en: "Brazil", ar: "البرازيل" },
        media: { type: "club", fallbackText: "SAN" },
        value: 3,
        valueLabel: { en: "3 Titles", ar: "3 ألقاب" },
        correctRank: 5,
      },
    ],
  },

  // ── 12. PLAYER STATS: UEFA Champions League All-Time Assists ──────
  {
    slug: "ucl-all-time-assists",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 players by UEFA Champions League assists provided",
      ar: "رتّب اللاعبين الخمسة حسب عدد تمريراتهم الحاسمة في دوري أبطال أوروبا",
    },
    subtitle: {
      en: "Excluding qualifying rounds, through 2025–26",
      ar: "مع استبعاد الأدوار التمهيدية، حتى نهاية موسم 2025–26",
    },
    metricLabel: { en: "Assists", ar: "تمريرات حاسمة" },
    direction: "desc",
    difficulty: "HARD",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["ucl", "assists", "playmakers"],
    answers: [
      {
        answerKey: "ast_cr7",
        name: { en: "Cristiano Ronaldo", ar: "كريستيانو رونالدو" },
        media: { type: "player", fallbackText: "CR7" },
        value: 42,
        valueLabel: { en: "42 Assists", ar: "42 تمريرة" },
        correctRank: 1,
      },
      {
        answerKey: "ast_dimaria",
        name: { en: "Ángel Di María", ar: "أنخيل دي ماريا" },
        media: { type: "player", fallbackText: "ADM" },
        value: 41,
        valueLabel: { en: "41 Assists", ar: "41 تمريرة" },
        correctRank: 2,
      },
      {
        answerKey: "ast_messi",
        name: { en: "Lionel Messi", ar: "ليونيل ميسي" },
        media: { type: "player", fallbackText: "LM10" },
        value: 40,
        valueLabel: { en: "40 Assists", ar: "40 تمريرة" },
        correctRank: 3,
      },
      {
        answerKey: "ast_neymar",
        name: { en: "Neymar Jr", ar: "نيمار" },
        media: { type: "player", fallbackText: "NJR" },
        value: 33,
        valueLabel: { en: "33 Assists", ar: "33 تمريرة" },
        correctRank: 4,
      },
      {
        answerKey: "ast_vini",
        name: { en: "Vinícius Júnior", ar: "فينيسيوس جونيور" },
        media: { type: "player", fallbackText: "VJR" },
        value: 32,
        valueLabel: { en: "32 Assists", ar: "32 تمريرة" },
        correctRank: 5,
      },
    ],
  },

  // ── 13. PLAYER STATS: Single-Club UCL Goals ──────────────────────
  {
    slug: "ucl-goals-for-single-club",
    scopeType: "PER_CLUB",
    title: {
      en: "Rank these 5 players by UEFA Champions League goals for a single club",
      ar: "رتّب اللاعبين الخمسة حسب أهدافهم في دوري أبطال أوروبا مع نادٍ واحد فقط",
    },
    subtitle: {
      en: "Goals scored while representing that specific club",
      ar: "الأهداف المسجلة بقميص هذا النادي المحدد",
    },
    metricLabel: { en: "Goals", ar: "أهداف" },
    direction: "desc",
    difficulty: "MEDIUM",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["ucl", "goals", "single-club"],
    answers: [
      {
        answerKey: "sc_messi_barca",
        name: { en: "Lionel Messi", ar: "ليونيل ميسي" },
        subText: { en: "Barcelona", ar: "برشلونة" },
        media: { type: "player", secondaryBadgeUrl: "/badges/barcelona.png", fallbackText: "LM10" },
        value: 120,
        valueLabel: { en: "120 Goals", ar: "120 هدف" },
        correctRank: 1,
      },
      {
        answerKey: "sc_cr7_real",
        name: { en: "Cristiano Ronaldo", ar: "كريستيانو رونالدو" },
        subText: { en: "Real Madrid", ar: "ريال مدريد" },
        media: { type: "player", secondaryBadgeUrl: "/badges/real-madrid.png", fallbackText: "CR7" },
        value: 105,
        valueLabel: { en: "105 Goals", ar: "105 أهداف" },
        correctRank: 2,
      },
      {
        answerKey: "sc_benzema_real",
        name: { en: "Karim Benzema", ar: "كريم بنزيما" },
        subText: { en: "Real Madrid", ar: "ريال مدريد" },
        media: { type: "player", secondaryBadgeUrl: "/badges/real-madrid.png", fallbackText: "KB9" },
        value: 78,
        valueLabel: { en: "78 Goals", ar: "78 هدف" },
        correctRank: 3,
      },
      {
        answerKey: "sc_lewa_bayern",
        name: { en: "Robert Lewandowski", ar: "روبرت ليفاندوفسكي" },
        subText: { en: "Bayern Munich", ar: "بايرن ميونخ" },
        media: { type: "player", secondaryBadgeUrl: "/badges/bayern.png", fallbackText: "RL9" },
        value: 76,
        valueLabel: { en: "76 Goals", ar: "76 هدف" },
        correctRank: 4,
      },
      {
        answerKey: "sc_muller_bayern",
        name: { en: "Thomas Müller", ar: "توماس مولر" },
        subText: { en: "Bayern Munich", ar: "بايرن ميونخ" },
        media: { type: "player", secondaryBadgeUrl: "/badges/bayern.png", fallbackText: "TM25" },
        value: 56,
        valueLabel: { en: "56 Goals", ar: "56 هدف" },
        correctRank: 5,
      },
    ],
  },

  // ── 14. NATIONAL TEAMS: UEFA European Championship Matches Won ───
  {
    slug: "euro-matches-won-national-teams",
    scopeType: "ALL_TIME",
    title: {
      en: "Rank these 5 national teams by UEFA EURO tournament matches won",
      ar: "رتّب المنتخبات الخمسة حسب عدد مباريات الفوز في نهائيات بطولة أمم أوروبا",
    },
    subtitle: {
      en: "EURO finals matches from 1960 through EURO 2024",
      ar: "مباريات نهائيات اليورو من 1960 وحتى يورو 2024",
    },
    metricLabel: { en: "Wins", ar: "انتصارات" },
    direction: "desc",
    difficulty: "MEDIUM",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["euro", "national-teams", "uefa", "wins"],
    answers: [
      {
        answerKey: "eur_germany",
        name: { en: "Germany", ar: "ألمانيا" },
        media: { type: "nation", fallbackText: "GER" },
        value: 30,
        valueLabel: { en: "30 Wins", ar: "30 فوز" },
        correctRank: 1,
      },
      {
        answerKey: "eur_spain",
        name: { en: "Spain", ar: "إسبانيا" },
        media: { type: "nation", fallbackText: "ESP" },
        value: 27,
        valueLabel: { en: "27 Wins", ar: "27 فوز" },
        correctRank: 2,
      },
      {
        answerKey: "eur_france",
        name: { en: "France", ar: "فرنسا" },
        media: { type: "nation", fallbackText: "FRA" },
        value: 23,
        valueLabel: { en: "23 Wins", ar: "23 فوز" },
        correctRank: 3,
      },
      {
        answerKey: "eur_italy",
        name: { en: "Italy", ar: "إيطاليا" },
        media: { type: "nation", fallbackText: "ITA" },
        value: 19,
        valueLabel: { en: "19 Wins", ar: "19 فوز" },
        correctRank: 4,
      },
      {
        answerKey: "eur_portugal",
        name: { en: "Portugal", ar: "البرتغال" },
        media: { type: "nation", fallbackText: "POR" },
        value: 18,
        valueLabel: { en: "18 Wins", ar: "18 فوز" },
        correctRank: 5,
      },
    ],
  },

  // ── 15. SEASONS & POINTS: Century Points Seasons in Top Leagues ──
  {
    slug: "century-point-domestic-seasons",
    scopeType: "PER_SEASON",
    title: {
      en: "Rank these 5 club-seasons by points won in their domestic league",
      ar: "رتّب مواسم الأندية الخمسة حسب عدد النقاط المحققة في الدوري المحلي",
    },
    subtitle: {
      en: "Standard 3-points-for-a-win system",
      ar: "نظام احتساب 3 نقاط للفوز",
    },
    metricLabel: { en: "Points", ar: "نقاط" },
    direction: "desc",
    difficulty: "HARD",
    asOfDate: "2026-08",
    isActive: true,
    tags: ["points", "club-seasons", "centurions"],
    answers: [
      {
        answerKey: "cps_juve_1314",
        name: { en: "Juventus (2013–14)", ar: "يوفنتوس (2013–14)" },
        subText: { en: "Serie A", ar: "الدوري الإيطالي" },
        media: { type: "club", fallbackText: "JUV" },
        value: 102,
        valueLabel: { en: "102 Points", ar: "102 نقطة" },
        correctRank: 1,
      },
      {
        answerKey: "cps_mancity_1718",
        name: { en: "Man City (2017–18)", ar: "مانشستر سيتي (2017–18)" },
        subText: { en: "Premier League (Centurions)", ar: "البريميرليج (المئوية)" },
        media: { type: "club", fallbackText: "MC" },
        value: 100,
        valueLabel: { en: "100 Points", ar: "100 نقطة" },
        correctRank: 2,
      },
      {
        answerKey: "cps_liv_1920",
        name: { en: "Liverpool (2019–20)", ar: "ليفربول (2019–20)" },
        subText: { en: "Premier League", ar: "الدوري الإنجليزي" },
        media: { type: "club", fallbackText: "LIV" },
        value: 99,
        valueLabel: { en: "99 Points", ar: "99 نقطة" },
        correctRank: 3,
      },
      {
        answerKey: "cps_psg_1516",
        name: { en: "PSG (2015–16)", ar: "باريس سان جيرمان (2015–16)" },
        subText: { en: "Ligue 1", ar: "الدوري الفرنسي" },
        media: { type: "club", fallbackText: "PSG" },
        value: 96,
        valueLabel: { en: "96 Points", ar: "96 نقطة" },
        correctRank: 4,
      },
      {
        answerKey: "cps_bayern_1213",
        name: { en: "Bayern Munich (2012–13)", ar: "بايرن ميونخ (2012–13)" },
        subText: { en: "Bundesliga", ar: "الدوري الألماني" },
        media: { type: "club", fallbackText: "BAY" },
        value: 91,
        valueLabel: { en: "91 Points", ar: "91 نقطة" },
        correctRank: 5,
      },
    ],
  },
];

// Invariant pre-flight validation on load
validateQuestionBank(initialRankQuestions);
