const fs = require('fs');
const path = require('path');

// 1. Tier Mappings extracted from prompt
const TEAM_TIERS = {
  "alaves": {
    "Sivera": "GOLD",
    "Jesús Owono": "GOLD",
    "R. Montero": "SILVER",
    "G. Swiderski": "SILVER",
    "Jonny": "ELITE",
    "M. Diarra": "GOLD",
    "F. Garcés": "GOLD",
    "Álvaro García": "GOLD",
    "V. Koski": "SILVER",
    "Hugo Novoa": "SILVER",
    "N. Tenaglia": "SILVER",
    "Yusi": "SILVER",
    "Carlos Ballestero García": "BRONZE",
    "P. Sanz": "BRONZE",
    "Carles Aleñá": "ELITE",
    "Antonio Blanco": "GOLD",
    "Guevara": "GOLD",
    "C. Benavídez": "GOLD",
    "Denis Suárez": "GOLD",
    "Pablo Ibáñez": "SILVER",
    "Mikel Rodríguez": "SILVER",
    "L. Boyé": "GOLD",
    "M. Díaz": "GOLD",
    "Toni Martínez": "GOLD",
    "A. Rebbach": "GOLD",
    "Angel Pérez": "SILVER",
    "A. Manas": "BRONZE",
    "Miguel Rodríguez": "SILVER"
  },
  "athletic-club": {
    "Unai Simón": "ELITE_PLUS",
    "Álex Padilla": "GOLD",
    "Mikel Santos": "BRONZE",
    "Dani Vivian": "ELITE",
    "Yeray": "GOLD",
    "Aymeric Laporte": "ELITE",
    "Yuri": "GOLD",
    "Jesús Areso": "GOLD",
    "Unai Eguíluz": "SILVER",
    "Gorosabel": "GOLD",
    "Iker Monreal": "SILVER",
    "Aitor Paredes": "SILVER",
    "A. Boiro": "SILVER",
    "Alejandro Rego": "BRONZE",
    "Hugo Rincón": "BRONZE",
    "Oihan Sancet": "ELITE_PLUS",
    "Mikel Jauregizar": "ELITE",
    "Mikel Vesga": "GOLD",
    "Ruíz de Galarreta": "GOLD",
    "Beñat Prados": "GOLD",
    "Robert Navarro": "GOLD",
    "Peio Canales": "SILVER",
    "Beñat Gerenabarrena": "SILVER",
    "S. Sanchez": "BRONZE",
    "E. Gift": "BRONZE",
    "Nico Williams": "MASTER",
    "I. Williams": "ELITE_PLUS",
    "Álex Berenguer": "ELITE",
    "Gorka Guruzeta": "GOLD",
    "Álvaro Djaló": "GOLD",
    "Nico Serrano": "GOLD",
    "Maroan Sannadi": "SILVER",
    "A. Hierro": "SILVER"
  },
  "atletico-madrid": {
    "J. Oblak": "ELITE_PLUS",
    "J. Musso": "GOLD",
    "Salvador Esquivel": "SILVER",
    "Mario de Luis": "BRONZE",
    "Álvaro Moreno": "BRONZE",
    "J. Giménez": "ELITE",
    "Robin Le Normand": "ELITE",
    "Álex Grimaldo": "ELITE",
    "D. Hancko": "ELITE",
    "Marcos Llorente": "ELITE",
    "N. Molina": "GOLD",
    "Marc Pubill": "GOLD",
    "Dani Martínez": "GOLD",
    "Javier Boñar": "SILVER",
    "Julio Díaz del Romo": "BRONZE",
    "A. Puric": "BRONZE",
    "M. Ruggeri": "SILVER",
    "G. Spina": "SILVER",
    "Pablo Barrios": "ELITE_PLUS",
    "M. Hjulmand": "ELITE",
    "Koke": "ELITE",
    "J. Cardoso": "GOLD",
    "Lee Kang-In": "ELITE",
    "Rodrigo Mendoza": "SILVER",
    "J. Morcillo": "SILVER",
    "T. Seidu": "SILVER",
    "Javi Serrano": "SILVER",
    "O. Vargas": "SILVER",
    "J. Álvarez": "MASTER",
    "Álex Baena": "ELITE_PLUS",
    "A. Sørloth": "ELITE",
    "A. Lookman": "ELITE",
    "T. Almada": "ELITE",
    "G. Simeone": "GOLD",
    "M. Llorente": "SILVER",
    "Rayane Belid": "BRONZE",
    "I. Luque": "SILVER"
  },
  "barcelona": {
    "Joan García": "ELITE",
    "W. Szczęsny": "GOLD",
    "Eder Aller": "BRONZE",
    "Pau Cubarsí": "MASTER",
    "Pau Cubarsí Paredes": "MASTER",
    "J. Koundé": "ELITE_PLUS",
    "R. Araújo": "ELITE",
    "Alejandro Balde": "ELITE_PLUS",
    "A. Christensen": "GOLD",
    "Eric García": "GOLD",
    "Gerard Martín": "GOLD",
    "Álvaro Cortés Moyano": "BRONZE",
    "X. Espart": "BRONZE",
    "Jofre Torrents": "BRONZE",
    "Pedri": "MASTER",
    "F. de Jong": "ELITE_PLUS",
    "Gavi": "ELITE_PLUS",
    "Fermín": "ELITE_PLUS",
    "Marc Casadó": "ELITE",
    "Marc Bernal": "GOLD",
    "Tomás Marqués": "BRONZE",
    "Dani Olmo": "ELITE_PLUS",
    "Lamine Yamal": "MASTER",
    "Raphinha": "MASTER",
    "Ferran Torres": "ELITE",
    "R. Bardghji": "ELITE",
    "A. Gordon": "GOLD",
    "K. Adeyemi": "ELITE",
    "Juan Hernández": "BRONZE",
    "H. Abdelkarim": "BRONZE"
  },
  "celta-vigo": {
    "Iván Villar": "GOLD",
    "I. Radu": "SILVER",
    "Coke Carrillo": "BRONZE",
    "C. Starfelt": "GOLD",
    "Unai Núñez": "GOLD",
    "Marcos Alonso": "GOLD",
    "Javi Galán": "GOLD",
    "Carlos Domínguez": "GOLD",
    "Sergio Carreira": "SILVER",
    "Manu Sánchez": "SILVER",
    "Javi Rodríguez": "SILVER",
    "Javi Rueda": "SILVER",
    "Yoel Lago": "SILVER",
    "J. Lopez": "BRONZE",
    "Álvaro Núñez": "SILVER",
    "M. Vecino": "GOLD",
    "I. Moriba": "ELITE",
    "Hugo González": "GOLD",
    "Aleix Febas": "GOLD",
    "Manu Fernández": "SILVER",
    "Andrés Antañón": "SILVER",
    "O. Marcos": "SILVER",
    "Miguel Román": "BRONZE",
    "H. Burcio": "BRONZE",
    "Iago Aspas": "ELITE",
    "Borja Iglesias": "GOLD",
    "Hugo Álvarez": "ELITE",
    "Pablo Durán": "GOLD",
    "Ferran Jutglà": "GOLD",
    "W. Swedberg": "SILVER",
    "B. Somuah": "SILVER",
    "J. El Abdellaoui": "BRONZE"
  },
  "espanyol": {
    "M. Dmitrović": "GOLD",
    "Ángel Fortuño": "SILVER",
    "Pol Tristán": "BRONZE",
    "Llorenç Serred": "BRONZE",
    "L. Cabrera": "GOLD",
    "Q. Hartman": "GOLD",
    "Pablo Ramón": "SILVER",
    "José Salinas": "SILVER",
    "O. El Hilali": "SILVER",
    "Roger Hinojo": "SILVER",
    "C. Riedel": "SILVER",
    "Miguel Rubio": "SILVER",
    "Rubén Sánchez": "BRONZE",
    "Edu Expósito": "GOLD",
    "Pol Lozano": "GOLD",
    "Urko González": "GOLD",
    "Álex Calatrava": "SILVER",
    "Gabriel Moscardo": "GOLD",
    "F. Gomez": "SILVER",
    "Javier Hernandez": "SILVER",
    "Rafel Bauzà": "BRONZE",
    "Pere Milla": "GOLD",
    "Jofre Carreras": "GOLD",
    "Kike García": "GOLD",
    "Roberto Fernández": "GOLD",
    "Marcos Fernández": "SILVER",
    "T. Dolan": "SILVER",
    "A. Almansa": "BRONZE",
    "Cala": "SILVER"
  },
  "getafe": {
    "David Soria": "GOLD",
    "J. Letáček": "SILVER",
    "Jorge Benito": "BRONZE",
    "Diego Ferrer": "BRONZE",
    "D. Dakonam": "GOLD",
    "Kiko Femenía": "GOLD",
    "A. Abqar": "GOLD",
    "S. Boselli": "SILVER",
    "Z. Tassounte": "SILVER",
    "Andrés García": "SILVER",
    "Davinchi": "SILVER",
    "Gorka Rivera": "BRONZE",
    "Z. Romero": "BRONZE",
    "Jorge Montes": "BRONZE",
    "J. Valou": "BRONZE",
    "Mario Martín": "GOLD",
    "Ramón Terrats": "GOLD",
    "Javi Muñoz": "GOLD",
    "A. R. Alcantara": "SILVER",
    "Adrián Riquelme": "SILVER",
    "Mady Macalou": "BRONZE",
    "Borja Mayoral": "ELITE",
    "Juanmi": "GOLD",
    "M. Satriano": "GOLD",
    "Álex Sancris": "SILVER"
  },
  "girona": {
    "P. Gazzaniga": "GOLD",
    "A. Andreev": "SILVER",
    "V. Krapyvtsov": "BRONZE",
    "Arnau Martínez": "ELITE",
    "David López": "GOLD",
    "Alejandro Francés": "GOLD",
    "Álex Moreno": "GOLD",
    "Gibert Jordana": "SILVER",
    "Iván Martín": "ELITE",
    "Fran Beltrán": "GOLD",
    "A. Ounahi": "GOLD",
    "V. Tsygankov": "ELITE",
    "D. van de Beek": "GOLD",
    "Joel Roca": "SILVER",
    "Iván Morante": "SILVER",
    "L. Kourouma": "SILVER",
    "Ricard Artero": "BRONZE",
    "I. Gonzalez": "BRONZE",
    "C. Stuani": "GOLD",
    "Abel Ruiz": "GOLD",
    "Bryan Gil": "GOLD",
    "V. Vanat": "GOLD",
    "Oleksandr Pishchur": "SILVER",
    "P. Ba": "SILVER",
    "Juan Arango": "BRONZE"
  },
  "las-palmas": {
    "D. Horkaš": "GOLD",
    "José Caro": "SILVER",
    "Adrián Suárez": "BRONZE",
    "Ãlvaro Killane": "BRONZE",
    "Álex Suárez": "GOLD",
    "Enrique Clemente": "GOLD",
    "Cristian Gutiérrez": "GOLD",
    "Manu Fuster": "GOLD",
    "Marvin Park": "SILVER",
    "Juan Herzog": "SILVER",
    "V. Alegre": "BRONZE",
    "C. Navarro": "BRONZE",
    "Valentín Pezzolesi": "BRONZE",
    "A. Rodriguez": "SILVER",
    "Kirian Rodríguez": "GOLD",
    "Sergio Ruiz": "GOLD",
    "E. Loiodice": "SILVER",
    "Iñaki González Zambrano": "SILVER",
    "A. Bassinga": "SILVER",
    "Aimar Dominguez": "BRONZE",
    "Jesé": "GOLD",
    "Sandro Ramírez": "GOLD",
    "T. Miyashiro": "GOLD",
    "Jefté Betancor": "GOLD",
    "Ale García": "SILVER",
    "José Adam Arvelo López": "SILVER",
    "I. Medina": "SILVER",
    "Arturo Rodríguez": "BRONZE",
    "Elías Romero": "BRONZE",
    "Viti Rozada": "SILVER"
  },
  "leganes": {
    "Juan Soriano": "GOLD",
    "Raúl Fernández": "SILVER",
    "Ignasi Miquel": "GOLD",
    "Enric Franquesa": "GOLD",
    "Rubén Peña": "GOLD",
    "Rubén Pulido": "SILVER",
    "Álvaro Tejero": "SILVER",
    "S. Figueredo": "SILVER",
    "Lalo Aguilar": "SILVER",
    "Marvel": "SILVER",
    "D. Gueye": "SILVER",
    "B. Auguste": "BRONZE",
    "S. Fernandez": "BRONZE",
    "Samuel Bayon Almarza": "BRONZE",
    "L. Macazaga": "BRONZE",
    "S. Imigene": "BRONZE",
    "Dani Rodríguez": "GOLD",
    "Roberto López": "GOLD",
    "Ismaël Gharbi": "GOLD",
    "A. Diawara": "GOLD",
    "Y. Kechta": "GOLD",
    "Z. Buurmeester": "SILVER",
    "Miguel Atienza": "SILVER",
    "Javi Hernández": "SILVER",
    "Melero": "SILVER",
    "Carlos Guirao": "SILVER",
    "Modou Ndiaye": "SILVER",
    "J. Herrero": "BRONZE",
    "Nico Lozano": "BRONZE",
    "G. Rodriguez": "BRONZE",
    "M. Leiva": "BRONZE",
    "G. Siame": "BRONZE",
    "Andrés Campos": "GOLD",
    "Naim García": "SILVER",
    "A. Gøthler": "SILVER",
    "Álex Millán": "SILVER",
    "Carlos de Miguel": "BRONZE"
  },
  "mallorca": {
    "L. Bergström": "GOLD",
    "Rareș Vlad": "SILVER",
    "Raíllo": "ELITE",
    "Toni Lato": "GOLD",
    "Mateu Morey": "GOLD",
    "M. Valjent": "GOLD",
    "J. Mojica": "GOLD",
    "David López": "GOLD",
    "L. Orejuela": "SILVER",
    "J. Olaizola": "SILVER",
    "M. Calatayud": "BRONZE",
    "Leo Sánchez": "SILVER",
    "A. Souhmahoro": "SILVER",
    "I. Salhi": "SILVER",
    "Manu Morlanes": "ELITE",
    "Samú Costa": "ELITE",
    "Darder": "GOLD",
    "Antonio Sánchez": "GOLD",
    "Pablo Torre": "ELITE",
    "Arnau Puigmal": "SILVER",
    "C. Riba": "SILVER",
    "J. Garcia": "BRONZE",
    "Abdón Prats": "GOLD",
    "Jan Virgili": "GOLD",
    "J. Kalumba": "SILVER",
    "Fuentes": "SILVER"
  },
  "osasuna": {
    "Sergio Herrera": "GOLD",
    "Aitor Fernández": "GOLD",
    "Rafa": "SILVER",
    "D. Stamatakis": "BRONZE",
    "F. Boyomo": "GOLD",
    "Jorge Herrando": "GOLD",
    "Catena": "GOLD",
    "Abel Bretones": "SILVER",
    "V. Rosier": "SILVER",
    "U. Santos": "SILVER",
    "Moncayola": "ELITE",
    "Aimar Oroz": "ELITE",
    "Iker Muñoz": "GOLD",
    "Lucas Torró": "GOLD",
    "Mauro Echegoyen": "GOLD",
    "Asier Osambela": "SILVER",
    "A. Budimir": "ELITE",
    "Raúl García": "GOLD",
    "Rubén García": "GOLD",
    "Moi Gómez": "GOLD",
    "Kike Barja": "SILVER",
    "Raul Moro": "SILVER",
    "Íñigo Arguibide": "BRONZE",
    "Iker Benito": "BRONZE"
  },
  "rayo-vallecano": {
    "A. Batalla": "GOLD",
    "Dani Cárdenas": "SILVER",
    "Juanpe": "BRONZE",
    "Adrián Molina": "BRONZE",
    "A. Rațiu": "ELITE",
    "N. Mendy": "GOLD",
    "F. Lejeune": "GOLD",
    "I. Balliu": "GOLD",
    "Pep Chavarría": "GOLD",
    "Pelayo Fernández": "SILVER",
    "S. Lozano": "SILVER",
    "J. Vertrouwd": "SILVER",
    "Marco de las Sías": "BRONZE",
    "Isi Palazón": "ELITE",
    "Unai López": "GOLD",
    "P. Ciss": "GOLD",
    "Jorge de Frutos": "ELITE",
    "Fran Pérez": "GOLD",
    "Álvaro García": "GOLD",
    "Óscar Valentín": "GOLD",
    "Pedro Díaz": "SILVER",
    "Samu Becerra": "SILVER",
    "R. Nteka": "SILVER",
    "M. Roman": "SILVER",
    "Sergio Camello": "ELITE",
    "E. Eto'o": "GOLD",
    "Alemão": "SILVER"
  },
  "real-betis": {
    "Álvaro Vallés": "GOLD",
    "Diego Conde": "SILVER",
    "Marc Bartra": "GOLD",
    "Héctor Bellerín": "GOLD",
    "Diego Llorente": "GOLD",
    "Junior Firpo": "GOLD",
    "Natan": "GOLD",
    "Fran García": "GOLD",
    "V. Gómez": "SILVER",
    "Pablo Busto": "SILVER",
    "C. De Roa": "BRONZE",
    "Ángel Ortiz": "BRONZE",
    "Isco": "ELITE",
    "G. Lo Celso": "ELITE",
    "Álvaro Fidalgo": "ELITE",
    "Marc Roca": "GOLD",
    "Pablo Fornals": "GOLD",
    "N. Deossa": "GOLD",
    "F. Bernal": "SILVER",
    "Ivan Corralejo": "SILVER",
    "Antony": "ELITE",
    "A. Ezzalzouli": "GOLD",
    "Rodrigo Riquelme": "GOLD",
    "Aitor Ruibal": "GOLD",
    "G. Petit": "SILVER",
    "C. Hernández": "SILVER",
    "Iker Losada": "SILVER",
    "R. Marina": "SILVER",
    "J. A. Morante": "SILVER"
  },
  "real-madrid": {
    "T. Courtois": "ELITE_PLUS",
    "A. Lunin": "GOLD",
    "Fran González": "BRONZE",
    "Sergio Mestre": "BRONZE",
    "J. Navarro Jimenez": "BRONZE",
    "D. Huijsen": "ELITE_PLUS",
    "Éder Militão": "ELITE",
    "A. Rüdiger": "ELITE",
    "I. Konaté": "ELITE",
    "T. Alexander-Arnold": "ELITE_PLUS",
    "Marc Cucurella": "ELITE",
    "D. Dumfries": "ELITE",
    "Raúl Asencio": "GOLD",
    "F. Mendy": "GOLD",
    "Álvaro Fernández": "SILVER",
    "L. Fati": "SILVER",
    "Jesús Fortea": "SILVER",
    "David Jiménez": "BRONZE",
    "M. Serrano": "BRONZE",
    "Diego Aguado": "BRONZE",
    "J. Bellingham": "MASTER",
    "F. Valverde": "MASTER",
    "Bernardo Silva": "ELITE_PLUS",
    "E. Camavinga": "ELITE_PLUS",
    "A. Tchouaméni": "ELITE_PLUS",
    "A. Güler": "ELITE",
    "Brahim Díaz": "ELITE",
    "César Palacios": "SILVER",
    "Thiago Pitarch": "SILVER",
    "J. Cestero Sancho": "BRONZE",
    "Manuel Ángel": "BRONZE",
    "Kylian Mbappé": "MASTER",
    "Vinícius Júnior": "MASTER",
    "Rodrygo": "ELITE_PLUS",
    "Franco Mastantuono": "ELITE",
    "Gonzalo García": "GOLD",
    "Ávaro Leiva": "SILVER",
    "Daniel Yañez": "BRONZE",
    "J. Martinez": "SILVER"
  },
  "real-sociedad": {
    "Álex Remiro": "ELITE",
    "Unai Marrero": "SILVER",
    "Aitor Fraga": "BRONZE",
    "T. Folgado": "BRONZE",
    "Jon Pacheco": "ELITE",
    "Zubeldia": "GOLD",
    "Odriozola": "GOLD",
    "Aihen Muñoz": "GOLD",
    "J. Aramburu": "GOLD",
    "Javi López": "SILVER",
    "Jon Martín": "SILVER",
    "K. Kita": "SILVER",
    "J. Ochieng": "SILVER",
    "Rupérez": "BRONZE",
    "Luken Beitia": "BRONZE",
    "T. Kubo": "ELITE_PLUS",
    "L. Sučić": "ELITE",
    "Beñat Turrientes": "ELITE",
    "Carlos Soler": "GOLD",
    "Jon Gorrotxategi": "GOLD",
    "Y. Herrera": "GOLD",
    "A. Zakharyan": "GOLD",
    "Mikel Goti": "SILVER",
    "Pablo Marín": "SILVER",
    "Ibai Aguirre": "SILVER",
    "Lander Astiazarán": "SILVER",
    "Mikel Oyarzabal": "ELITE_PLUS",
    "Gonçalo Guedes": "GOLD",
    "O. Óskarsson": "GOLD",
    "Barrenetxea": "GOLD",
    "Jon Karrikaburu": "SILVER",
    "Dani Díaz": "SILVER",
    "Gorka Carrera": "SILVER",
    "Alex Garcia": "BRONZE",
    "Sergio Gómez": "GOLD"
  },
  "sevilla": {
    "O. Vlachodimos": "ELITE",
    "Alberto Flores": "SILVER",
    "Rafael Romero": "BRONZE",
    "José Ángel Carmona": "GOLD",
    "G. Suazo": "GOLD",
    "Adrià Pedrosa": "GOLD",
    "F. Gattoni": "GOLD",
    "Fábio Cardoso": "GOLD",
    "Juanlu Sánchez": "GOLD",
    "Kike Salas": "SILVER",
    "I. Munoz": "SILVER",
    "Andrés Castrín": "SILVER",
    "Oso": "BRONZE",
    "A. Sangante": "BRONZE",
    "L. Agoumé": "GOLD",
    "Jon Guridi": "GOLD",
    "Joan Jordán": "GOLD",
    "D. Sow": "GOLD",
    "Juan Iglesias": "SILVER",
    "R. Vargas": "SILVER",
    "Manu Bueno": "SILVER",
    "N. Guillen": "BRONZE",
    "Eduardo Altozano Agudo": "BRONZE",
    "P. Mercado": "BRONZE",
    "C. Ejuke": "GOLD",
    "Isaac": "GOLD",
    "M. Sierra": "SILVER",
    "Peque Fernández": "SILVER"
  },
  "valencia": {
    "S. Dimitrievski": "GOLD",
    "Cristian Rivero": "SILVER",
    "Vicent Abril": "BRONZE",
    "José Gayà": "ELITE",
    "M. Diakhaby": "GOLD",
    "César Tárrega": "GOLD",
    "D. Foulquier": "GOLD",
    "Copete": "GOLD",
    "J. de Haas": "SILVER",
    "Jesús Vázquez": "SILVER",
    "Iker Córdoba": "SILVER",
    "A. Panach": "SILVER",
    "Marcos Navarro": "BRONZE",
    "Aaron Mayol": "BRONZE",
    "Rubo Iranzo": "BRONZE",
    "Joel Fontanet": "BRONZE",
    "Javi Guerra": "ELITE",
    "Pepelu": "GOLD",
    "André Almeida": "GOLD",
    "G. Rodríguez": "GOLD",
    "A. Dieng": "SILVER",
    "F. Ugrinic": "SILVER",
    "R. Sato": "SILVER",
    "Hugo Duro": "GOLD",
    "A. Danjuma": "ELITE",
    "Luis Rioja": "GOLD",
    "U. Sadiq": "SILVER",
    "Dani Raba": "SILVER",
    "David Otorbi": "BRONZE",
    "Aimar Blázquez": "BRONZE"
  },
  "valladolid": {
    "Álvaro Aceves": "SILVER",
    "A. de Pablo": "BRONZE",
    "Marcos André": "GOLD",
    "Juanmi Latasa": "GOLD",
    "Ramón Martínez": "GOLD",
    "David Torres": "GOLD",
    "C. Michelin": "SILVER",
    "Iván Garriel": "SILVER",
    "M. Jaouab": "SILVER",
    "Alejandro Galdeano": "BRONZE",
    "Víctor Meseguer": "GOLD",
    "S. Jurić": "GOLD",
    "M. Lachuer": "SILVER",
    "Dani Pérez": "SILVER",
    "J. Ponceau": "SILVER",
    "Ricardo de Moraes": "SILVER",
    "T. Ojeda": "SILVER",
    "L. Sanseviero": "SILVER",
    "Pablo Tomeo": "BRONZE",
    "I. Alani": "BRONZE",
    "Iván Alejo": "GOLD",
    "A. Ndiaye": "GOLD",
    "K. de Rooij": "GOLD",
    "S. Biuk": "GOLD",
    "Victor Barberá": "SILVER",
    "Luis Chacón": "SILVER",
    "Víctor Fernández": "SILVER",
    "A. Carvajal": "SILVER",
    "R. Duiven": "SILVER",
    "Brain Chinedu": "BRONZE",
    "Hugo San": "BRONZE",
    "V. Erlien": "SILVER"
  },
  "villarreal": {
    "Rubén Gómez": "GOLD",
    "Luíz Júnior": "SILVER",
    "Y. Kinareykin": "BRONZE",
    "Renato Veiga": "ELITE",
    "Logan Costa": "GOLD",
    "Willy Kambwala Ndengushi": "GOLD",
    "Sergi Cardona": "GOLD",
    "Pau Navarro": "SILVER",
    "S. Mouriño": "SILVER",
    "Carlos Romero": "SILVER",
    "Daniel Budesca": "BRONZE",
    "A. Freeman": "BRONZE",
    "P. Gueye": "ELITE",
    "Santi Comesaña": "GOLD",
    "Alberto Moleiro": "ELITE",
    "A. Diatta": "GOLD",
    "T. Fernández": "SILVER",
    "C. Macia": "SILVER",
    "T. Buchanan": "GOLD",
    "G. Mikautadze": "ELITE",
    "Gerard Moreno": "ELITE",
    "Ayoze Pérez": "GOLD",
    "N. Pépé": "GOLD",
    "Álex Forés": "SILVER",
    "Hugo López": "SILVER",
    "T. Oluwaseyi": "SILVER",
    "Pau Cabanes": "SILVER"
  }
};

// 2. Verified Real-World Nationality Lookup
const NATION_MAP = {
  // Real Madrid
  "T. Courtois": "Belgium",
  "A. Lunin": "Ukraine",
  "D. Huijsen": "Spain",
  "Éder Militão": "Brazil",
  "A. Rüdiger": "Germany",
  "I. Konaté": "France",
  "T. Alexander-Arnold": "England",
  "D. Dumfries": "Netherlands",
  "F. Mendy": "France",
  "J. Bellingham": "England",
  "F. Valverde": "Uruguay",
  "Bernardo Silva": "Portugal",
  "E. Camavinga": "France",
  "A. Tchouaméni": "France",
  "A. Güler": "Turkey",
  "Brahim Díaz": "Morocco",
  "Kylian Mbappé": "France",
  "Vinícius Júnior": "Brazil",
  "Rodrygo": "Brazil",
  "Franco Mastantuono": "Argentina",

  // Barcelona
  "W. Szczęsny": "Poland",
  "J. Koundé": "France",
  "R. Araújo": "Uruguay",
  "A. Christensen": "Denmark",
  "F. de Jong": "Netherlands",
  "Raphinha": "Brazil",
  "R. Bardghji": "Sweden",
  "A. Gordon": "England",
  "K. Adeyemi": "Germany",

  // Atletico Madrid
  "J. Oblak": "Slovenia",
  "J. Musso": "Argentina",
  "J. Giménez": "Uruguay",
  "D. Hancko": "Slovakia",
  "N. Molina": "Argentina",
  "A. Puric": "Serbia",
  "G. Spina": "Argentina",
  "M. Hjulmand": "Denmark",
  "J. Cardoso": "USA",
  "Lee Kang-In": "South Korea",
  "T. Seidu": "Ghana",
  "J. Álvarez": "Argentina",
  "A. Sørloth": "Norway",
  "A. Lookman": "Nigeria",
  "T. Almada": "Argentina",
  "G. Simeone": "Argentina",

  // Athletic Club
  "Álex Padilla": "Mexico",
  "Aymeric Laporte": "Spain",
  "I. Williams": "Ghana",
  "Álvaro Djaló": "Guinea-Bissau",
  "Maroan Sannadi": "Morocco",

  // Alaves
  "Jesús Owono": "Equatorial Guinea",
  "G. Swiderski": "Poland",
  "M. Diarra": "Mali",
  "F. Garcés": "Argentina",
  "V. Koski": "Finland",
  "N. Tenaglia": "Argentina",
  "Yusi": "Morocco",
  "C. Benavídez": "Uruguay",
  "L. Boyé": "Argentina",
  "M. Díaz": "Dominican Republic",
  "A. Rebbach": "Algeria",

  // Celta Vigo
  "I. Radu": "Romania",
  "C. Starfelt": "Sweden",
  "M. Vecino": "Uruguay",
  "I. Moriba": "Guinea",
  "W. Swedberg": "Sweden",
  "B. Somuah": "Ghana",
  "J. El Abdellaoui": "Norway",

  // Espanyol
  "M. Dmitrović": "Serbia",
  "Q. Hartman": "Netherlands",
  "C. Riedel": "Germany",
  "Gabriel Moscardo": "Brazil",
  "T. Dolan": "Ireland",

  // Getafe
  "J. Letáček": "Czech Republic",
  "D. Dakonam": "Togo",
  "A. Abqar": "Morocco",
  "S. Boselli": "Uruguay",
  "M. Satriano": "Uruguay",

  // Girona
  "P. Gazzaniga": "Argentina",
  "A. Andreev": "Bulgaria",
  "V. Krapyvtsov": "Ukraine",
  "A. Ounahi": "Morocco",
  "V. Tsygankov": "Ukraine",
  "D. van de Beek": "Netherlands",
  "C. Stuani": "Uruguay",
  "V. Vanat": "Ukraine",
  "Oleksandr Pishchur": "Ukraine",

  // Las Palmas
  "D. Horkaš": "Slovakia",
  "Valentín Pezzolesi": "Argentina",
  "E. Loiodice": "France",
  "T. Miyashiro": "Peru",

  // Leganes
  "S. Figueredo": "Uruguay",
  "Marvel": "Brazil",
  "D. Gueye": "Senegal",
  "A. Diawara": "Guinea",
  "Y. Kechta": "Morocco",
  "Z. Buurmeester": "Netherlands",
  "Modou Ndiaye": "Senegal",
  "G. Siame": "Zambia",
  "A. Gøthler": "Denmark",

  // Mallorca
  "L. Bergström": "Sweden",
  "Rareș Vlad": "Romania",
  "M. Valjent": "Slovakia",
  "J. Mojica": "Colombia",
  "D. Stamatakis": "Greece",

  // Osasuna
  "F. Boyomo": "Cameroon",
  "V. Rosier": "France",
  "A. Budimir": "Croatia",

  // Rayo Vallecano
  "A. Batalla": "Argentina",
  "A. Rațiu": "Romania",
  "N. Mendy": "Senegal",
  "I. Balliu": "Albania",
  "J. Vertrouwd": "Netherlands",
  "P. Ciss": "Senegal",

  // Real Betis
  "Natan": "Brazil",
  "G. Lo Celso": "Argentina",
  "Álvaro Fidalgo": "Spain",
  "N. Deossa": "Colombia",
  "Antony": "Brazil",
  "A. Ezzalzouli": "Morocco",

  // Real Sociedad
  "K. Kita": "Japan",
  "J. Ochieng": "Kenya",
  "T. Kubo": "Japan",
  "L. Sučić": "Croatia",
  "Y. Herrera": "Venezuela",
  "A. Zakharyan": "Russia",
  "Gonçalo Guedes": "Portugal",
  "O. Óskarsson": "Iceland",

  // Sevilla
  "O. Vlachodimos": "Greece",
  "G. Suazo": "Chile",
  "F. Gattoni": "Argentina",
  "Fábio Cardoso": "Portugal",
  "L. Agoumé": "France",
  "D. Sow": "Switzerland",
  "R. Vargas": "Chile",
  "P. Mercado": "Argentina",
  "C. Ejuke": "Nigeria",

  // Valencia
  "S. Dimitrievski": "North Macedonia",
  "M. Diakhaby": "Guinea",
  "D. Foulquier": "Guadeloupe",
  "André Almeida": "Portugal",
  "F. Ugrinic": "Switzerland",
  "R. Sato": "Japan",
  "A. Danjuma": "Netherlands",
  "U. Sadiq": "Nigeria",

  // Valladolid
  "Marcos André": "Brazil",
  "S. Jurić": "Croatia",
  "J. Ponceau": "Uruguay",
  "T. Ojeda": "Paraguay",
  "L. Sanseviero": "Uruguay",
  "A. Ndiaye": "Senegal",
  "K. de Rooij": "Netherlands",
  "S. Biuk": "Croatia",
  "R. Duiven": "Netherlands",

  // Villarreal
  "Luíz Júnior": "Brazil",
  "Y. Kinareykin": "Russia",
  "Renato Veiga": "Portugal",
  "Logan Costa": "Cape Verde",
  "Willy Kambwala Ndengushi": "France",
  "S. Mouriño": "Uruguay",
  "P. Gueye": "Senegal",
  "A. Diatta": "Senegal",
  "T. Buchanan": "Canada",
  "G. Mikautadze": "Georgia",
  "N. Pépé": "Ivory Coast",
  "T. Oluwaseyi": "Canada"
};

// 3. Multi-Position Mappings
const MULTI_POSITIONS = {
  // Real Madrid
  "D. Huijsen": "CB/RB",
  "Éder Militão": "CB/RB",
  "A. Rüdiger": "CB",
  "I. Konaté": "CB",
  "T. Alexander-Arnold": "RB/RM",
  "Marc Cucurella": "LB/LM",
  "D. Dumfries": "RB/RM",
  "F. Mendy": "LB",
  "J. Bellingham": "CAM/CM",
  "F. Valverde": "CM/RW",
  "Bernardo Silva": "CAM/RW",
  "E. Camavinga": "CDM/CM",
  "A. Tchouaméni": "CDM/CB",
  "A. Güler": "CAM/RW",
  "Brahim Díaz": "CAM/RW",
  "Kylian Mbappé": "ST/LW",
  "Vinícius Júnior": "LW/ST",
  "Rodrygo": "RW/ST",
  "Franco Mastantuono": "CAM/RW",

  // Barcelona
  "Pau Cubarsí": "CB",
  "Pau Cubarsí Paredes": "CB",
  "J. Koundé": "RB/CB",
  "R. Araújo": "CB/RB",
  "Alejandro Balde": "LB/LM",
  "A. Christensen": "CB/CDM",
  "Eric García": "CB/RB",
  "Gerard Martín": "LB/CB",
  "Pedri": "CM/CAM",
  "F. de Jong": "CM/CDM",
  "Gavi": "CM/CAM",
  "Fermín": "CAM/CM",
  "Marc Casadó": "CDM/CM",
  "Marc Bernal": "CDM/CM",
  "Dani Olmo": "CAM/LW",
  "Lamine Yamal": "RW/ST",
  "Raphinha": "LW/RW",
  "Ferran Torres": "ST/LW",
  "R. Bardghji": "RW/CAM",
  "A. Gordon": "LW/RW",
  "K. Adeyemi": "LW/ST",

  // Atletico Madrid
  "J. Giménez": "CB",
  "Robin Le Normand": "CB",
  "Álex Grimaldo": "LB/LM",
  "D. Hancko": "CB/LB",
  "Marcos Llorente": "RB/CM",
  "N. Molina": "RB/RM",
  "Marc Pubill": "RB/CB",
  "Pablo Barrios": "CM/CDM",
  "M. Hjulmand": "CDM/CM",
  "Koke": "CM/CDM",
  "J. Cardoso": "CDM/CM",
  "Lee Kang-In": "CAM/RW",
  "J. Álvarez": "ST/LW",
  "Álex Baena": "CAM/LW",
  "A. Sørloth": "ST",
  "A. Lookman": "ST/LW",
  "T. Almada": "CAM/LW",
  "G. Simeone": "RW/RM",

  // Athletic Club
  "Dani Vivian": "CB",
  "Yeray": "CB",
  "Aymeric Laporte": "CB",
  "Yuri": "LB",
  "Jesús Areso": "RB",
  "Gorosabel": "RB",
  "Oihan Sancet": "CAM/ST",
  "Mikel Jauregizar": "CM/CDM",
  "Mikel Vesga": "CDM/CM",
  "Ruíz de Galarreta": "CM/CDM",
  "Beñat Prados": "CDM/CM",
  "Robert Navarro": "CAM/LW",
  "Nico Williams": "LW/RW",
  "I. Williams": "RW/ST",
  "Álex Berenguer": "LW/RW",
  "Gorka Guruzeta": "ST",
  "Álvaro Djaló": "LW/ST",
  "Nico Serrano": "LW/RW",

  // Villarreal
  "Renato Veiga": "CB/CDM",
  "Logan Costa": "CB",
  "Willy Kambwala Ndengushi": "CB",
  "Sergi Cardona": "LB/CB",
  "P. Gueye": "CDM/CM",
  "Santi Comesaña": "CM/CDM",
  "Alberto Moleiro": "CAM/CM",
  "A. Diatta": "RM/RW",
  "T. Buchanan": "RM/RB",
  "G. Mikautadze": "ST",
  "Gerard Moreno": "ST/RW",
  "Ayoze Pérez": "ST/LW",
  "N. Pépé": "RW/ST",

  // Real Betis
  "Marc Bartra": "CB",
  "Héctor Bellerín": "RB",
  "Diego Llorente": "CB",
  "Junior Firpo": "LB",
  "Natan": "CB",
  "Isco": "CAM/CM",
  "G. Lo Celso": "CAM/CM",
  "Álvaro Fidalgo": "CM/CAM",
  "Marc Roca": "CDM/CM",
  "Pablo Fornals": "CAM/RM",
  "N. Deossa": "CM/CAM",
  "Antony": "RW",
  "A. Ezzalzouli": "LW/RW",
  "Rodrigo Riquelme": "LW/CAM",
  "Aitor Ruibal": "RB/RW",

  // Real Sociedad
  "Jon Pacheco": "CB",
  "Zubeldia": "CB/RB",
  "Aihen Muñoz": "LB",
  "J. Aramburu": "RB/CB",
  "T. Kubo": "RW/CAM",
  "L. Sučić": "CM/CAM",
  "Beñat Turrientes": "CM/CDM",
  "Y. Herrera": "CM/CDM",
  "A. Zakharyan": "CAM/CM",
  "Mikel Oyarzabal": "LW/ST",
  "Gonçalo Guedes": "LW/ST",
  "Barrenetxea": "LW/RW"
};

function normalize(str) {
  return str ? str.replace(/&apos;/g, "'").toLowerCase().replace(/['’\-]/g, '').replace(/[^a-z0-9]/g, '') : '';
}

const dir = path.join(__dirname, '..', 'data', 'players', 'active', 'la-liga');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));

let totalPlayersProcessed = 0;
let tierUpdatedCount = 0;
let nationUpdatedCount = 0;
let positionUpdatedCount = 0;

files.forEach(file => {
  const filePath = path.join(dir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const clubKey = file.replace('.json', '');
  const tiersForClub = TEAM_TIERS[clubKey] || {};

  // Build normalized lookup for tiers
  const normTiers = {};
  Object.keys(tiersForClub).forEach(k => {
    normTiers[normalize(k)] = tiersForClub[k];
  });

  data.players.forEach(player => {
    totalPlayersProcessed++;

    // 1. Tier assignment
    const pNorm = normalize(player.name);
    let assignedTier = normTiers[pNorm];

    if (!assignedTier) {
      // Try matching by last name
      const parts = player.name.split(' ');
      const lastName = normalize(parts[parts.length - 1]);
      const matchKey = Object.keys(normTiers).find(k => k === lastName || k.endsWith(lastName) || lastName.endsWith(k));
      if (matchKey) {
        assignedTier = normTiers[matchKey];
      }
    }

    // Fallback if missing in prompt list
    if (!assignedTier) {
      if (player.kitNumber && player.kitNumber > 30) {
        assignedTier = "BRONZE";
      } else if (player.kitNumber && player.kitNumber > 20) {
        assignedTier = "SILVER";
      } else {
        assignedTier = "GOLD";
      }
    }

    if (player.tier !== assignedTier) {
      player.tier = assignedTier;
      tierUpdatedCount++;
    }

    // 2. Nation correction
    const exactNation = NATION_MAP[player.name];
    if (exactNation && player.nation !== exactNation) {
      player.nation = exactNation;
      nationUpdatedCount++;
    } else if (!exactNation) {
      // Check partial match in NATION_MAP
      const foundNationKey = Object.keys(NATION_MAP).find(k => normalize(k) === pNorm);
      if (foundNationKey && player.nation !== NATION_MAP[foundNationKey]) {
        player.nation = NATION_MAP[foundNationKey];
        nationUpdatedCount++;
      }
    }

    // 3. Multi-position update
    const multiPos = MULTI_POSITIONS[player.name];
    if (multiPos && player.position !== multiPos) {
      player.position = multiPos;
      positionUpdatedCount++;
    }
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Updated ${data.club.name} (${file}): ${data.players.length} players processed.`);
});

console.log(`\n🎉 La Liga Update Complete!`);
console.log(`   Total Players Processed: ${totalPlayersProcessed}`);
console.log(`   Tiers Updated: ${tierUpdatedCount}`);
console.log(`   Nations Corrected: ${nationUpdatedCount}`);
console.log(`   Multi-Positions Updated: ${positionUpdatedCount}`);
