import fs from 'fs';
import path from 'path';

// Master tier mapping extracted from User Tier List (2025/26 - v2)
const TIER_MAPPINGS = {
  "Arsenal": {
    "David Raya": "ELITE_PLUS",
    "Kepa": "GOLD",
    "I. Meslier": "SILVER",
    "J. Porter": "BRONZE",
    "K. Ranson": "BRONZE",
    "T. Setford": "BRONZE",
    "W. Saliba": "MASTER",
    "Gabriel Magalhães": "ELITE_PLUS",
    "J. Timber": "ELITE_PLUS",
    "B. White": "ELITE",
    "R. Calafiori": "ELITE",
    "P. Hincapié": "ELITE",
    "Cristhian Mosquera": "GOLD",
    "M. Lewis-Skelly": "ELITE",
    "Jaden Dixon": "BRONZE",
    "M. Salmon": "BRONZE",
    "D. Rice": "MASTER",
    "Martín Zubimendi": "ELITE_PLUS",
    "M. Ødegaard": "ELITE_PLUS",
    "Mikel Merino": "ELITE",
    "C. Nørgaard": "GOLD",
    "E. Eze": "ELITE_PLUS",
    "I. Ibrahim": "SILVER",
    "M. Dowman": "SILVER",
    "B. Saka": "MASTER",
    "Gabriel Martinelli": "ELITE",
    "N. Madueke": "ELITE",
    "V. Gyökeres": "ELITE_PLUS",
    "Gabriel Jesus": "ELITE",
    "K. Havertz": "ELITE_PLUS",
    "C. Tzolis": "GOLD",
    "B. Bailey-Joseph": "SILVER",
    "A. Annous": "BRONZE"
  },
  "Aston Villa": {
    "E. Martínez": "ELITE_PLUS",
    "M. Bizot": "GOLD",
    "J. Gauci": "SILVER",
    "J. Wright": "BRONZE",
    "T. Mings": "GOLD",
    "E. Konsa": "ELITE",
    "Pau Torres": "ELITE",
    "V. Lindelöf": "GOLD",
    "L. Digne": "GOLD",
    "M. Cash": "ELITE",
    "I. Maatsen": "ELITE",
    "K. Nedeljković": "SILVER",
    "L. Bogarde": "GOLD",
    "M. Cissé": "SILVER",
    "T. Rowe": "BRONZE",
    "J. McGinn": "ELITE",
    "A. Onana": "ELITE",
    "João Gomes": "ELITE_PLUS",
    "R. Barkley": "GOLD",
    "E. Buendía": "GOLD",
    "Aidan Borland": "BRONZE",
    "B. Broggio": "SILVER",
    "B. Burrows": "BRONZE",
    "T. Carroll": "SILVER",
    "R. Fortes": "BRONZE",
    "George Hemmings": "BRONZE",
    "J. Jimoh": "BRONZE",
    "J. Manzambi": "SILVER",
    "O. Watkins": "ELITE_PLUS",
    "T. Abraham": "GOLD",
    "L. Bailey": "SILVER",
    "A. Garnacho": "ELITE",
    "S. Iling-Junior": "GOLD",
    "Alysson Edward": "BRONZE",
    "Brian Madjo": "BRONZE",
    "T. Mulley": "BRONZE"
  },
  "Bournemouth": {
    "Đ. Petrović": "ELITE",
    "F. Forster": "SILVER",
    "J. Hill": "GOLD",
    "A. Smith": "GOLD",
    "B. Diakité": "GOLD",
    "A. Truffert": "ELITE",
    "Veljko Milosavljević": "SILVER",
    "T. Adams": "ELITE",
    "R. Christie": "GOLD",
    "L. Cook": "GOLD",
    "M. Tavernier": "GOLD",
    "A. Adli": "GOLD",
    "A. Scott": "GOLD",
    "A. Tóth": "SILVER",
    "Malcom Dacosta": "BRONZE",
    "C. Stevens": "BRONZE",
    "Evanilson": "ELITE",
    "D. Brooks": "GOLD",
    "B. Doak": "ELITE",
    "J. Kluivert": "ELITE",
    "Á. Rodríguez": "GOLD",
    "E. Ünal": "SILVER",
    "E. Kroupi": "GOLD",
    "Rayan": "SILVER",
    "Remy Rees-Dottin": "BRONZE"
  },
  "Brentford": {
    "C. Kelleher": "ELITE",
    "H. Valdimarsson": "GOLD",
    "E. Balcombe": "SILVER",
    "N. Collins": "ELITE",
    "K. Ajer": "GOLD",
    "E. Pinnock": "GOLD",
    "S. van den Berg": "GOLD",
    "R. Henry": "SILVER",
    "A. Hickey": "SILVER",
    "M. Kayode": "SILVER",
    "J. Stephenson": "BRONZE",
    "M. Damsgaard": "ELITE",
    "V. Janelt": "GOLD",
    "M. Jensen": "GOLD",
    "K. Lewis-Potter": "ELITE",
    "Y. Yarmolyuk": "GOLD",
    "J. Henderson": "SILVER",
    "J. Dasilva": "SILVER",
    "Luka Bentt": "BRONZE",
    "Jannik Schuster": "SILVER",
    "R. Owen": "BRONZE",
    "K. Schade": "ELITE_PLUS",
    "D. Ouattara": "GOLD",
    "Thiago": "GOLD",
    "C. Wilson": "GOLD",
    "J. Anthony": "SILVER",
    "Kaye Iyowuna Furo": "BRONZE",
    "O. Shield": "BRONZE"
  },
  "Brighton": {
    "B. Verbruggen": "ELITE",
    "J. Steele": "SILVER",
    "L. Vušković": "ELITE",
    "Igor": "GOLD",
    "P. Struijk": "GOLD",
    "M. De Cuyper": "GOLD",
    "F. Kadıoğlu": "GOLD",
    "O. Boscagli": "SILVER",
    "Costinha": "SILVER",
    "M. Svoboda": "SILVER",
    "C. Baleba": "ELITE_PLUS",
    "M. Wieffer": "ELITE",
    "P. Groß": "GOLD",
    "D. Gómez": "GOLD",
    "J. Hinshelwood": "ELITE",
    "M. O'Riley": "ELITE",
    "Y. Ayari": "SILVER",
    "H. Howell": "BRONZE",
    "K. Mitoma": "ELITE_PLUS",
    "Y. Minteh": "ELITE",
    "D. Welbeck": "GOLD",
    "G. Rutter": "ELITE",
    "C. Kostoulas": "GOLD",
    "Z. Yohanna": "BRONZE"
  },
  "Chelsea": {
    "Robert Sánchez": "ELITE",
    "F. Jörgensen": "GOLD",
    "G. Słonina": "SILVER",
    "T. Sharman-Lowe": "BRONZE",
    "Max Merrick": "BRONZE",
    "L. Colwill": "ELITE_PLUS",
    "W. Fofana": "ELITE",
    "T. Chalobah": "GOLD",
    "T. Adarabioyo": "GOLD",
    "B. Badiashile": "GOLD",
    "R. James": "ELITE_PLUS",
    "M. Gusto": "ELITE",
    "J. Hato": "GOLD",
    "Joshua Kofi Acheampong": "GOLD",
    "M. Sarr": "SILVER",
    "M. Palestra": "BRONZE",
    "Denner": "BRONZE",
    "M. Caicedo": "MASTER",
    "E. Fernández": "ELITE_PLUS",
    "R. Lavia": "ELITE",
    "Dário Essugo": "GOLD",
    "Harrison Bettoni": "BRONZE",
    "M. Eboue": "BRONZE",
    "R. Kavuma McQueen": "BRONZE",
    "C. Holland": "BRONZE",
    "C. Palmer": "MASTER",
    "M. Rogers": "ELITE",
    "Pedro Neto": "ELITE_PLUS",
    "João Pedro": "ELITE_PLUS",
    "Estêvão": "ELITE_PLUS",
    "Geovany Tcherno Quenda": "ELITE",
    "J. Bynoe-Gittens": "ELITE",
    "L. Delap": "ELITE",
    "E. Emegha": "GOLD",
    "Marc Guiu": "SILVER",
    "Shumaira Mheuka": "BRONZE"
  },
  "Crystal Palace": {
    "D. Henderson": "ELITE",
    "W. Benítez": "SILVER",
    "R. Matthews": "SILVER",
    "J. Whitworth": "BRONZE",
    "M. Lacroix": "ELITE",
    "Óscar Mingueza": "GOLD",
    "N. Clyne": "SILVER",
    "C. Richards": "GOLD",
    "B. Sosa": "GOLD",
    "D. Muñoz": "ELITE_PLUS",
    "T. Mitchell": "GOLD",
    "C. Riad": "SILVER",
    "T. Adaramola": "BRONZE",
    "D. Benamar": "BRONZE",
    "J. Canvot": "SILVER",
    "Rio Cardines": "BRONZE",
    "Daniel Edward Peter Imray": "BRONZE",
    "M. Jemide": "BRONZE",
    "G. King": "BRONZE",
    "A. Wharton": "ELITE_PLUS",
    "C. Doucouré": "GOLD",
    "W. Hughes": "GOLD",
    "J. Lerma": "GOLD",
    "D. Kamada": "GOLD",
    "Matheus França": "ELITE",
    "J. Rak-Sakyi": "GOLD",
    "J. Devenny": "BRONZE",
    "J. Drakes-Thomas": "BRONZE",
    "R. Esse": "SILVER",
    "D. Ozoh": "BRONZE",
    "J. Strand Larsen": "ELITE",
    "J. Mateta": "ELITE_PLUS",
    "E. Nketiah": "GOLD",
    "Yeremy Pino": "ELITE",
    "I. Sarr": "ELITE",
    "B. Johnson": "SILVER",
    "Z. Marsh": "BRONZE"
  },
  "Everton": {
    "J. Pickford": "ELITE_PLUS",
    "M. Travers": "SILVER",
    "T. King": "BRONZE",
    "J. Tarkowski": "GOLD",
    "J. Branthwaite": "ELITE",
    "V. Mykolenko": "GOLD",
    "N. Patterson": "SILVER",
    "J. O'Brien": "SILVER",
    "Adam Aznou Ben Cheikh": "GOLD",
    "Elijah Xavier Campbell": "BRONZE",
    "G. Finney": "BRONZE",
    "W. Tamen": "BRONZE",
    "C. Alcaraz": "ELITE",
    "K. Dewsbury-Hall": "ELITE",
    "I. Ndiaye": "ELITE_PLUS",
    "J. Garner": "SILVER",
    "H. Hackney": "GOLD",
    "T. Iroegbunam": "GOLD",
    "H. Armstrong": "SILVER",
    "H. Foster": "BRONZE",
    "Malik Olayiwola": "BRONZE",
    "M. Röhl": "GOLD",
    "D. McNeil": "GOLD",
    "Beto": "GOLD",
    "Tyrique George": "ELITE",
    "T. Barry": "GOLD",
    "T. Dibling": "ELITE",
    "B. Graham": "BRONZE"
  },
  "Fulham": {
    "B. Leno": "ELITE_PLUS",
    "B. Lecomte": "SILVER",
    "J. Andersen": "ELITE",
    "C. Bassey": "GOLD",
    "K. Tete": "GOLD",
    "T. Castagne": "GOLD",
    "I. Diop": "SILVER",
    "Jorge Cuenca": "SILVER",
    "A. Robinson": "GOLD",
    "S. Amissah": "BRONZE",
    "A. Iwobi": "ELITE_PLUS",
    "T. Cairney": "GOLD",
    "S. Berge": "GOLD",
    "S. Lukić": "GOLD",
    "H. Reed": "GOLD",
    "R. Sessegnon": "GOLD",
    "Oscar Bobb": "ELITE",
    "Joshua King": "BRONZE",
    "E. Smith Rowe": "ELITE",
    "Rodrigo Muniz": "ELITE",
    "Kevin": "GOLD",
    "J. Kusi-Asare": "BRONZE"
  },
  "Ipswich": {
    "A. Palmer": "GOLD",
    "D. Button": "SILVER",
    "C. Walton": "SILVER",
    "K. van Oevelen": "BRONZE",
    "D. O'Shea": "ELITE",
    "C. Kipré": "GOLD",
    "L. Davis": "GOLD",
    "I. Diop": "SILVER",
    "D. Furlong": "SILVER",
    "J. Greaves": "SILVER",
    "S. Boniface": "BRONZE",
    "J. Taylor": "GOLD",
    "A. Matusiwa": "GOLD",
    "W. Burns": "SILVER",
    "M. Núñez": "SILVER",
    "A. Fatawu": "ELITE",
    "G. Hirst": "GOLD",
    "J. Philogene": "ELITE",
    "C. Akpom": "GOLD",
    "J. Clarke": "SILVER",
    "D. Maeda": "SILVER",
    "A. Mehmeti": "SILVER",
    "K. McAteer": "GOLD",
    "S. Egeli": "SILVER",
    "Emersonn": "BRONZE",
    "B. Johnson": "BRONZE"
  },
  "Leicester": {
    "A. Begović": "GOLD",
    "J. Stolarczyk": "SILVER",
    "Fran Vieites": "SILVER",
    "Harry French": "BRONZE",
    "W. Faes": "ELITE",
    "H. Souttar": "GOLD",
    "V. Kristiansen": "GOLD",
    "C. Okoli": "SILVER",
    "W. Coulibaly": "SILVER",
    "B. Nelson": "SILVER",
    "O. Aluko": "BRONZE",
    "K. Gray": "BRONZE",
    "L. Page": "BRONZE",
    "L. Thomas": "BRONZE",
    "T. Wilson-Brown": "BRONZE",
    "O. Skipp": "ELITE",
    "H. Choudhury": "GOLD",
    "B. De Cordova-Reid": "GOLD",
    "S. Braybrooke": "GOLD",
    "W. Alves": "BRONZE",
    "S. Mavididi": "ELITE",
    "A. Fatawu": "ELITE",
    "J. Evans": "SILVER",
    "Silko Amari Otieno Thomas": "BRONZE"
  },
  "Liverpool": {
    "Alisson Becker": "ELITE_PLUS",
    "G. Mamardashvili": "ELITE",
    "F. Woodman": "SILVER",
    "H. Davies": "BRONZE",
    "K. Miściur": "BRONZE",
    "V. van Dijk": "MASTER",
    "J. Gomez": "GOLD",
    "M. Kerkez": "ELITE",
    "K. Tsimikas": "GOLD",
    "L. Chambers": "SILVER",
    "J. Jacquet": "SILVER",
    "C. Ramsay": "SILVER",
    "T. Ndiaye": "BRONZE",
    "C. Scanlon": "BRONZE",
    "A. Mac Allister": "MASTER",
    "D. Szoboszlai": "ELITE_PLUS",
    "R. Gravenberch": "ELITE_PLUS",
    "F. Wirtz": "MASTER",
    "J. Frimpong": "ELITE",
    "W. Endo": "GOLD",
    "C. Jones": "GOLD",
    "H. Elliott": "ELITE",
    "T. Nyoni": "GOLD",
    "K. Morrison": "SILVER",
    "J. McConnell": "BRONZE",
    "A. Isak": "MASTER",
    "H. Ekitike": "ELITE_PLUS",
    "C. Gakpo": "ELITE",
    "F. Chiesa": "GOLD",
    "R. Ngumoha": "ELITE",
    "L. Koumas": "GOLD",
    "Víctor Muñoz": "SILVER",
    "Joshua Abe": "BRONZE",
    "W. Wright": "BRONZE"
  },
  "Manchester City": {
    "G. Donnarumma": "MASTER",
    "J. Trafford": "GOLD",
    "M. Bettinelli": "SILVER",
    "Rúben Dias": "ELITE_PLUS",
    "J. Gvardiol": "ELITE_PLUS",
    "M. Guéhi": "ELITE",
    "R. Aït-Nouri": "ELITE",
    "A. Khusanov": "GOLD",
    "R. Lewis": "GOLD",
    "Max Alleyne": "BRONZE",
    "S. Mfuni": "BRONZE",
    "Rodri": "MASTER",
    "M. Kovačić": "GOLD",
    "Nico González": "ELITE",
    "Matheus Nunes": "GOLD",
    "T. Reijnders": "ELITE_PLUS",
    "N. O'Reilly": "GOLD",
    "Charlie Gray": "BRONZE",
    "R. McAidoo": "BRONZE",
    "P. Foden": "MASTER",
    "R. Cherki": "ELITE",
    "E. Anderson": "GOLD",
    "E. Haaland": "MASTER",
    "Omar Marmoush": "ELITE",
    "J. Doku": "ELITE_PLUS",
    "Sávio": "ELITE",
    "A. Semenyo": "ELITE",
    "D. Mukasa": "GOLD",
    "J. Monga": "BRONZE"
  },
  "Manchester United": {
    "A. Bayındır": "GOLD",
    "K. Darlow": "SILVER",
    "S. Lammens": "SILVER",
    "Lisandro Martínez": "ELITE",
    "H. Maguire": "ELITE",
    "L. Yoro": "ELITE_PLUS",
    "N. Mazraoui": "GOLD",
    "Diogo Dalot": "ELITE",
    "L. Shaw": "GOLD",
    "P. Dorgu": "GOLD",
    "T. Fredricson": "BRONZE",
    "A. Heaven": "SILVER",
    "G. Kukonki": "BRONZE",
    "Bruno Fernandes": "MASTER",
    "K. Mainoo": "ELITE",
    "M. Ugarte": "GOLD",
    "Y. Tielemans": "GOLD",
    "M. Mount": "GOLD",
    "Andrey Santos": "ELITE",
    "J. Fletcher": "SILVER",
    "T. Fletcher": "BRONZE",
    "J. Moorhouse": "BRONZE",
    "Matheus Cunha": "ELITE_PLUS",
    "B. Mbeumo": "ELITE_PLUS",
    "B. Šeško": "ELITE",
    "J. Zirkzee": "GOLD",
    "A. Diallo": "ELITE",
    "S. Lacey": "BRONZE"
  },
  "Newcastle": {
    "N. Pope": "ELITE_PLUS",
    "A. Ramsdale": "GOLD",
    "E. Jaouen": "SILVER",
    "Aidan Harris": "BRONZE",
    "Max Thompson": "BRONZE",
    "S. Botman": "ELITE",
    "M. Thiaw": "ELITE",
    "D. Burn": "GOLD",
    "T. Livramento": "ELITE_PLUS",
    "L. Hall": "GOLD",
    "A. Murphy": "SILVER",
    "L. Shahar": "BRONZE",
    "Bruno Guimarães": "MASTER",
    "Joelinton": "ELITE",
    "J. Willock": "GOLD",
    "J. Murphy": "GOLD",
    "J. Ramsey": "GOLD",
    "B. Touré": "SILVER",
    "Sean Steur": "SILVER",
    "Park Seung-Soo": "SILVER",
    "S. Neave": "BRONZE",
    "L. Miley": "BRONZE",
    "N. Woltemade": "ELITE_PLUS",
    "Y. Wissa": "ELITE",
    "A. Elanga": "ELITE",
    "H. Barnes": "GOLD",
    "W. Osula": "SILVER"
  },
  "Nottingham Forest": {
    "M. Sels": "ELITE",
    "John": "SILVER",
    "Keehan Willows": "BRONZE",
    "Murillo": "ELITE_PLUS",
    "N. Milenković": "ELITE",
    "O. Aina": "GOLD",
    "Morato": "GOLD",
    "O. Richards": "GOLD",
    "N. Williams": "SILVER",
    "Jair": "SILVER",
    "L. Netz": "SILVER",
    "Z. Abbott": "BRONZE",
    "B. Hammond": "BRONZE",
    "Justin Thomas Hanks": "BRONZE",
    "J. Sinclair": "BRONZE",
    "Jack Ethan Thompson": "BRONZE",
    "M. Gibbs-White": "ELITE_PLUS",
    "I. Sangaré": "GOLD",
    "N. Domínguez": "GOLD",
    "C. Hudson-Odoi": "GOLD",
    "X. Schlager": "GOLD",
    "J. McAtee": "ELITE",
    "R. Yates": "GOLD",
    "Eric Emanuel da Silva Moreira": "SILVER",
    "A. Whitehall": "BRONZE",
    "G. McDonnell": "BRONZE",
    "Igor Jesus": "ELITE",
    "C. Wood": "GOLD",
    "A. Kalimuendo": "ELITE",
    "D. Ndoye": "ELITE",
    "T. Awoniyi": "GOLD",
    "D. Bakwa": "GOLD",
    "O. Hutchinson": "GOLD",
    "L. Sillah": "BRONZE",
    "Z. Blake": "BRONZE"
  },
  "Southampton": {
    "G. Long": "SILVER",
    "Daniel Peretz": "SILVER",
    "T. Harwood-Bellis": "ELITE",
    "J. Stephens": "GOLD",
    "J. Bree": "GOLD",
    "R. Manning": "SILVER",
    "Welington": "SILVER",
    "J. Quarshie": "SILVER",
    "N. Wood-Gordon": "BRONZE",
    "T. Dobson-Ventura": "BRONZE",
    "F. Downes": "GOLD",
    "M. Sesay": "GOLD",
    "F. Azaz": "GOLD",
    "K. Matsuki": "SILVER",
    "C. Jander": "SILVER",
    "T. Fellows": "GOLD",
    "S. Charles": "SILVER",
    "B. Williams": "BRONZE",
    "Cameron Bragg": "BRONZE",
    "J. O'Brien-Whitmarsh": "BRONZE",
    "C. Archer": "ELITE",
    "C. Larin": "GOLD",
    "S. Edozie": "GOLD",
    "Léo Scienza": "SILVER",
    "Jay Robinson": "BRONZE",
    "N. Oyekunle": "BRONZE"
  },
  "Tottenham": {
    "G. Vicario": "ELITE_PLUS",
    "A. Kinský": "GOLD",
    "M. Dúbravka": "SILVER",
    "B. Austin": "BRONZE",
    "C. Romero": "ELITE_PLUS",
    "M. van de Ven": "ELITE_PLUS",
    "K. Danso": "GOLD",
    "Pedro Porro": "ELITE",
    "A. Robertson": "ELITE",
    "D. Udogie": "ELITE",
    "J. van Hecke": "GOLD",
    "M. Senesi": "GOLD",
    "B. Davies": "SILVER",
    "Souza": "SILVER",
    "D. Spence": "SILVER",
    "K. Takai": "BRONZE",
    "A. Gray": "SILVER",
    "James Rowswell": "BRONZE",
    "J. Byfield": "BRONZE",
    "M. Hardy": "BRONZE",
    "R. Bentancur": "ELITE",
    "J. Maddison": "ELITE_PLUS",
    "P. Sarr": "ELITE_PLUS",
    "L. Bergvall": "ELITE_PLUS",
    "S. Tonali": "ELITE_PLUS",
    "X. Simons": "ELITE",
    "Mateus Fernandes": "GOLD",
    "C. Gallagher": "GOLD",
    "D. Ajayi": "SILVER",
    "T. Hall": "SILVER",
    "Rio Kyerematen": "BRONZE",
    "C. Olusesi": "BRONZE",
    "D. Solanke": "ELITE",
    "Richarlison": "ELITE",
    "W. Odobert": "ELITE",
    "M. Tel": "GOLD",
    "M. Solomon": "SILVER",
    "D. Scarlett": "SILVER",
    "J. Donley": "BRONZE",
    "M. Moore": "BRONZE",
    "L. Williams-Barnett": "BRONZE",
    "Yang Min-Hyeok": "BRONZE"
  },
  "West Ham": {
    "A. Areola": "GOLD",
    "M. Hermansen": "GOLD",
    "F. Herrick": "BRONZE",
    "M. Kilman": "GOLD",
    "J. Todibo": "ELITE",
    "K. Mavropanos": "GOLD",
    "K. Walker-Peters": "GOLD",
    "A. Wan-Bissaka": "GOLD",
    "E. Diouf": "SILVER",
    "O. Scarles": "SILVER",
    "Junior Robinson": "BRONZE",
    "A. Golambeckis": "BRONZE",
    "K. Casey": "BRONZE",
    "E. Mayers": "BRONZE",
    "R. Battrum": "BRONZE",
    "T. Souček": "ELITE",
    "J. Ward-Prowse": "ELITE",
    "M. Kanté": "SILVER",
    "S. Magassa": "SILVER",
    "F. Potts": "GOLD",
    "George Earthy": "SILVER",
    "P. Fearon": "BRONZE",
    "K. Lamadrid": "BRONZE",
    "L. Orford": "BRONZE",
    "J. Bowen": "ELITE_PLUS",
    "V. Castellanos": "GOLD",
    "M. Cornet": "GOLD",
    "Pablo": "SILVER",
    "C. Marshall": "BRONZE"
  },
  "Wolves": {
    "José Sá": "GOLD",
    "S. Johnstone": "SILVER",
    "D. Bentley": "BRONZE",
    "J. Gracey": "BRONZE",
    "K. Trippier": "GOLD",
    "Toti Gomes": "GOLD",
    "S. Bueno": "GOLD",
    "Hugo Bueno": "GOLD",
    "Rodrigo Gomes": "GOLD",
    "L. Krejčí": "SILVER",
    "D. Møller Wolfe": "SILVER",
    "Pedro Lima": "BRONZE",
    "S. Olagunju": "BRONZE",
    "João Gomes": "ELITE",
    "André": "GOLD",
    "Fer López": "ELITE",
    "Y. Mosquera": "GOLD",
    "J. Bellegarde": "GOLD",
    "L. Rawlings": "SILVER",
    "T. Edozie": "BRONZE",
    "Hwang Hee-Chan": "ELITE",
    "R. Jiménez": "GOLD",
    "T. Arokodare": "GOLD",
    "A. Armstrong": "SILVER",
    "M. Mane": "SILVER",
    "R. Saïd": "SILVER",
    "J. Tchatchoua": "BRONZE",
    "Ethan Sutherland": "BRONZE"
  }
};

function normalize(str) {
  return str.replace(/&apos;/g, "'").toLowerCase().replace(/['’\-]/g, '').replace(/[^a-z0-9]/g, '');
}

const dir = path.join(process.cwd(), 'data', 'players', 'active', 'premier-league');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));

let totalAssigned = 0;
let totalPlayers = 0;
let unmappedPlayers = [];

for (const file of files) {
  const filePath = path.join(dir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const clubName = data.club.name;
  const mappings = TIER_MAPPINGS[clubName] || {};

  // Build normalized lookup
  const normMap = {};
  for (const [name, tier] of Object.entries(mappings)) {
    normMap[normalize(name)] = tier;
  }

  for (const player of data.players) {
    totalPlayers++;
    const playerNorm = normalize(player.name);
    
    let tier = normMap[playerNorm];

    // Try last name match if exact fails
    if (!tier) {
      const parts = player.name.split(' ');
      const lastName = normalize(parts[parts.length - 1]);
      for (const [k, v] of Object.entries(normMap)) {
        if (k.endsWith(lastName) || k === lastName) {
          tier = v;
          break;
        }
      }
    }

    // Default fallback based on kit number or prospect status
    if (!tier) {
      if (player.kitNumber && player.kitNumber > 40) {
        tier = "BRONZE";
      } else if (player.kitNumber && player.kitNumber > 25) {
        tier = "SILVER";
      } else {
        tier = "GOLD";
      }
      unmappedPlayers.push(`${clubName}: ${player.name} (#${player.kitNumber}) -> fallback to ${tier}`);
    }

    player.tier = tier;
    totalAssigned++;
  }

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Updated ${clubName}: ${data.players.length} players tier-assigned.`);
}

console.log(`\nSuccessfully assigned tiers for ${totalAssigned} / ${totalPlayers} Premier League players.`);
if (unmappedPlayers.length > 0) {
  console.log(`\nFallbacks applied (${unmappedPlayers.length}):`);
  console.log(unmappedPlayers.join('\n'));
}
