const fs = require('fs');
const path = require('path');

// Prompt Tier Mappings per Club
const PROMPT_TIERS = {
  "Alaves": {
    "Sivera": "GOLD",
    "Jesús Owono": "GOLD",
    "R. Montero": "SILVER",
    "G. Swiderski": "SILVER",
    "Jonny": "ELITE",
    "M. Diarra": "GOLD",
    "F. Garcés": "GOLD",
    "Álvaro García": "GOLD",
    "V. Koski": "SILVER",
    "Hugo Novoa": "SILVER",
    "N. Tenaglia": "SILVER",
    "Yusi": "SILVER",
    "Carlos Ballestero García": "BRONZE",
    "P. Sanz": "BRONZE",
    "Carles Aleñá": "ELITE",
    "Antonio Blanco": "GOLD",
    "Guevara": "GOLD",
    "C. Benavídez": "GOLD",
    "Denis Suárez": "GOLD",
    "Pablo Ibáñez": "SILVER",
    "Mikel Rodríguez": "SILVER",
    "L. Boyé": "GOLD",
    "M. Díaz": "GOLD",
    "Toni Martínez": "GOLD",
    "A. Rebbach": "GOLD",
    "Angel Pérez": "SILVER",
    "A. Manas": "BRONZE",
    "Miguel Rodríguez": "SILVER"
  },
  "Athletic Club": {
    "Unai Simón": "ELITE_PLUS",
    "Álex Padilla": "GOLD",
    "Mikel Santos": "BRONZE",
    "Dani Vivian": "ELITE",
    "Yeray": "GOLD",
    "Aymeric Laporte": "ELITE",
    "Yuri": "GOLD",
    "Jesús Areso": "GOLD",
    "Unai Eguíluz": "SILVER",
    "Gorosabel": "GOLD",
    "Iker Monreal": "SILVER",
    "Aitor Paredes": "SILVER",
    "A. Boiro": "SILVER",
    "Alejandro Rego": "BRONZE",
    "Hugo Rincón": "BRONZE",
    "Oihan Sancet": "ELITE_PLUS",
    "Mikel Jauregizar": "ELITE",
    "Mikel Vesga": "GOLD",
    "Ruíz de Galarreta": "GOLD",
    "Beñat Prados": "GOLD",
    "Robert Navarro": "GOLD",
    "Peio Canales": "SILVER",
    "Beñat Gerenabarrena": "SILVER",
    "S. Sanchez": "BRONZE",
    "E. Gift": "BRONZE",
    "Nico Williams": "MASTER",
    "I. Williams": "ELITE_PLUS",
    "Álex Berenguer": "ELITE",
    "Gorka Guruzeta": "GOLD",
    "Álvaro Djaló": "GOLD",
    "Nico Serrano": "GOLD",
    "Maroan Sannadi": "SILVER",
    "A. Hierro": "SILVER"
  },
  "Atletico Madrid": {
    "J. Oblak": "ELITE_PLUS",
    "J. Musso": "GOLD",
    "Salvador Esquivel": "SILVER",
    "Mario de Luis": "BRONZE",
    "Álvaro Moreno": "BRONZE",
    "J. Giménez": "ELITE",
    "Robin Le Normand": "ELITE",
    "Álex Grimaldo": "ELITE",
    "D. Hancko": "ELITE",
    "Marcos Llorente": "ELITE",
    "N. Molina": "GOLD",
    "Marc Pubill": "GOLD",
    "Dani Martínez": "GOLD",
    "Javier Boñar": "SILVER",
    "Julio Díaz del Romo": "BRONZE",
    "A. Puric": "BRONZE",
    "M. Ruggeri": "SILVER",
    "G. Spina": "SILVER",
    "Pablo Barrios": "ELITE_PLUS",
    "M. Hjulmand": "ELITE",
    "Koke": "ELITE",
    "J. Cardoso": "GOLD",
    "Lee Kang-In": "ELITE",
    "Rodrigo Mendoza": "SILVER",
    "J. Morcillo": "SILVER",
    "T. Seidu": "SILVER",
    "Javi Serrano": "SILVER",
    "O. Vargas": "SILVER",
    "J. Álvarez": "MASTER",
    "Álex Baena": "ELITE_PLUS",
    "A. Sørloth": "ELITE",
    "A. Lookman": "ELITE",
    "T. Almada": "ELITE",
    "G. Simeone": "GOLD",
    "M. Llorente": "SILVER",
    "Rayane Belid": "BRONZE"
  },
  "Barcelona": {
    "Joan García": "ELITE",
    "W. Szczęsny": "GOLD",
    "Eder Aller": "BRONZE",
    "Pau Cubarsí": "MASTER",
    "J. Koundé": "ELITE_PLUS",
    "R. Araújo": "ELITE",
    "Alejandro Balde": "ELITE_PLUS",
    "A. Christensen": "GOLD",
    "Eric García": "GOLD",
    "Gerard Martín": "GOLD",
    "Álvaro Cortés Moyano": "BRONZE",
    "X. Espart": "BRONZE",
    "Jofre Torrents": "BRONZE",
    "Pedri": "MASTER",
    "F. de Jong": "ELITE_PLUS",
    "Gavi": "ELITE_PLUS",
    "Fermín": "ELITE_PLUS",
    "Marc Casadó": "ELITE",
    "Marc Bernal": "GOLD",
    "Tomás Marqués": "BRONZE",
    "Dani Olmo": "ELITE_PLUS",
    "Lamine Yamal": "MASTER",
    "Raphinha": "MASTER",
    "Ferran Torres": "ELITE",
    "R. Bardghji": "ELITE",
    "A. Gordon": "GOLD",
    "K. Adeyemi": "ELITE",
    "Juan Hernández": "BRONZE",
    "H. Abdelkarim": "BRONZE"
  },
  "Celta Vigo": {
    "Iván Villar": "GOLD",
    "I. Radu": "SILVER",
    "Coke Carrillo": "BRONZE",
    "C. Starfelt": "GOLD",
    "Unai Núñez": "GOLD",
    "Marcos Alonso": "GOLD",
    "Javi Galán": "GOLD",
    "Carlos Domínguez": "GOLD",
    "Sergio Carreira": "SILVER",
    "Manu Sánchez": "SILVER",
    "Javi Rodríguez": "SILVER",
    "Javi Rueda": "SILVER",
    "Yoel Lago": "SILVER",
    "J. Lopez": "BRONZE",
    "Álvaro Núñez": "SILVER",
    "M. Vecino": "GOLD",
    "I. Moriba": "ELITE",
    "Hugo González": "GOLD",
    "Aleix Febas": "GOLD",
    "Manu Fernández": "SILVER",
    "Andrés Antañón": "SILVER",
    "O. Marcos": "SILVER",
    "Miguel Román": "BRONZE",
    "H. Burcio": "BRONZE",
    "Iago Aspas": "ELITE",
    "Borja Iglesias": "GOLD",
    "Hugo Álvarez": "ELITE",
    "Pablo Durán": "GOLD",
    "Ferran Jutglà": "GOLD",
    "W. Swedberg": "SILVER",
    "B. Somuah": "SILVER",
    "J. El Abdellaoui": "BRONZE"
  },
  "Espanyol": {
    "M. Dmitrović": "GOLD",
    "Ángel Fortuño": "SILVER",
    "Pol Tristán": "BRONZE",
    "Llorenç Serred": "BRONZE",
    "L. Cabrera": "GOLD",
    "Q. Hartman": "GOLD",
    "Pablo Ramón": "SILVER",
    "José Salinas": "SILVER",
    "O. El Hilali": "SILVER",
    "Roger Hinojo": "SILVER",
    "C. Riedel": "SILVER",
    "Miguel Rubio": "SILVER",
    "Rubén Sánchez": "BRONZE",
    "Edu Expósito": "GOLD",
    "Pol Lozano": "GOLD",
    "Urko González": "GOLD",
    "Álex Calatrava": "SILVER",
    "Gabriel Moscardo": "GOLD",
    "F. Gomez": "SILVER",
    "Javier Hernandez": "SILVER",
    "Rafel Bauzà": "BRONZE",
    "Pere Milla": "GOLD",
    "Jofre Carreras": "GOLD",
    "Kike García": "GOLD",
    "Roberto Fernández": "GOLD",
    "Marcos Fernández": "SILVER",
    "T. Dolan": "SILVER",
    "A. Almansa": "BRONZE",
    "Cala": "SILVER"
  },
  "Getafe": {
    "David Soria": "GOLD",
    "J. Letáček": "SILVER",
    "Jorge Benito": "BRONZE",
    "Diego Ferrer": "BRONZE",
    "D. Dakonam": "GOLD",
    "Kiko Femenía": "GOLD",
    "A. Abqar": "GOLD",
    "S. Boselli": "SILVER",
    "Z. Tassounte": "SILVER",
    "Andrés García": "SILVER",
    "Davinchi": "SILVER",
    "Gorka Rivera": "BRONZE",
    "Z. Romero": "BRONZE",
    "Jorge Montes": "BRONZE",
    "J. Valou": "BRONZE",
    "Mario Martín": "GOLD",
    "Ramón Terrats": "GOLD",
    "Javi Muñoz": "GOLD",
    "A. R. Alcantara": "SILVER",
    "Adrián Riquelme": "SILVER",
    "Mady Macalou": "BRONZE",
    "Borja Mayoral": "ELITE",
    "Juanmi": "GOLD",
    "M. Satriano": "GOLD",
    "Álex Sancris": "SILVER"
  },
  "Girona": {
    "P. Gazzaniga": "GOLD",
    "A. Andreev": "SILVER",
    "V. Krapyvtsov": "BRONZE",
    "Arnau Martínez": "ELITE",
    "David López": "GOLD",
    "Alejandro Francés": "GOLD",
    "Álex Moreno": "GOLD",
    "Gibert Jordana": "SILVER",
    "Iván Martín": "ELITE",
    "Fran Beltrán": "GOLD",
    "A. Ounahi": "GOLD",
    "V. Tsygankov": "ELITE",
    "D. van de Beek": "GOLD",
    "Joel Roca": "SILVER",
    "Iván Morante": "SILVER",
    "L. Kourouma": "SILVER",
    "Ricard Artero": "BRONZE",
    "I. Gonzalez": "BRONZE",
    "C. Stuani": "GOLD",
    "Abel Ruiz": "GOLD",
    "Bryan Gil": "GOLD",
    "V. Vanat": "GOLD",
    "Oleksandr Pishchur": "SILVER",
    "P. Ba": "SILVER",
    "Juan Arango": "BRONZE"
  },
  "Las Palmas": {
    "D. Horkaš": "GOLD",
    "José Caro": "SILVER",
    "Adrián Suárez": "BRONZE",
    "Ãlvaro Killane": "BRONZE",
    "Álex Suárez": "GOLD",
    "Enrique Clemente": "GOLD",
    "Cristian Gutiérrez": "GOLD",
    "Manu Fuster": "GOLD",
    "Marvin Park": "SILVER",
    "Juan Herzog": "SILVER",
    "V. Alegre": "BRONZE",
    "C. Navarro": "BRONZE",
    "Valentín Pezzolesi": "BRONZE",
    "A. Rodriguez": "SILVER",
    "Kirian Rodríguez": "GOLD",
    "Sergio Ruiz": "GOLD",
    "E. Loiodice": "SILVER",
    "Iñaki González Zambrano": "SILVER",
    "A. Bassinga": "SILVER",
    "Aimar Dominguez": "BRONZE",
    "Jesé": "GOLD",
    "Sandro Ramírez": "GOLD",
    "T. Miyashiro": "GOLD",
    "Jefté Betancor": "GOLD",
    "Ale García": "SILVER",
    "José Adam Arvelo López": "SILVER",
    "I. Medina": "SILVER",
    "Arturo Rodríguez": "BRONZE",
    "Elías Romero": "BRONZE",
    "Viti Rozada": "SILVER"
  },
  "Leganes": {
    "Juan Soriano": "GOLD",
    "Raúl Fernández": "SILVER",
    "Ignasi Miquel": "GOLD",
    "Enric Franquesa": "GOLD",
    "Rubén Peña": "GOLD",
    "Rubén Pulido": "SILVER",
    "Álvaro Tejero": "SILVER",
    "S. Figueredo": "SILVER",
    "Lalo Aguilar": "SILVER",
    "Marvel": "SILVER",
    "D. Gueye": "SILVER",
    "B. Auguste": "BRONZE",
    "S. Fernandez": "BRONZE",
    "Samuel Bayon Almarza": "BRONZE",
    "L. Macazaga": "BRONZE",
    "S. Imigene": "BRONZE",
    "Dani Rodríguez": "GOLD",
    "Roberto López": "GOLD",
    "Ismaël Gharbi": "GOLD",
    "A. Diawara": "GOLD",
    "Y. Kechta": "GOLD",
    "Z. Buurmeester": "SILVER",
    "Miguel Atienza": "SILVER",
    "Javi Hernández": "SILVER",
    "Melero": "SILVER",
    "Carlos Guirao": "SILVER",
    "Modou Ndiaye": "SILVER",
    "J. Herrero": "BRONZE",
    "Nico Lozano": "BRONZE",
    "G. Rodriguez": "BRONZE",
    "M. Leiva": "BRONZE",
    "G. Siame": "BRONZE",
    "Andrés Campos": "GOLD",
    "Naim García": "SILVER",
    "A. Gøthler": "SILVER",
    "Álex Millán": "SILVER",
    "Carlos de Miguel": "BRONZE"
  },
  "Mallorca": {
    "L. Bergström": "GOLD",
    "Rareș Vlad": "SILVER",
    "Raíllo": "ELITE",
    "Toni Lato": "GOLD",
    "Mateu Morey": "GOLD",
    "M. Valjent": "GOLD",
    "J. Mojica": "GOLD",
    "David López": "GOLD",
    "L. Orejuela": "SILVER",
    "J. Olaizola": "SILVER",
    "M. Calatayud": "BRONZE",
    "Leo Sánchez": "SILVER",
    "A. Souhmahoro": "SILVER",
    "I. Salhi": "SILVER",
    "Manu Morlanes": "ELITE",
    "Samú Costa": "ELITE",
    "Darder": "GOLD",
    "Antonio Sánchez": "GOLD",
    "Pablo Torre": "ELITE",
    "Arnau Puigmal": "SILVER",
    "C. Riba": "SILVER",
    "J. Garcia": "BRONZE",
    "Abdón Prats": "GOLD",
    "Jan Virgili": "GOLD",
    "J. Kalumba": "SILVER",
    "Fuentes": "SILVER"
  },
  "Osasuna": {
    "Sergio Herrera": "GOLD",
    "Aitor Fernández": "GOLD",
    "Rafa": "SILVER",
    "D. Stamatakis": "BRONZE",
    "F. Boyomo": "GOLD",
    "Jorge Herrando": "GOLD",
    "Catena": "GOLD",
    "Abel Bretones": "SILVER",
    "V. Rosier": "SILVER",
    "U. Santos": "SILVER",
    "Moncayola": "ELITE",
    "Aimar Oroz": "ELITE",
    "Iker Muñoz": "GOLD",
    "Lucas Torró": "GOLD",
    "Mauro Echegoyen": "GOLD",
    "Asier Osambela": "SILVER",
    "A. Budimir": "ELITE",
    "Raúl García": "GOLD",
    "Rubén García": "GOLD",
    "Moi Gómez": "GOLD",
    "Kike Barja": "SILVER",
    "Raul Moro": "SILVER",
    "Íñigo Arguibide": "BRONZE",
    "Iker Benito": "BRONZE"
  },
  "Rayo Vallecano": {
    "A. Batalla": "GOLD",
    "Dani Cárdenas": "SILVER",
    "Juanpe": "BRONZE",
    "Adrián Molina": "BRONZE",
    "A. Rațiu": "ELITE",
    "N. Mendy": "GOLD",
    "F. Lejeune": "GOLD",
    "I. Balliu": "GOLD",
    "Pep Chavarría": "GOLD",
    "Pelayo Fernández": "SILVER",
    "S. Lozano": "SILVER",
    "J. Vertrouwd": "SILVER",
    "Marco de las Sías": "BRONZE",
    "Isi Palazón": "ELITE",
    "Unai López": "GOLD",
    "P. Ciss": "GOLD",
    "Jorge de Frutos": "ELITE",
    "Fran Pérez": "GOLD",
    "Álvaro García": "GOLD",
    "Óscar Valentín": "GOLD",
    "Pedro Díaz": "SILVER",
    "Samu Becerra": "SILVER",
    "R. Nteka": "SILVER",
    "M. Roman": "SILVER",
    "Sergio Camello": "ELITE",
    "E. Eto'o": "GOLD"
  },
  "Real Betis": {
    "Álvaro Vallés": "GOLD",
    "Diego Conde": "SILVER",
    "Marc Bartra": "GOLD",
    "Héctor Bellerín": "GOLD",
    "Diego Llorente": "GOLD",
    "Junior Firpo": "GOLD",
    "Natan": "GOLD",
    "Fran García": "GOLD",
    "V. Gómez": "SILVER",
    "Pablo Busto": "SILVER",
    "C. De Roa": "BRONZE",
    "Ángel Ortiz": "BRONZE",
    "Isco": "ELITE",
    "G. Lo Celso": "ELITE",
    "Álvaro Fidalgo": "ELITE",
    "Marc Roca": "GOLD",
    "Pablo Fornals": "GOLD",
    "N. Deossa": "GOLD",
    "F. Bernal": "SILVER",
    "Ivan Corralejo": "SILVER",
    "Antony": "ELITE",
    "A. Ezzalzouli": "GOLD",
    "Rodrigo Riquelme": "GOLD",
    "Aitor Ruibal": "GOLD",
    "G. Petit": "SILVER",
    "C. Hernández": "SILVER",
    "Iker Losada": "SILVER",
    "R. Marina": "SILVER"
  },
  "Real Madrid": {
    "T. Courtois": "ELITE_PLUS",
    "A. Lunin": "GOLD",
    "Fran González": "BRONZE",
    "Sergio Mestre": "BRONZE",
    "J. Navarro Jimenez": "BRONZE",
    "D. Huijsen": "ELITE_PLUS",
    "Éder Militão": "ELITE",
    "A. Rüdiger": "ELITE",
    "I. Konaté": "ELITE",
    "T. Alexander-Arnold": "ELITE_PLUS",
    "Marc Cucurella": "ELITE",
    "D. Dumfries": "ELITE",
    "Raúl Asencio": "GOLD",
    "F. Mendy": "GOLD",
    "Álvaro Fernández": "SILVER",
    "L. Fati": "SILVER",
    "Jesús Fortea": "SILVER",
    "David Jiménez": "BRONZE",
    "M. Serrano": "BRONZE",
    "Diego Aguado": "BRONZE",
    "J. Bellingham": "MASTER",
    "F. Valverde": "MASTER",
    "Bernardo Silva": "ELITE_PLUS",
    "E. Camavinga": "ELITE_PLUS",
    "A. Tchouaméni": "ELITE_PLUS",
    "A. Güler": "ELITE",
    "Brahim Díaz": "ELITE",
    "César Palacios": "SILVER",
    "Thiago Pitarch": "SILVER",
    "J. Cestero Sancho": "BRONZE",
    "Manuel Ángel": "BRONZE",
    "Kylian Mbappé": "MASTER",
    "Vinícius Júnior": "MASTER",
    "Rodrygo": "ELITE_PLUS",
    "Franco Mastantuono": "ELITE",
    "Gonzalo García": "GOLD",
    "Ávaro Leiva": "SILVER",
    "Daniel Yañez": "BRONZE"
  },
  "Real Sociedad": {
    "Álex Remiro": "ELITE",
    "Unai Marrero": "SILVER",
    "Aitor Fraga": "BRONZE",
    "T. Folgado": "BRONZE",
    "Jon Pacheco": "ELITE",
    "Zubeldia": "GOLD",
    "Odriozola": "GOLD",
    "Aihen Muñoz": "GOLD",
    "J. Aramburu": "GOLD",
    "Javi López": "SILVER",
    "Jon Martín": "SILVER",
    "K. Kita": "SILVER",
    "J. Ochieng": "SILVER",
    "Rupérez": "BRONZE",
    "Luken Beitia": "BRONZE",
    "T. Kubo": "ELITE_PLUS",
    "L. Sučić": "ELITE",
    "Beñat Turrientes": "ELITE",
    "Carlos Soler": "GOLD",
    "Jon Gorrotxategi": "GOLD",
    "Y. Herrera": "GOLD",
    "A. Zakharyan": "GOLD",
    "Mikel Goti": "SILVER",
    "Pablo Marín": "SILVER",
    "Ibai Aguirre": "SILVER",
    "Lander Astiazarán": "SILVER",
    "Mikel Oyarzabal": "ELITE_PLUS",
    "Gonçalo Guedes": "GOLD",
    "O. Óskarsson": "GOLD",
    "Barrenetxea": "GOLD",
    "Jon Karrikaburu": "SILVER",
    "Dani Díaz": "SILVER",
    "Gorka Carrera": "SILVER",
    "Alex Garcia": "BRONZE"
  },
  "Sevilla": {
    "O. Vlachodimos": "ELITE",
    "Alberto Flores": "SILVER",
    "Rafael Romero": "BRONZE",
    "José Ángel Carmona": "GOLD",
    "G. Suazo": "GOLD",
    "Adrià Pedrosa": "GOLD",
    "F. Gattoni": "GOLD",
    "Fábio Cardoso": "GOLD",
    "Juanlu Sánchez": "GOLD",
    "Kike Salas": "SILVER",
    "I. Munoz": "SILVER",
    "Andrés Castrín": "SILVER",
    "Oso": "BRONZE",
    "A. Sangante": "BRONZE",
    "L. Agoumé": "GOLD",
    "Jon Guridi": "GOLD",
    "Joan Jordán": "GOLD",
    "D. Sow": "GOLD",
    "Juan Iglesias": "SILVER",
    "R. Vargas": "SILVER",
    "Manu Bueno": "SILVER",
    "N. Guillen": "BRONZE",
    "Eduardo Altozano Agudo": "BRONZE",
    "P. Mercado": "BRONZE",
    "C. Ejuke": "GOLD",
    "Isaac": "GOLD",
    "M. Sierra": "SILVER",
    "Peque Fernández": "SILVER"
  },
  "Valencia": {
    "S. Dimitrievski": "GOLD",
    "Cristian Rivero": "SILVER",
    "Vicent Abril": "BRONZE",
    "José Gayà": "ELITE",
    "M. Diakhaby": "GOLD",
    "César Tárrega": "GOLD",
    "D. Foulquier": "GOLD",
    "Copete": "GOLD",
    "J. de Haas": "SILVER",
    "Jesús Vázquez": "SILVER",
    "Iker Córdoba": "SILVER",
    "A. Panach": "SILVER",
    "Marcos Navarro": "BRONZE",
    "Aaron Mayol": "BRONZE",
    "Rubo Iranzo": "BRONZE",
    "Joel Fontanet": "BRONZE",
    "Javi Guerra": "ELITE",
    "Pepelu": "GOLD",
    "André Almeida": "GOLD",
    "G. Rodríguez": "GOLD",
    "A. Dieng": "SILVER",
    "F. Ugrinic": "SILVER",
    "R. Sato": "SILVER",
    "Hugo Duro": "GOLD",
    "A. Danjuma": "ELITE",
    "Luis Rioja": "GOLD",
    "U. Sadiq": "SILVER",
    "Dani Raba": "SILVER",
    "David Otorbi": "BRONZE",
    "Aimar Blázquez": "BRONZE"
  },
  "Valladolid": {
    "Álvaro Aceves": "SILVER",
    "A. de Pablo": "BRONZE",
    "Marcos André": "GOLD",
    "Juanmi Latasa": "GOLD",
    "Ramón Martínez": "GOLD",
    "David Torres": "GOLD",
    "C. Michelin": "SILVER",
    "Iván Garriel": "SILVER",
    "M. Jaouab": "SILVER",
    "Alejandro Galdeano": "BRONZE",
    "Víctor Meseguer": "GOLD",
    "S. Jurić": "GOLD",
    "M. Lachuer": "SILVER",
    "Dani Pérez": "SILVER",
    "J. Ponceau": "SILVER",
    "Ricardo de Moraes": "SILVER",
    "T. Ojeda": "SILVER",
    "L. Sanseviero": "SILVER",
    "Pablo Tomeo": "BRONZE",
    "I. Alani": "BRONZE",
    "Iván Alejo": "GOLD",
    "A. Ndiaye": "GOLD",
    "K. de Rooij": "GOLD",
    "S. Biuk": "GOLD",
    "Victor Barberá": "SILVER",
    "Luis Chacón": "SILVER",
    "Víctor Fernández": "SILVER",
    "A. Carvajal": "SILVER",
    "R. Duiven": "SILVER",
    "Brain Chinedu": "BRONZE",
    "Hugo San": "BRONZE"
  },
  "Villarreal": {
    "Rubén Gómez": "GOLD",
    "Luíz Júnior": "SILVER",
    "Y. Kinareykin": "BRONZE",
    "Renato Veiga": "ELITE",
    "Logan Costa": "GOLD",
    "Willy Kambwala Ndengushi": "GOLD",
    "Sergi Cardona": "GOLD",
    "Pau Navarro": "SILVER",
    "S. Mouriño": "SILVER",
    "Carlos Romero": "SILVER",
    "Daniel Budesca": "BRONZE",
    "A. Freeman": "BRONZE",
    "P. Gueye": "ELITE",
    "Santi Comesaña": "GOLD",
    "Alberto Moleiro": "ELITE",
    "A. Diatta": "GOLD",
    "T. Fernández": "SILVER",
    "C. Macia": "SILVER",
    "T. Buchanan": "GOLD",
    "G. Mikautadze": "ELITE",
    "Gerard Moreno": "ELITE",
    "Ayoze Pérez": "GOLD",
    "N. Pépé": "GOLD",
    "Álex Forés": "SILVER",
    "Hugo López": "SILVER",
    "T. Oluwaseyi": "SILVER"
  }
};

function normalize(str) {
  return str ? str.replace(/&apos;/g, "'").toLowerCase().replace(/['’\-]/g, '').replace(/[^a-z0-9]/g, '') : '';
}

const dir = path.join(__dirname, '..', 'data', 'players', 'active', 'la-liga');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));

let totalMatches = 0;
let totalMissingInJson = [];
let totalUnmappedInJson = [];

files.forEach(file => {
  const filePath = path.join(dir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const clubName = data.club.name;
  
  // Find key in PROMPT_TIERS
  const promptKey = Object.keys(PROMPT_TIERS).find(k => normalize(k) === normalize(clubName) || clubName.includes(k) || k.includes(clubName));
  const promptMap = promptKey ? PROMPT_TIERS[promptKey] : {};
  
  const normPrompt = {};
  Object.keys(promptMap).forEach(k => {
    normPrompt[normalize(k)] = { original: k, tier: promptMap[k] };
  });

  const matchedPromptKeys = new Set();

  data.players.forEach(p => {
    const pNorm = normalize(p.name);
    let match = normPrompt[pNorm];

    if (!match) {
      // Try last name / partial matching
      const parts = p.name.split(' ');
      const lastName = normalize(parts[parts.length - 1]);
      const keys = Object.keys(normPrompt);
      const foundKey = keys.find(k => k === lastName || k.endsWith(lastName) || lastName.endsWith(k));
      if (foundKey) {
        match = normPrompt[foundKey];
      }
    }

    if (match) {
      totalMatches++;
      matchedPromptKeys.add(match.original);
    } else {
      totalUnmappedInJson.push({ club: clubName, name: p.name, kitNumber: p.kitNumber });
    }
  });

  Object.keys(promptMap).forEach(k => {
    if (!matchedPromptKeys.has(k)) {
      totalMissingInJson.push({ club: clubName, promptName: k, tier: promptMap[k] });
    }
  });
});

console.log(`Matched ${totalMatches} players between prompt and JSON.`);
console.log(`Unmapped players in JSON (${totalUnmappedInJson.length}):`);
totalUnmappedInJson.forEach(u => console.log(`  - [${u.club}] ${u.name} (#${u.kitNumber})`));
console.log(`\nPrompt players missing in JSON (${totalMissingInJson.length}):`);
totalMissingInJson.forEach(m => console.log(`  - [${m.club}] ${m.promptName} (${m.tier})`));
