const fs = require('fs');
const path = require('path');

// 1. COMPREHENSIVE PREMIER LEAGUE NATION MAP
const REAL_PL_NATIONS = {
  // Arsenal
  "David Raya": "Spain",
  "Kepa": "Spain",
  "I. Meslier": "France",
  "W. Saliba": "France",
  "Gabriel Magalhães": "Brazil",
  "R. Calafiori": "Italy",
  "J. Timber": "Netherlands",
  "B. White": "England",
  "P. Hincapié": "Ecuador",
  "Cristhian Mosquera": "Spain",
  "M. Lewis-Skelly": "England",
  "D. Rice": "England",
  "M. Ødegaard": "Norway",
  "Martín Zubimendi": "Spain",
  "Mikel Merino": "Spain",
  "E. Eze": "England",
  "C. Nørgaard": "Denmark",
  "B. Saka": "England",
  "V. Gyökeres": "Sweden",
  "K. Havertz": "Germany",
  "Gabriel Martinelli": "Brazil",
  "Gabriel Jesus": "Brazil",
  "N. Madueke": "England",
  "C. Tzolis": "Greece",

  // Aston Villa
  "E. Martínez": "Argentina",
  "Emiliano Martínez": "Argentina",
  "R. Olsen": "Sweden",
  "J. Gauci": "Australia",
  "E. Konsa": "England",
  "Pau Torres": "Spain",
  "D. Carlos": "Brazil",
  "T. Mings": "England",
  "I. Maatsen": "Netherlands",
  "L. Digne": "France",
  "M. Cash": "Poland",
  "K. Nedeljković": "Serbia",
  "A. Onana": "Belgium",
  "Amadou Onana": "Belgium",
  "B. Kamara": "France",
  "J. McGinn": "Scotland",
  "Y. Tielemans": "Belgium",
  "E. Barrenechea": "Argentina",
  "M. Rogers": "England",
  "Morgan Rogers": "England",
  "E. Buendía": "Argentina",
  "J. Ramsey": "England",
  "L. Bailey": "Jamaica",
  "O. Watkins": "England",
  "Ollie Watkins": "England",
  "J. Duran": "Colombia",
  "Jhon Durán": "Colombia",

  // Bournemouth
  "K. Kepa": "Spain",
  "Neto": "Brazil",
  "M. Travers": "Ireland",
  "I. Zabarnyi": "Ukraine",
  "M. Senesi": "Argentina",
  "D. Huijsen": "Spain",
  "M. Kerkez": "Hungary",
  "M. Aarons": "England",
  "J. Smith": "England",
  "T. Adams": "USA",
  "L. Cook": "England",
  "R. Christie": "Scotland",
  "A. Scott": "England",
  "P. Billing": "Denmark",
  "J. Kluivert": "Netherlands",
  "A. Semenyo": "Ghana",
  "M. Tavernier": "England",
  "L. Sinisterra": "Colombia",
  "E. Ünal": "Turkey",
  "Evanilson": "Brazil",

  // Brentford
  "M. Flekken": "Netherlands",
  "H. Valdimarsson": "Iceland",
  "N. Collins": "Ireland",
  "E. Pinnock": "Jamaica",
  "S. van den Berg": "Netherlands",
  "K. Ajer": "Norway",
  "R. Henry": "England",
  "A. Hickey": "Scotland",
  "C. Nørgaard": "Denmark",
  "M. Jensen": "Denmark",
  "V. Janelt": "Germany",
  "Y. Konak": "Turkey",
  "F. Carvalho": "Portugal",
  "M. Damsgaard": "Denmark",
  "B. Mbeumo": "Cameroon",
  "Bryan Mbeumo": "Cameroon",
  "Y. Wissa": "DR Congo",
  "K. Schade": "Germany",
  "I. Thiago": "Brazil",

  // Brighton
  "B. Verbruggen": "Netherlands",
  "J. Steele": "England",
  "L. Dunk": "England",
  "J. van Hecke": "Netherlands",
  "I. Igor": "Brazil",
  "A. Webster": "England",
  "P. Estupiñán": "Ecuador",
  "T. Lamptey": "Ghana",
  "J. Veltman": "Netherlands",
  "C. Baleba": "Cameroon",
  "Carlos Baleba": "Cameroon",
  "M. Wieffer": "Netherlands",
  "Y. Ayari": "Sweden",
  "J. Moder": "Poland",
  "J. Milner": "England",
  "M. O'Riley": "Denmark",
  "K. Mitoma": "Japan",
  "Kaoru Mitoma": "Japan",
  "Y. Minteh": "Gambia",
  "Yankuba Minteh": "Gambia",
  "S. Adingra": "Ivory Coast",
  "G. Rutter": "France",
  "João Pedro": "Brazil",
  "E. Ferguson": "Ireland",
  "D. Welbeck": "England",

  // Chelsea
  "R. Sánchez": "Spain",
  "F. Jørgensen": "Denmark",
  "M. Bettinelli": "England",
  "L. Colwill": "England",
  "M. Cucurella": "Spain",
  "W. Fofana": "France",
  "A. Disasi": "France",
  "B. Badiashile": "France",
  "T. Adarabioyo": "England",
  "R. James": "England",
  "M. Gusto": "France",
  "M. Caicedo": "Ecuador",
  "Moisés Caicedo": "Ecuador",
  "Enzo Fernández": "Argentina",
  "E. Fernández": "Argentina",
  "R. Lavia": "Belgium",
  "K. Dewsbury-Hall": "England",
  "C. Palmer": "England",
  "Cole Palmer": "England",
  "Estêvão": "Brazil",
  "Kendry Páez": "Ecuador",
  "P. Neto": "Portugal",
  "Pedro Neto": "Portugal",
  "J. Félix": "Portugal",
  "João Félix": "Portugal",
  "J. Sancho": "England",
  "M. Mudryk": "Ukraine",
  "N. Jackson": "Senegal",
  "Nicolas Jackson": "Senegal",
  "C. Nkunku": "France",
  "Christopher Nkunku": "France",
  "Marc Guiu": "Spain",

  // Crystal Palace
  "D. Henderson": "England",
  "M. Turner": "USA",
  "M. Guéhi": "England",
  "Marc Guéhi": "England",
  "C. Riad": "Morocco",
  "M. Lacroix": "France",
  "C. Richards": "USA",
  "J. Lerma": "Colombia",
  "D. Muñoz": "Colombia",
  "T. Mitchell": "England",
  "A. Wharton": "England",
  "Adam Wharton": "England",
  "C. Doucouré": "Mali",
  "W. Hughes": "England",
  "J. Devenny": "Scotland",
  "D. Kamada": "Japan",
  "I. Sarr": "Senegal",
  "J. Mateta": "France",
  "Jean-Philippe Mateta": "France",
  "E. Nketiah": "England",

  // Everton
  "J. Pickford": "England",
  "Jordan Pickford": "England",
  "J. Virginia": "Portugal",
  "J. Branthwaite": "England",
  "Jarrad Branthwaite": "England",
  "J. Tarkowski": "England",
  "M. Keane": "England",
  "J. O'Brien": "Ireland",
  "V. Mykolenko": "Ukraine",
  "N. Patterson": "Scotland",
  "S. Coleman": "Ireland",
  "I. Gueye": "Senegal",
  "J. Garner": "England",
  "T. Iroegbunam": "England",
  "A. Doucouré": "Mali",
  "I. Ndiaye": "Senegal",
  "J. Harrison": "England",
  "D. McNeil": "England",
  "J. Lindstrøm": "Denmark",
  "D. Calvert-Lewin": "England",
  "B. Beto": "Portugal",
  "A. Broja": "Albania",

  // Fulham
  "B. Leno": "Germany",
  "Bernd Leno": "Germany",
  "S. Benda": "Germany",
  "J. Andersen": "Denmark",
  "Joachim Andersen": "Denmark",
  "C. Bassey": "Nigeria",
  "J. Cuenca": "Spain",
  "A. Robinson": "USA",
  "Antonee Robinson": "USA",
  "T. Castagne": "Belgium",
  "S. Berge": "Norway",
  "Sander Berge": "Norway",
  "S. Lukić": "Serbia",
  "A. Pereira": "Brazil",
  "Andreas Pereira": "Brazil",
  "E. Smith Rowe": "England",
  "Emile Smith Rowe": "England",
  "H. Wilson": "Wales",
  "A. Iwobi": "Nigeria",
  "Alex Iwobi": "Nigeria",
  "Adama Traoré": "Spain",
  "R. Jiménez": "Mexico",
  "Raúl Jiménez": "Mexico",
  "R. Muniz": "Brazil",
  "Rodrigo Muniz": "Brazil",

  // Ipswich
  "A. Muric": "Kosovo",
  "C. Walton": "England",
  "J. Greaves": "England",
  "D. O'Shea": "Ireland",
  "C. Burgess": "Australia",
  "L. Davis": "England",
  "A. Tuanzebe": "DR Congo",
  "B. Johnson": "England",
  "K. Phillips": "England",
  "J. Cajuste": "Sweden",
  "M. Luongo": "Australia",
  "S. Morsy": "Egypt",
  "S. Szmodics": "Ireland",
  "C. Chaplin": "England",
  "O. Hutchinson": "Jamaica",
  "J. Clarke": "England",
  "C. Chiedozie": "Ireland",
  "L. Delap": "England",
  "Liam Delap": "England",
  "G. Hirst": "England",

  // Leicester
  "M. Hermansen": "Denmark",
  "D. Ward": "Wales",
  "W. Faes": "Belgium",
  "C. Okoli": "Italy",
  "J. Vestergaard": "Denmark",
  "V. Kristiansen": "Denmark",
  "J. Justin": "England",
  "R. Pereira": "Portugal",
  "W. Ndidi": "Nigeria",
  "Wilfred Ndidi": "Nigeria",
  "H. Winks": "England",
  "O. Skipp": "England",
  "B. El Khannouss": "Morocco",
  "Bilal El Khannouss": "Morocco",
  "F. Buonanotte": "Argentina",
  "Facundo Buonanotte": "Argentina",
  "S. Mavididi": "England",
  "A. Fatawu": "Ghana",
  "Abdul Fatawu": "Ghana",
  "J. Ayew": "Ghana",
  "J. Vardy": "England",
  "Jamie Vardy": "England",
  "P. Daka": "Zambia",

  // Liverpool
  "Alisson": "Brazil",
  "Alisson Becker": "Brazil",
  "C. Kelleher": "Ireland",
  "V. van Dijk": "Netherlands",
  "Virgil van Dijk": "Netherlands",
  "I. Konaté": "France",
  "Ibrahima Konaté": "France",
  "J. Gomez": "England",
  "J. Quansah": "England",
  "A. Robertson": "Scotland",
  "Andy Robertson": "Scotland",
  "K. Tsimikas": "Greece",
  "T. Alexander-Arnold": "England",
  "Trent Alexander-Arnold": "England",
  "C. Bradley": "Northern Ireland",
  "R. Gravenberch": "Netherlands",
  "Ryan Gravenberch": "Netherlands",
  "A. Mac Allister": "Argentina",
  "Alexis Mac Allister": "Argentina",
  "D. Szoboszlai": "Hungary",
  "Dominik Szoboszlai": "Hungary",
  "W. Endo": "Japan",
  "C. Jones": "England",
  "H. Elliott": "England",
  "M. Salah": "Egypt",
  "Mohamed Salah": "Egypt",
  "L. Díaz": "Colombia",
  "Luis Díaz": "Colombia",
  "C. Gakpo": "Netherlands",
  "Cody Gakpo": "Netherlands",
  "D. Nunez": "Uruguay",
  "Darwin Núñez": "Uruguay",
  "F. Chiesa": "Italy",
  "Federico Chiesa": "Italy",

  // Manchester City
  "Ederson": "Brazil",
  "S. Ortega": "Germany",
  "R. Dias": "Portugal",
  "Rúben Dias": "Portugal",
  "J. Gvardiol": "Croatia",
  "Joško Gvardiol": "Croatia",
  "M. Akanji": "Switzerland",
  "N. Aké": "Netherlands",
  "J. Stones": "England",
  "R. Lewis": "England",
  "K. Walker": "England",
  "Rodri": "Spain",
  "M. Kovačić": "Croatia",
  "Matteo Kovačić": "Croatia",
  "I. Gündoğan": "Germany",
  "Ilkay Gündoğan": "Germany",
  "K. De Bruyne": "Belgium",
  "Kevin De Bruyne": "Belgium",
  "P. Foden": "England",
  "Phil Foden": "England",
  "Bernardo Silva": "Portugal",
  "J. Doku": "Belgium",
  "Jeremy Doku": "Belgium",
  "Savinho": "Brazil",
  "J. Grealish": "England",
  "Jack Grealish": "England",
  "E. Haaland": "Norway",
  "Erling Haaland": "Norway",
  "O. Bobb": "Norway",

  // Manchester United
  "A. Onana": "Cameroon",
  "André Onana": "Cameroon",
  "A. Bayındır": "Turkey",
  "L. Martínez": "Argentina",
  "Lisandro Martínez": "Argentina",
  "M. de Ligt": "Netherlands",
  "Matthijs de Ligt": "Netherlands",
  "L. Yoro": "France",
  "Leny Yoro": "France",
  "H. Maguire": "England",
  "V. Lindelöf": "Sweden",
  "L. Shaw": "England",
  "N. Mazraoui": "Morocco",
  "D. Dalot": "Portugal",
  "Diogo Dalot": "Portugal",
  "Casemiro": "Brazil",
  "M. Ugarte": "Uruguay",
  "Manuel Ugarte": "Uruguay",
  "K. Mainoo": "England",
  "Kobbie Mainoo": "England",
  "Bruno Fernandes": "Portugal",
  "C. Eriksen": "Denmark",
  "M. Mount": "England",
  "A. Diallo": "Ivory Coast",
  "Amad Diallo": "Ivory Coast",
  "A. Garnacho": "Argentina",
  "Alejandro Garnacho": "Argentina",
  "M. Rashford": "England",
  "Marcus Rashford": "England",
  "Antony": "Brazil",
  "R. Højlund": "Denmark",
  "Rasmus Højlund": "Denmark",
  "J. Zirkzee": "Netherlands",
  "Joshua Zirkzee": "Netherlands",
  "Chido Obi-Martin": "Denmark",

  // Newcastle United
  "N. Pope": "England",
  "M. Dubravka": "Slovakia",
  "O. Vlachodimos": "Greece",
  "S. Botman": "Netherlands",
  "F. Schär": "Switzerland",
  "Fabian Schär": "Switzerland",
  "L. Hall": "England",
  "D. Burn": "England",
  "T. Livramento": "England",
  "K. Trippier": "England",
  "B. Guimarães": "Brazil",
  "Bruno Guimarães": "Brazil",
  "S. Tonali": "Italy",
  "Sandro Tonali": "Italy",
  "Jelinton": "Brazil",
  "Joelinton": "Brazil",
  "J. Willock": "England",
  "S. Longstaff": "England",
  "L. Miley": "England",
  "A. Gordon": "England",
  "Anthony Gordon": "England",
  "H. Barnes": "England",
  "J. Murphy": "England",
  "M. Almirón": "Paraguay",
  "A. Isak": "Sweden",
  "Alexander Isak": "Sweden",
  "C. Wilson": "England",
  "W. Osula": "Denmark",

  // Nottingham Forest
  "M. Sels": "Belgium",
  "C. Miguel": "Brazil",
  "Murillo": "Brazil",
  "N. Milenković": "Serbia",
  "W. Boly": "Ivory Coast",
  "A. Moreno": "Spain",
  "O. Aina": "Nigeria",
  "N. Williams": "Wales",
  "I. Sangaré": "Ivory Coast",
  "Elliot Anderson": "Scotland",
  "E. Anderson": "Scotland",
  "N. Domínguez": "Argentina",
  "R. Yates": "England",
  "M. Gibbs-White": "England",
  "Morgan Gibbs-White": "England",
  "C. Hudson-Odoi": "England",
  "A. Elanga": "Sweden",
  "J. Silva": "Portugal",
  "C. Wood": "New Zealand",
  "Chris Wood": "New Zealand",
  "T. Awoniyi": "Nigeria",

  // Southampton
  "A. Ramsdale": "England",
  "Aaron Ramsdale": "England",
  "A. McCarthy": "England",
  "T. Harwood-Bellis": "England",
  "J. Bednarek": "Poland",
  "R. Sugawara": "Japan",
  "K. Walker-Peters": "England",
  "C. Taylor": "England",
  "Flynn Downes": "England",
  "F. Downes": "England",
  "L. Ugochukwu": "France",
  "W. Smallbone": "Ireland",
  "J. Aribo": "Nigeria",
  "M. Fernandes": "Portugal",
  "A. Lallana": "England",
  "T. Dibling": "England",
  "Tyler Dibling": "England",
  "R. Fraser": "Scotland",
  "C. Archer": "England",
  "B. Brereton Díaz": "Chile",
  "P. Onuachu": "Nigeria",

  // Tottenham Hotspur
  "G. Vicario": "Italy",
  "Guglielmo Vicario": "Italy",
  "F. Forster": "England",
  "C. Romero": "Argentina",
  "Cristian Romero": "Argentina",
  "M. van de Ven": "Netherlands",
  "Micky van de Ven": "Netherlands",
  "R. Drăgușin": "Romania",
  "Radu Drăgușin": "Romania",
  "D. Udogie": "Italy",
  "Destiny Udogie": "Italy",
  "B. Davies": "Wales",
  "Pedro Porro": "Spain",
  "P. Porro": "Spain",
  "D. Gray": "England",
  "Archie Gray": "England",
  "Y. Bissouma": "Mali",
  "P. Sarr": "Senegal",
  "Pape Matar Sarr": "Senegal",
  "R. Bentancur": "Uruguay",
  "L. Bergvall": "Sweden",
  "Lucas Bergvall": "Sweden",
  "J. Maddison": "England",
  "James Maddison": "England",
  "D. Kulusevski": "Sweden",
  "Dejan Kulusevski": "Sweden",
  "Son Heung-min": "South Korea",
  "H. Son": "South Korea",
  "B. Johnson": "Wales",
  "Brennan Johnson": "Wales",
  "W. Odobert": "France",
  "Mikey Moore": "England",
  "D. Solanke": "England",
  "Dominic Solanke": "England",
  "Richarlison": "Brazil",
  "T. Werner": "Germany",

  // West Ham United
  "A. Areola": "France",
  "L. Fabiański": "Poland",
  "M. Guéhi": "England",
  "M. Kilman": "England",
  "J. Todibo": "France",
  "Jean-Clair Todibo": "France",
  "K. Mavropanos": "Greece",
  "E. Palmieri": "Italy",
  "Emerson Palmieri": "Italy",
  "A. Wan-Bissaka": "England",
  "V. Coufal": "Czech Republic",
  "E. Alvarez": "Mexico",
  "Edson Álvarez": "Mexico",
  "G. Rodríguez": "Argentina",
  "T. Souček": "Czech Republic",
  "Tomas Souček": "Czech Republic",
  "L. Paquetá": "Brazil",
  "Lucas Paquetá": "Brazil",
  "C. Soler": "Spain",
  "M. Kudus": "Ghana",
  "Mohammed Kudus": "Ghana",
  "J. Bowen": "England",
  "Jarrod Bowen": "England",
  "C. Summerville": "Netherlands",
  "Crysencio Summerville": "Netherlands",
  "L. Guilherme": "Brazil",
  "N. Füllkrug": "Germany",
  "Niclas Füllkrug": "Germany",
  "M. Antonio": "Jamaica",
  "D. Ings": "England",

  // Wolverhampton Wanderers
  "J. Sá": "Portugal",
  "José Sá": "Portugal",
  "D. Bentley": "England",
  "S. Bueno": "Uruguay",
  "T. Gomes": "Portugal",
  "Y. Mosquera": "Colombia",
  "R. Aït-Nouri": "Algeria",
  "Rayan Aït-Nouri": "Algeria",
  "N. Semedo": "Portugal",
  "M. Doherty": "Ireland",
  "A. André": "Brazil",
  "B. Traoré": "Mali",
  "M. Lemina": "Gabon",
  "T. Doyle": "England",
  "J. Bellegarde": "France",
  "J. Larsen": "Norway",
  "Jørgen Strand Larsen": "Norway",
  "M. Cunha": "Brazil",
  "Matheus Cunha": "Brazil",
  "Hwang Hee-Chan": "South Korea",
  "H. Hwang": "South Korea",
  "G. Guedes": "Portugal",
  "C. Forbs": "Portugal",
  "S. Kalajdžić": "Austria"
};

// 2. COMPREHENSIVE HONEST TIER MAP FOR PREMIER LEAGUE
const HONEST_PL_TIERS = {
  MASTER: new Set([
    "Erling Haaland", "E. Haaland", "Kevin De Bruyne", "K. De Bruyne", "Rodri",
    "Mohamed Salah", "M. Salah", "Bukayo Saka", "B. Saka", "Virgil van Dijk", "V. van Dijk",
    "Declan Rice", "D. Rice", "William Saliba", "W. Saliba", "Bruno Fernandes",
    "Phil Foden", "P. Foden", "Cole Palmer", "C. Palmer", "Alexander Isak", "A. Isak"
  ]),

  ELITE_PLUS: new Set([
    "David Raya", "Gabriel Magalhães", "M. Ødegaard", "Martín Zubimendi", "K. Havertz", "V. Gyökeres",
    "Emiliano Martínez", "E. Martínez", "Ollie Watkins", "O. Watkins", "Bryan Mbeumo", "B. Mbeumo",
    "Alexis Mac Allister", "A. Mac Allister", "Trent Alexander-Arnold", "T. Alexander-Arnold", "Luis Díaz", "L. Díaz",
    "Alisson", "Alisson Becker", "Rúben Dias", "R. Dias", "Joško Gvardiol", "J. Gvardiol", "Bernardo Silva",
    "Son Heung-min", "H. Son", "Cristian Romero", "C. Romero", "Guglielmo Vicario", "G. Vicario", "Anthony Gordon", "A. Gordon",
    "Bruno Guimarães", "B. Guimarães", "E. Eze", "Jean-Philippe Mateta", "J. Mateta", "Matheus Cunha", "M. Cunha",
    "Bernd Leno", "B. Leno", "André Onana", "A. Onana", "Jarrod Bowen", "J. Bowen"
  ]),

  ELITE: new Set([
    "J. Timber", "R. Calafiori", "B. White", "Mikel Merino", "Gabriel Martinelli", "Gabriel Jesus",
    "Ezri Konsa", "E. Konsa", "Pau Torres", "John McGinn", "J. McGinn", "Morgan Rogers", "M. Rogers", "Amadou Onana", "A. Onana", "Jhon Durán", "J. Duran",
    "Antoine Semenyo", "A. Semenyo", "Evanilson", "Justin Kluivert", "J. Kluivert", "Milosh Kerkez", "M. Kerkez", "Illan Zabarnyi", "I. Zabarnyi",
    "Yoane Wissa", "Y. Wissa", "Kevin Schade", "K. Schade", "Nathan Collins", "N. Collins",
    "Kaoru Mitoma", "K. Mitoma", "Yankuba Minteh", "Y. Minteh", "Carlos Baleba", "C. Baleba", "João Pedro", "Evan Ferguson", "E. Ferguson", "Bart Verbruggen", "B. Verbruggen",
    "Moises Caicedo", "M. Caicedo", "Moisés Caicedo", "Enzo Fernández", "E. Fernández", "Levi Colwill", "L. Colwill", "Marc Cucurella", "M. Cucurella", "Reece James", "R. James", "Malo Gusto", "M. Gusto", "Pedro Neto", "P. Neto", "João Félix", "J. Félix", "Nicolas Jackson", "N. Jackson", "Christopher Nkunku", "C. Nkunku", "Estêvão",
    "Marc Guéhi", "M. Guéhi", "Adam Wharton", "A. Wharton", "Daniel Muñoz", "D. Muñoz", "Ismaïla Sarr", "I. Sarr",
    "Jordan Pickford", "J. Pickford", "Jarrad Branthwaite", "J. Branthwaite", "Vitaliy Mykolenko", "V. Mykolenko", "Iliman Ndiaye", "I. Ndiaye", "Dwight McNeil", "D. McNeil",
    "Joachim Andersen", "J. Andersen", "Antonee Robinson", "A. Robinson", "Sander Berge", "S. Berge", "Emile Smith Rowe", "E. Smith Rowe", "Alex Iwobi", "A. Iwobi", "Rodrigo Muniz", "R. Muniz", "Raúl Jiménez", "R. Jiménez",
    "Liam Delap", "L. Delap", "Omari Hutchinson", "O. Hutchinson", "Leif Davis", "L. Davis",
    "Wilfred Ndidi", "W. Ndidi", "Bilal El Khannouss", "B. El Khannouss", "Facundo Buonanotte", "F. Buonanotte", "Mads Hermansen", "M. Hermansen",
    "Ibrahima Konaté", "I. Konaté", "Dominik Szoboszlai", "D. Szoboszlai", "Cody Gakpo", "C. Gakpo", "Ryan Gravenberch", "R. Gravenberch", "Andy Robertson", "A. Robertson", "Conor Bradley", "C. Bradley", "Federico Chiesa", "F. Chiesa",
    "Manuel Akanji", "M. Akanji", "Nathan Aké", "N. Aké", "Jeremy Doku", "J. Doku", "Savinho", "Ilkay Gündoğan", "I. Gündoğan", "Matteo Kovačić", "M. Kovačić", "Rico Lewis", "R. Lewis",
    "Lisandro Martínez", "L. Martínez", "Matthijs de Ligt", "M. de Ligt", "Leny Yoro", "L. Yoro", "Kobbie Mainoo", "K. Mainoo", "Alejandro Garnacho", "A. Garnacho", "Amad Diallo", "A. Diallo", "Marcus Rashford", "M. Rashford", "Rasmus Højlund", "R. Højlund", "Joshua Zirkzee", "J. Zirkzee", "Diogo Dalot", "D. Dalot", "Noussair Mazraoui", "N. Mazraoui", "Manuel Ugarte", "M. Ugarte",
    "Sandro Tonali", "S. Tonali", "Joelinton", "Jelinton", "Fabian Schär", "F. Schär", "Lewis Hall", "L. Hall", "Tino Livramento", "T. Livramento", "Nick Pope", "N. Pope", "Harvey Barnes", "H. Barnes",
    "Murillo", "Nikola Milenković", "N. Milenković", "Morgan Gibbs-White", "M. Gibbs-White", "Callum Hudson-Odoi", "C. Hudson-Odoi", "Anthony Elanga", "A. Elanga", "Chris Wood", "C. Wood", "Ola Aina", "O. Aina",
    "Aaron Ramsdale", "A. Ramsdale", "Taylor Harwood-Bellis", "T. Harwood-Bellis", "Yukinari Sugawara", "R. Sugawara", "Tyler Dibling", "T. Dibling", "Mateus Fernandes", "M. Fernandes",
    "Micky van de Ven", "M. van de Ven", "Destiny Udogie", "D. Udogie", "Pedro Porro", "P. Porro", "James Maddison", "J. Maddison", "Dejan Kulusevski", "D. Kulusevski", "Brennan Johnson", "B. Johnson", "Dominic Solanke", "D. Solanke", "Pape Matar Sarr", "P. Sarr", "Lucas Bergvall", "L. Bergvall", "Archie Gray", "D. Gray",
    "Jean-Clair Todibo", "J. Todibo", "Max Kilman", "M. Kilman", "Emerson Palmieri", "E. Palmieri", "Edson Álvarez", "E. Alvarez", "Lucas Paquetá", "L. Paquetá", "Mohammed Kudus", "M. Kudus", "Crysencio Summerville", "C. Summerville", "Niclas Füllkrug", "N. Füllkrug",
    "Rayan Aït-Nouri", "R. Aït-Nouri", "André", "A. André", "Mario Lemina", "M. Lemina", "Jørgen Strand Larsen", "J. Larsen", "Hwang Hee-Chan", "H. Hwang"
  ])
};

const plDir = path.join(__dirname, '..', 'data', 'players', 'active', 'premier-league');
const files = fs.readdirSync(plDir).filter(f => f.endsWith('.json'));

let totalPlayersProcessed = 0;
let totalKitNumberFixes = 0;
let totalNationFixes = 0;

files.forEach(file => {
  const filePath = path.join(plDir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const clubName = data.club.name;

  const usedKitNumbers = new Set();
  let nextAvailableKit = 40; // For academy/youth fallback assignment

  data.players.forEach(p => {
    totalPlayersProcessed++;

    // 1. Correct Real International Nation
    if (REAL_PL_NATIONS[p.name]) {
      if (p.nation !== REAL_PL_NATIONS[p.name]) {
        p.nation = REAL_PL_NATIONS[p.name];
        totalNationFixes++;
      }
    }

    // 2. Honest & Accurate Tiering
    if (HONEST_PL_TIERS.MASTER.has(p.name)) p.tier = "MASTER";
    else if (HONEST_PL_TIERS.ELITE_PLUS.has(p.name)) p.tier = "ELITE_PLUS";
    else if (HONEST_PL_TIERS.ELITE.has(p.name)) p.tier = "ELITE";
    else {
      // If kit number is high (>35) or prospect name, default to SILVER or BRONZE
      if (p.kitNumber && p.kitNumber > 45) p.tier = p.tier === "GOLD" ? "SILVER" : (p.tier || "BRONZE");
      else if (!p.tier || p.tier === "") p.tier = "GOLD";
    }

    // 3. Unique Kit Numbers per Club
    if (!p.kitNumber || usedKitNumbers.has(p.kitNumber)) {
      // Assign next available unique kit number
      while (usedKitNumbers.has(nextAvailableKit)) {
        nextAvailableKit++;
      }
      p.kitNumber = nextAvailableKit;
      usedKitNumbers.add(nextAvailableKit);
      totalKitNumberFixes++;
    } else {
      usedKitNumbers.add(p.kitNumber);
    }
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Updated ${clubName} (${file}): ${data.players.length} players processed, kit numbers deduplicated.`);
});

console.log(`\n🎉 Premier League Rebuild Complete!`);
console.log(`   Total Players Processed: ${totalPlayersProcessed}`);
console.log(`   Nations Corrected: ${totalNationFixes}`);
console.log(`   Kit Numbers Deduplicated: ${totalKitNumberFixes}`);
