const fs = require('fs');
const path = require('path');

const COMPLETE_NATION_MAP = {
  // Goalkeepers & Defenders
  "I. Meslier": "France",
  "J. Porter": "England",
  "K. Ranson": "England",
  "P. Hincapié": "Ecuador",
  "Cristhian Mosquera": "Spain",
  "Jaden Dixon": "England",
  "M. Salmon": "England",
  "J. Gauci": "Australia",
  "R. Olsen": "Sweden",
  "S. Proctor": "England",
  "L. Bogarde": "Netherlands",
  "K. Hause": "England",
  "I. Maatsen": "Netherlands",
  "T. Mings": "England",
  "E. Konsa": "England",
  "P. Torres": "Spain",
  "K. Kosta": "England",
  "W. Dennis": "England",
  "D. Huijsen": "Spain",
  "J. Araujo": "Mexico",
  "I. Zabarnyi": "Ukraine",
  "M. Senesi": "Argentina",
  "M. Kerkez": "Hungary",
  "A. Smith": "England",
  "J. Hill": "England",
  "M. Aarons": "England",
  "H. Valdimarsson": "Iceland",
  "L. Ji-Soo": "South Korea",
  "S. van den Berg": "Netherlands",
  "E. Pinnock": "Jamaica",
  "N. Collins": "Ireland",
  "K. Ajer": "Norway",
  "R. Henry": "England",
  "A. Hickey": "Scotland",
  "M. Roerslev": "Denmark",
  "J. Steele": "England",
  "C. Rushworth": "England",
  "I. Igor": "Brazil",
  "J. van Hecke": "Netherlands",
  "A. Webster": "England",
  "T. Lamptey": "Ghana",
  "P. Estupiñán": "Ecuador",
  "F. Kadioglu": "Turkey",
  "F. Jørgensen": "Denmark",
  "M. Penders": "Belgium",
  "L. Colwill": "England",
  "B. Badiashile": "France",
  "A. Disasi": "France",
  "T. Adarabioyo": "England",
  "W. Fofana": "France",
  "M. Cucurella": "Spain",
  "B. Chilwell": "England",
  "R. James": "England",
  "M. Gusto": "France",
  "V. Jaros": "Czech Republic",
  "C. Kelleher": "Ireland",
  "I. Konaté": "France",
  "J. Quansah": "England",
  "J. Gomez": "England",
  "A. Robertson": "Scotland",
  "K. Tsimikas": "Greece",
  "C. Bradley": "Northern Ireland",
  "S. Ortega": "Germany",
  "N. Athanasiou": "Greece",
  "N. Aké": "Netherlands",
  "M. Akanji": "Switzerland",
  "Rúben Dias": "Portugal",
  "J. Gvardiol": "Croatia",
  "J. Stones": "England",
  "R. Lewis": "England",
  "A. Bayındır": "Turkey",
  "K. Darlow": "England",
  "S. Lammens": "Belgium",
  "P. Dorgu": "Denmark",
  "L. Yoro": "France",
  "M. de Ligt": "Netherlands",
  "L. Martínez": "Argentina",
  "H. Maguire": "England",
  "V. Lindelöf": "Sweden",
  "J. Evans": "Northern Ireland",
  "N. Mazraoui": "Morocco",
  "T. Malacia": "Netherlands",
  "L. Shaw": "England",
  "O. Vlachodimos": "Greece",
  "M. Gillespie": "Northern Ireland",
  "A. Ramsdale": "England",
  "Max Thompson": "England",
  "L. Hall": "England",
  "S. Botman": "Netherlands",
  "L. Kelly": "England",
  "F. Schär": "Switzerland",
  "J. Lascelles": "England",
  "E. Krafth": "Sweden",
  "T. Livramento": "England",
  "M. Thiaw": "Germany",
  "F. Forster": "England",
  "M. Dúbravka": "Slovakia",
  "A. Phillips": "England",
  "R. Drăgușin": "Romania",
  "M. van de Ven": "Netherlands",
  "C. Romero": "Argentina",
  "B. Davies": "Wales",
  "D. Udogie": "Italy",
  "S. Reguilón": "Spain",
  "P. Porro": "Spain",
  "D. Spence": "England",
  "M. Hermansen": "Denmark",
  "R. Battrum": "England",
  "K. Casey": "England",
  "E. Diouf": "Senegal",
  "A. Golambeckis": "Lithuania",
  "E. Mayers": "England",
  "K. Walker-Peters": "England",
  "J. Gracey": "Northern Ireland",
  "L. Krejčí": "Czech Republic",
  "S. Olagunju": "England",
  "K. Trippier": "England",
  "D. Møller Wolfe": "Norway",
  "G. Long": "Ireland",
  "Daniel Peretz": "Israel",
  "T. Dobson-Ventura": "England",
  "J. Quarshie": "Germany",
  "J. Byfield": "England",
  "M. Hardy": "England",
  "James Rowswell": "England",
  "Souza": "Brazil",
  "K. Takai": "Japan",
  "John": "Brazil",
  "Keehan Willows": "England",
  "Jair": "Brazil",
  "B. Hammond": "England",
  "Justin Thomas Hanks": "England",
  "L. Netz": "Germany",
  "J. Sinclair": "England",
  "Jack Ethan Thompson": "England",
  "L. Shahar": "England",

  // Midfielders
  "E. Eze": "England",
  "Martín Zubimendi": "Spain",
  "C. Nørgaard": "Denmark",
  "I. Ibrahim": "England",
  "M. Dowman": "England",
  "L. Bailey": "Jamaica",
  "E. Buendía": "Argentina",
  "R. Barkley": "England",
  "J. McGinn": "Scotland",
  "Y. Tielemans": "Belgium",
  "A. Onana": "Belgium",
  "J. Ramsey": "England",
  "M. Rogers": "England",
  "T. Adams": "USA",
  "L. Cook": "England",
  "R. Christie": "Scotland",
  "A. Scott": "England",
  "P. Billing": "Denmark",
  "Marcus Tavernier": "England",
  "M. Jensen": "Denmark",
  "V. Janelt": "Germany",
  "Y. Konak": "Turkey",
  "F. Carvalho": "Portugal",
  "M. Damsgaard": "Denmark",
  "M. Wieffer": "Netherlands",
  "Y. Ayari": "Sweden",
  "C. Baleba": "Cameroon",
  "J. Moder": "Poland",
  "J. Enciso": "Paraguay",
  "R. Lavia": "Belgium",
  "M. Caicedo": "Ecuador",
  "E. Fernández": "Argentina",
  "K. Dewsbury-Hall": "England",
  "C. Palmer": "England",
  "W. Endo": "Japan",
  "R. Gravenberch": "Netherlands",
  "A. Mac Allister": "Argentina",
  "D. Szoboszlai": "Hungary",
  "C. Jones": "England",
  "H. Elliott": "England",
  "M. Kovacic": "Croatia",
  "Matheus Nunes": "Portugal",
  "B. Silva": "Portugal",
  "J. McAtee": "England",
  "M. Ugarte": "Uruguay",
  "Casemiro": "Brazil",
  "K. Mainoo": "England",
  "C. Eriksen": "Denmark",
  "Mason Mount": "England",
  "Bruno Fernandes": "Portugal",
  "S. Longstaff": "England",
  "J. Willock": "England",
  "L. Miley": "England",
  "Bruno Guimarães": "Brazil",
  "Joelinton": "Brazil",
  "S. Tonali": "Italy",
  "J. Murphy": "England",
  "A. Gray": "England",
  "L. Bergvall": "Sweden",
  "P. Sarr": "Senegal",
  "Y. Bissouma": "Mali",
  "R. Bentancur": "Uruguay",
  "J. Maddison": "England",
  "P. Fearon": "England",
  "K. Lamadrid": "England",
  "S. Magassa": "France",
  "T. Edozie": "England",
  "Fer López": "Spain",
  "L. Rawlings": "England",
  "F. Azaz": "Ireland",
  "Cameron Bragg": "England",
  "T. Fellows": "England",
  "C. Jander": "Germany",
  "K. Matsuki": "Japan",
  "J. O&apos;Brien-Whitmarsh": "Ireland",
  "M. Sesay": "England",
  "B. Williams": "England",
  "D. Ajayi": "England",
  "Mateus Fernandes": "Portugal",
  "C. Gallagher": "England",
  "T. Hall": "England",
  "C. Olusesi": "England",
  "X. Simons": "Netherlands",
  "S. Neave": "England",
  "Park Seung-Soo": "South Korea",
  "Sean Steur": "Netherlands",
  "B. Touré": "Ivory Coast",
  "G. McDonnell": "Ireland",
  "X. Schlager": "Austria",
  "A. Whitehall": "England",

  // Attackers / Strikers
  "B. Bailey-Joseph": "England",
  "Gabriel Jesus": "Brazil",
  "V. Gyökeres": "Sweden",
  "A. Annous": "England",
  "N. Madueke": "England",
  "Gabriel Martinelli": "Brazil",
  "C. Tzolis": "Greece",
  "O. Watkins": "England",
  "J. Duran": "Colombia",
  "J. Kluivert": "Netherlands",
  "A. Semenyo": "Ghana",
  "E. Unal": "Turkey",
  "D. Ouattara": "Burkina Faso",
  "B. Mbeumo": "Cameroon",
  "Y. Wissa": "DR Congo",
  "I. Thiago": "Brazil",
  "K. Schade": "Germany",
  "G. Rutter": "France",
  "Y. Minteh": "Gambia",
  "S. Adingra": "Ivory Coast",
  "E. Ferguson": "Ireland",
  "Joao Pedro": "Brazil",
  "D. Welbeck": "England",
  "P. Neto": "Portugal",
  "J. Félix": "Portugal",
  "J. Sancho": "England",
  "M. Mudryk": "Ukraine",
  "N. Jackson": "Senegal",
  "C. Nkunku": "France",
  "F. Chiesa": "Italy",
  "C. Gakpo": "Netherlands",
  "L. Díaz": "Colombia",
  "D. Núñez": "Uruguay",
  "Diogo Jota": "Portugal",
  "Savinho": "Brazil",
  "J. Doku": "Belgium",
  "O. Bobb": "Norway",
  "E. Haaland": "Norway",
  "A. Diallo": "Ivory Coast",
  "Antony": "Brazil",
  "A. Garnacho": "Argentina",
  "M. Rashford": "England",
  "R. Højlund": "Denmark",
  "J. Zirkzee": "Netherlands",
  "M. Almirón": "Paraguay",
  "H. Barnes": "England",
  "A. Gordon": "England",
  "A. Isak": "Sweden",
  "C. Wilson": "England",
  "W. Osula": "Denmark",
  "A. Elanga": "Sweden",
  "N. Woltemade": "Germany",
  "D. Kulusevski": "Sweden",
  "B. Johnson": "Wales",
  "W. Odobert": "France",
  "T. Werner": "Germany",
  "Son Heung-Min": "South Korea",
  "Richarlison": "Brazil",
  "D. Solanke": "England",
  "J. Donley": "England",
  "M. Melia": "Ireland",
  "M. Moore": "England",
  "L. Williams-Barnett": "England",
  "Yang Min-Hyeok": "South Korea",
  "J. Ajala": "England",
  "V. Castellanos": "Argentina",
  "Pablo": "Brazil",
  "A. Armstrong": "England",
  "T. Arokodare": "Nigeria",
  "R. Jiménez": "Mexico",
  "R. Saïd": "France",
  "Ethan Sutherland": "Scotland",
  "J. Tchatchoua": "Cameroon",
  "C. Larin": "Canada",
  "N. Oyekunle": "England",
  "Léo Scienza": "Brazil",
  "D. Bakwa": "France",
  "Z. Blake": "England",
  "O. Hutchinson": "Jamaica",
  "Igor Jesus": "Brazil",
  "A. Kalimuendo": "France",
  "D. Ndoye": "Switzerland",
  "L. Sillah": "Gambia"
};

function applyCompleteNations() {
  const dir = path.join(__dirname, '..', 'data', 'players', 'active', 'premier-league');
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));

  let totalUpdated = 0;
  let remainingUnknown = 0;

  for (const file of files) {
    const filePath = path.join(dir, file);
    const content = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    let updatedInFile = 0;

    for (const p of content.players) {
      if (!p.nation || p.nation === 'Unknown') {
        if (COMPLETE_NATION_MAP[p.name]) {
          p.nation = COMPLETE_NATION_MAP[p.name];
          updatedInFile++;
          totalUpdated++;
        } else {
          // If name has initials or small variation, clean & match
          const cleanName = p.name.replace(/[^a-zA-Z\s]/g, '').trim();
          for (const [key, nat] of Object.entries(COMPLETE_NATION_MAP)) {
            if (key.toLowerCase() === cleanName.toLowerCase()) {
              p.nation = nat;
              updatedInFile++;
              totalUpdated++;
              break;
            }
          }
        }
      }

      if (!p.nation || p.nation === 'Unknown') {
        remainingUnknown++;
        console.log(`[Remaining Unknown] ${content.club.name}: ${p.name} (${p.position})`);
      }
    }

    if (updatedInFile > 0) {
      fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
      console.log(`✅ Updated ${updatedInFile} player nations in ${file}`);
    }
  }

  console.log(`\n🎉 Total nations resolved in this pass: ${totalUpdated}`);
  console.log(`❓ Remaining unknown players: ${remainingUnknown}`);
}

applyCompleteNations();
