const fs = require('fs');
const path = require('path');

// Complete Real-World Nationality Database for Serie A & Bundesliga
const REAL_NATIONS = {
  // SERIE A
  // AC Milan
  "M. Maignan": "France",
  "Mike Maignan": "France",
  "M. Sportiello": "Italy",
  "L. Torriani": "Italy",
  "Theo Hernández": "France",
  "T. Hernández": "France",
  "F. Tomori": "England",
  "Fikayo Tomori": "England",
  "S. Pavlović": "Serbia",
  "Strahinja Pavlović": "Serbia",
  "M. Thiaw": "Germany",
  "Malick Thiaw": "Germany",
  "P. Kalulu": "France",
  "E. Royal": "Brazil",
  "Emerson Royal": "Brazil",
  "D. Calabria": "Italy",
  "A. Florenzi": "Italy",
  "F. Terracciano": "Italy",
  "T. Reijnders": "Netherlands",
  "Tijjani Reijnders": "Netherlands",
  "Y. Fofana": "France",
  "Youssouf Fofana": "France",
  "I. Bennacer": "Algeria",
  "Ismaël Bennacer": "Algeria",
  "R. Loftus-Cheek": "England",
  "Ruben Loftus-Cheek": "England",
  "Y. Musah": "USA",
  "Yunus Musah": "USA",
  "C. Pulisic": "USA",
  "Christian Pulisic": "USA",
  "Rafael Leão": "Portugal",
  "R. Leão": "Portugal",
  "S. Chukwueze": "Nigeria",
  "Samuel Chukwueze": "Nigeria",
  "N. Okafor": "Switzerland",
  "Noah Okafor": "Switzerland",
  "Á. Morata": "Spain",
  "Álvaro Morata": "Spain",
  "L. Jović": "Serbia",
  "Luka Jović": "Serbia",
  "F. Camarda": "Italy",

  // Inter Milan
  "Y. Sommer": "Switzerland",
  "Yann Sommer": "Switzerland",
  "J. Martínez": "Spain",
  "R. Di Gennaro": "Italy",
  "A. Bastoni": "Italy",
  "Alessandro Bastoni": "Italy",
  "B. Pavard": "France",
  "Benjamin Pavard": "France",
  "S. de Vrij": "Netherlands",
  "Stefan de Vrij": "Netherlands",
  "F. Acerbi": "Italy",
  "Y. Bisseck": "Germany",
  "Yann Bisseck": "Germany",
  "F. Dimarco": "Italy",
  "Federico Dimarco": "Italy",
  "D. Dumfries": "Netherlands",
  "Denzel Dumfries": "Netherlands",
  "M. Darmian": "Italy",
  "C. Augusto": "Brazil",
  "Carlos Augusto": "Brazil",
  "T. Buchanan": "Canada",
  "N. Barella": "Italy",
  "Nicolò Barella": "Italy",
  "H. Çalhanoğlu": "Turkey",
  "Hakan Çalhanoğlu": "Turkey",
  "H. Mkhitaryan": "Armenia",
  "Henrikh Mkhitaryan": "Armenia",
  "P. Zieliński": "Poland",
  "Piotr Zieliński": "Poland",
  "K. Asllani": "Albania",
  "Kristjan Asllani": "Albania",
  "D. Frattesi": "Italy",
  "Davide Frattesi": "Italy",
  "Lautaro Martínez": "Argentina",
  "L. Martínez": "Argentina",
  "M. Thuram": "France",
  "Marcus Thuram": "France",
  "M. Taremi": "Iran",
  "Mehdi Taremi": "Iran",
  "M. Arnautović": "Austria",
  "Marko Arnautović": "Austria",
  "J. Correa": "Argentina",

  // Juventus
  "M. Di Gregorio": "Italy",
  "M. Perin": "Italy",
  "C. Pinsoglio": "Italy",
  "Bremer": "Brazil",
  "G. Bremer": "Brazil",
  "F. Gatti": "Italy",
  "Federico Gatti": "Italy",
  "P. Kalulu": "France",
  "Pierre Kalulu": "France",
  "J. Cabal": "Colombia",
  "Juan Cabal": "Colombia",
  "Danilo": "Brazil",
  "N. Savona": "Italy",
  "A. Cambiaso": "Italy",
  "Andrea Cambiaso": "Italy",
  "T. Koopmeiners": "Netherlands",
  "Teun Koopmeiners": "Netherlands",
  "Douglas Luiz": "Brazil",
  "K. Thuram": "France",
  "Khéphren Thuram": "France",
  "M. Locatelli": "Italy",
  "Manuel Locatelli": "Italy",
  "W. McKennie": "USA",
  "Weston McKennie": "USA",
  "N. Fagioli": "Italy",
  "Nicolò Fagioli": "Italy",
  "V. Adžić": "Montenegro",
  "Vasilije Adžić": "Montenegro",
  "K. Yildiz": "Turkey",
  "Kenan Yıldız": "Turkey",
  "F. Conceição": "Portugal",
  "Francisco Conceição": "Portugal",
  "N. González": "Argentina",
  "Nicolas González": "Argentina",
  "T. Weah": "USA",
  "Timothy Weah": "USA",
  "S. Mbangula": "Belgium",
  "D. Vlahović": "Serbia",
  "Dušan Vlahović": "Serbia",
  "A. Milik": "Poland",

  // Napoli
  "A. Meret": "Italy",
  "Alex Meret": "Italy",
  "E. Caprile": "Italy",
  "A. Rrahmani": "Kosovo",
  "Amir Rrahmani": "Kosovo",
  "A. Buongiorno": "Italy",
  "Alessandro Buongiorno": "Italy",
  "Rafa Marín": "Spain",
  "Juan Jesus": "Brazil",
  "M. Olivera": "Uruguay",
  "Mathías Olivera": "Uruguay",
  "L. Spinazzola": "Italy",
  "Leonardo Spinazzola": "Italy",
  "G. Di Lorenzo": "Italy",
  "Giovanni Di Lorenzo": "Italy",
  "P. Mazzocchi": "Italy",
  "S. Lobotka": "Slovakia",
  "Stanislav Lobotka": "Slovakia",
  "A. Zambo Anguissa": "Cameroon",
  "Frank Anguissa": "Cameroon",
  "S. McTominay": "Scotland",
  "Scott McTominay": "Scotland",
  "B. Gilmour": "Scotland",
  "Billy Gilmour": "Scotland",
  "M. Folorunsho": "Italy",
  "Khvicha Kvaratskhelia": "Georgia",
  "K. Kvaratskhelia": "Georgia",
  "David Neres": "Brazil",
  "M. Politano": "Italy",
  "Matteo Politano": "Italy",
  "C. Ngonge": "Belgium",
  "Cyril Ngonge": "Belgium",
  "G. Raspadori": "Italy",
  "Giacomo Raspadori": "Italy",
  "G. Simeone": "Argentina",
  "Giovanni Simeone": "Argentina",
  "R. Lukaku": "Belgium",
  "Romelu Lukaku": "Belgium",

  // Atalanta
  "M. Carnesecchi": "Italy",
  "R. Patricio": "Portugal",
  "Rui Patrício": "Portugal",
  "F. Rossi": "Italy",
  "G. Scalvini": "Italy",
  "Giorgio Scalvini": "Italy",
  "B. Djimsiti": "Albania",
  "Berat Djimsiti": "Albania",
  "I. Hien": "Sweden",
  "Isak Hien": "Sweden",
  "S. Kolasinac": "Bosnia",
  "Sead Kolašinac": "Bosnia",
  "B. Godfrey": "England",
  "Ben Godfrey": "England",
  "R. Tolói": "Italy",
  "M. Ruggeri": "Italy",
  "Matteo Ruggeri": "Italy",
  "D. Zappacosta": "Italy",
  "R. Bellanova": "Italy",
  "Raoul Bellanova": "Italy",
  "Éderson": "Brazil",
  "M. de Roon": "Netherlands",
  "Marten de Roon": "Netherlands",
  "M. Pašalić": "Croatia",
  "Mario Pašalić": "Croatia",
  "L. Samardžić": "Serbia",
  "Lazar Samardžić": "Serbia",
  "M. Brescianini": "Italy",
  "I. Sulemana": "Ghana",
  "Ibrahim Sulemana": "Ghana",
  "A. Lookman": "Nigeria",
  "Ademola Lookman": "Nigeria",
  "C. De Ketelaere": "Belgium",
  "Charles De Ketelaere": "Belgium",
  "N. Zaniolo": "Italy",
  "Nicolò Zaniolo": "Italy",
  "G. Scamacca": "Italy",
  "Gianluca Scamacca": "Italy",
  "M. Retegui": "Italy",
  "Mateo Retegui": "Italy",

  // AS Roma
  "M. Svilar": "Serbia",
  "Mile Svilar": "Serbia",
  "M. Ryan": "Australia",
  "Matthew Ryan": "Australia",
  "G. Mancini": "Italy",
  "Gianluca Mancini": "Italy",
  "E. Ndicka": "Ivory Coast",
  "Evan Ndicka": "Ivory Coast",
  "M. Hermoso": "Spain",
  "Mario Hermoso": "Spain",
  "M. Hummels": "Germany",
  "Mats Hummels": "Germany",
  "A. Saelemaekers": "Belgium",
  "Alexis Saelemaekers": "Belgium",
  "Angelino": "Spain",
  "Angeliño": "Spain",
  "Z. Celik": "Turkey",
  "Zeki Çelik": "Turkey",
  "B. Cristante": "Italy",
  "Bryan Cristante": "Italy",
  "L. Pellegrini": "Italy",
  "Lorenzo Pellegrini": "Italy",
  "L. Paredes": "Argentina",
  "Leandro Paredes": "Argentina",
  "M. Koné": "France",
  "Manu Koné": "France",
  "E. Le Fée": "France",
  "Enzo Le Fée": "France",
  "N. Pisilli": "Italy",
  "Niccolò Pisilli": "Italy",
  "T. Baldanzi": "Italy",
  "Tommaso Baldanzi": "Italy",
  "P. Dybala": "Argentina",
  "Paulo Dybala": "Argentina",
  "M. Soulé": "Argentina",
  "Matías Soulé": "Argentina",
  "S. El Shaarawy": "Italy",
  "Stephan El Shaarawy": "Italy",
  "A. Dovbyk": "Ukraine",
  "Artem Dovbyk": "Ukraine",
  "E. Shomurodov": "Uzbekistan",

  // Lazio
  "I. Provedel": "Italy",
  "Ivan Provedel": "Italy",
  "C. Mandas": "Greece",
  "Christos Mandas": "Greece",
  "A. Romagnoli": "Italy",
  "Alessio Romagnoli": "Italy",
  "M. Gila": "Spain",
  "Mario Gila": "Spain",
  "N. Casale": "Italy",
  "S. Gigot": "France",
  "Samuel Gigot": "France",
  "N. Tavares": "Portugal",
  "Nuno Tavares": "Portugal",
  "L. Pellegrini": "Italy",
  "Lazzari": "Italy",
  "M. Lazzari": "Italy",
  "M. Guendouzi": "France",
  "Mattéo Guendouzi": "France",
  "N. Rovella": "Italy",
  "Nicolò Rovella": "Italy",
  "G. Castrovilli": "Italy",
  "M. Vecino": "Uruguay",
  "Matías Vecino": "Uruguay",
  "F. Dele-Bashiru": "Nigeria",
  "Fisayo Dele-Bashiru": "Nigeria",
  "L. Tchaouna": "France",
  "Loum Tchaouna": "France",
  "G. Isaksen": "Denmark",
  "Gustav Isaksen": "Denmark",
  "Mattia Zaccagni": "Italy",
  "M. Zaccagni": "Italy",
  "T. Noslin": "Netherlands",
  "Tijjani Noslin": "Netherlands",
  "V. Castellanos": "Argentina",
  "Valentín Castellanos": "Argentina",
  "B. Dia": "Senegal",
  "Boulaye Dia": "Senegal",

  // Bologna
  "L. Skorupski": "Poland",
  "Łukasz Skorupski": "Poland",
  "F. Ravaglia": "Italy",
  "S. Beukema": "Netherlands",
  "Sam Beukema": "Netherlands",
  "J. Lucumí": "Colombia",
  "Jhon Lucumí": "Colombia",
  "N. Casale": "Italy",
  "E. Erlić": "Croatia",
  "Martin Erlić": "Croatia",
  "M. Miranda": "Spain",
  "Juan Miranda": "Spain",
  "C. Lykogiannis": "Greece",
  "S. Posch": "Austria",
  "Stefan Posch": "Austria",
  "E. Holm": "Sweden",
  "Emil Holm": "Sweden",
  "R. Freuler": "Switzerland",
  "Remo Freuler": "Switzerland",
  "M. Aebischer": "Switzerland",
  "Michel Aebischer": "Switzerland",
  "G. Moro": "Croatia",
  "Nikola Moro": "Croatia",
  "G. Fabbian": "Italy",
  "Giovanni Fabbian": "Italy",
  "K. Urbański": "Poland",
  "Kacper Urbański": "Poland",
  "T. Pobega": "Italy",
  "Tommaso Pobega": "Italy",
  "O. El Azzouzi": "Morocco",
  "D. Ndoye": "Switzerland",
  "Dan Ndoye": "Switzerland",
  "J. Karlsson": "Sweden",
  "Jesper Karlsson": "Sweden",
  "B. Domínguez": "Argentina",
  "Benjamin Domínguez": "Argentina",
  "N. Cambiaghi": "Italy",
  "Nicolò Cambiaghi": "Italy",
  "T. Dallinga": "Netherlands",
  "Thijs Dallinga": "Netherlands",
  "S. Castro": "Argentina",
  "Santiago Castro": "Argentina",

  // Fiorentina
  "D. de Gea": "Spain",
  "David de Gea": "Spain",
  "P. Terracciano": "Italy",
  "L. Ranieri": "Italy",
  "Luca Ranieri": "Italy",
  "L. Martínez Quarta": "Argentina",
  "Lucas Martínez Quarta": "Argentina",
  "M. Pongračić": "Croatia",
  "Marin Pongračić": "Croatia",
  "P. Comuzzo": "Italy",
  "Pietro Comuzzo": "Italy",
  "R. Gosens": "Germany",
  "Robin Gosens": "Germany",
  "F. Parisi": "Italy",
  "D. Dodô": "Brazil",
  "Dodô": "Brazil",
  "M. Kayode": "Italy",
  "Michael Kayode": "Italy",
  "D. Cataldi": "Italy",
  "Danilo Cataldi": "Italy",
  "Y. Adli": "France",
  "Yacine Adli": "France",
  "E. Bove": "Italy",
  "Edoardo Bove": "Italy",
  "R. Mandragora": "Italy",
  "Rolando Mandragora": "Italy",
  "A. Richardson": "Morocco",
  "Amir Richardson": "Morocco",
  "A. Gudmundsson": "Iceland",
  "Albert Guðmundsson": "Iceland",
  "A. Colpani": "Italy",
  "Andrea Colpani": "Italy",
  "J. Ikoné": "France",
  "Jonathan Ikoné": "France",
  "C. Kouamé": "Ivory Coast",
  "Christian Kouamé": "Ivory Coast",
  "M. Kean": "Italy",
  "Moise Kean": "Italy",
  "L. Beltrán": "Argentina",
  "Lucas Beltrán": "Argentina",

  // Genoa
  "P. Gollini": "Italy",
  "Pierluigi Gollini": "Italy",
  "N. Leali": "Italy",
  "J. Vásquez": "Mexico",
  "Johan Vásquez": "Mexico",
  "M. Bani": "Italy",
  "Mattia Bani": "Italy",
  "A. Vogliacco": "Italy",
  "K. De Winter": "Belgium",
  "Koni De Winter": "Belgium",
  "A. Martín": "Spain",
  "Aaron Martín": "Spain",
  "S. Sabelli": "Italy",
  "Stefano Sabelli": "Italy",
  "A. Zanoli": "Italy",
  "Alessandro Zanoli": "Italy",
  "M. Badelj": "Croatia",
  "Milan Badelj": "Croatia",
  "M. Frendrup": "Denmark",
  "Morten Frendrup": "Denmark",
  "F. Miretti": "Italy",
  "Fabio Miretti": "Italy",
  "R. Malinovskyi": "Ukraine",
  "Ruslan Malinovskyi": "Ukraine",
  "E. Bohinen": "Norway",
  "Emil Bohinen": "Norway",
  "J. Messias": "Brazil",
  "Junior Messias": "Brazil",
  "V. Vitinha": "Portugal",
  "Vitinha": "Portugal",
  "C. Ekuban": "Ghana",
  "Caleb Ekuban": "Ghana",
  "A. Pinamonti": "Italy",
  "Andrea Pinamonti": "Italy",
  "M. Balotelli": "Italy",
  "Mario Balotelli": "Italy",

  // Torino
  "V. Milinković-Savić": "Serbia",
  "Vanja Milinković-Savić": "Serbia",
  "A. Donnarumma": "Italy",
  "S. Coco": "Equatorial Guinea",
  "Saúl Coco": "Equatorial Guinea",
  "G. Maripán": "Chile",
  "Guillermo Maripán": "Chile",
  "P. Schuurs": "Netherlands",
  "Perr Schuurs": "Netherlands",
  "S. Walukiewicz": "Poland",
  "Sebastian Walukiewicz": "Poland",
  "B. Sosa": "Croatia",
  "Borna Sosa": "Croatia",
  "M. Vojvoda": "Kosovo",
  "Mergim Vojvoda": "Kosovo",
  "M. Pedersen": "Norway",
  "Marcus Pedersen": "Norway",
  "S. Ricci": "Italy",
  "Samuele Ricci": "Italy",
  "I. Ilić": "Serbia",
  "Ivan Ilić": "Serbia",
  "K. Linetty": "Poland",
  "Karol Linetty": "Poland",
  "G. Gineitis": "Lithuania",
  "Gvidas Gineitis": "Lithuania",
  "N. Vlašić": "Croatia",
  "Nikola Vlašić": "Croatia",
  "Y. Karamoh": "France",
  "Yann Karamoh": "France",
  "D. Zapata": "Colombia",
  "Duván Zapata": "Colombia",
  "A. Sanabria": "Paraguay",
  "Antonio Sanabria": "Paraguay",
  "C. Adams": "Scotland",
  "Ché Adams": "Scotland",

  // Udinese
  "M. Okoye": "Nigeria",
  "Maduka Okoye": "Nigeria",
  "D. Padelli": "Italy",
  "J. Bijol": "Slovenia",
  "Jaka Bijol": "Slovenia",
  "O. Solet": "France",
  "Oumar Solet": "France",
  "T. Kristensen": "Denmark",
  "Thomas Kristensen": "Denmark",
  "L. Giannetti": "Argentina",
  "Lautaro Giannetti": "Argentina",
  "H. Kamara": "Ivory Coast",
  "Hassane Kamara": "Ivory Coast",
  "K. Ehizibue": "Nigeria",
  "Kingsley Ehizibue": "Nigeria",
  "J. Zemura": "Zimbabwe",
  "Jordan Zemura": "Zimbabwe",
  "J. Karlström": "Sweden",
  "Jesper Karlström": "Sweden",
  "S. Lovrić": "Slovenia",
  "Sandi Lovrić": "Slovenia",
  "M. Payero": "Argentina",
  "Martín Payero": "Argentina",
  "O. Zarraga": "Spain",
  "Oier Zarraga": "Spain",
  "J. Ekkelenkamp": "Netherlands",
  "Jurgen Ekkelenkamp": "Netherlands",
  "F. Thauvin": "France",
  "Florian Thauvin": "France",
  "B. Brenner": "Brazil",
  "Brenner": "Brazil",
  "L. Lucca": "Italy",
  "Lorenzo Lucca": "Italy",
  "Keinan Davis": "England",
  "K. Davis": "England",

  // BUNDESLIGA
  // Bayern Munich
  "M. Neuer": "Germany",
  "Manuel Neuer": "Germany",
  "D. Peretz": "Israel",
  "Daniel Peretz": "Israel",
  "S. Ulreich": "Germany",
  "D. Upamecano": "France",
  "Dayot Upamecano": "France",
  "Kim Min-jae": "South Korea",
  "Min-jae Kim": "South Korea",
  "H. Ito": "Japan",
  "Hiroki Ito": "Japan",
  "E. Dier": "England",
  "Eric Dier": "England",
  "T. Davies": "Canada",
  "Alphonso Davies": "Canada",
  "R. Guerreiro": "Portugal",
  "Raphaël Guerreiro": "Portugal",
  "S. Boey": "France",
  "Sacha Boey": "France",
  "J. Stanisic": "Croatia",
  "Josip Stanišić": "Croatia",
  "J. Kimmich": "Germany",
  "Joshua Kimmich": "Germany",
  "L. Goretzka": "Germany",
  "Leon Goretzka": "Germany",
  "J. Musiala": "Germany",
  "Jamal Musiala": "Germany",
  "J. Palhinha": "Portugal",
  "João Palhinha": "Portugal",
  "K. Laimer": "Austria",
  "Konrad Laimer": "Austria",
  "A. Pavlovic": "Germany",
  "Aleksandar Pavlović": "Germany",
  "M. Olise": "France",
  "Michael Olise": "France",
  "L. Sané": "Germany",
  "Leroy Sané": "Germany",
  "K. Coman": "France",
  "Kingsley Coman": "France",
  "S. Gnabry": "Germany",
  "Serge Gnabry": "Germany",
  "M. Tel": "France",
  "Mathys Tel": "France",
  "T. Müller": "Germany",
  "Thomas Müller": "Germany",
  "H. Kane": "England",
  "Harry Kane": "England",

  // Bayer Leverkusen
  "L. Hradecky": "Finland",
  "Lukas Hradecky": "Finland",
  "M. Kovář": "Czech Republic",
  "Matej Kovář": "Czech Republic",
  "J. Tah": "Germany",
  "Jonathan Tah": "Germany",
  "E. Tapsoba": "Burkina Faso",
  "Edmond Tapsoba": "Burkina Faso",
  "P. Hincapié": "Ecuador",
  "Piero Hincapié": "Ecuador",
  "J. Belocian": "France",
  "Jeanuël Belocian": "France",
  "Á. Grimaldo": "Spain",
  "Álex Grimaldo": "Spain",
  "J. Frimpong": "Netherlands",
  "Jeremie Frimpong": "Netherlands",
  "A. Arthur": "Brazil",
  "G. Xhaka": "Switzerland",
  "Granit Xhaka": "Switzerland",
  "R. Andrich": "Germany",
  "Robert Andrich": "Germany",
  "E. Palacios": "Argentina",
  "Exequiel Palacios": "Argentina",
  "A. García": "Spain",
  "Aleix García": "Spain",
  "F. Wirtz": "Germany",
  "Florian Wirtz": "Germany",
  "J. Hofmann": "Germany",
  "Jonas Hofmann": "Germany",
  "N. Tella": "Nigeria",
  "Nathan Tella": "Nigeria",
  "A. Adli": "Morocco",
  "Amine Adli": "Morocco",
  "M. Terrier": "France",
  "Martin Terrier": "France",
  "V. Boniface": "Nigeria",
  "Victor Boniface": "Nigeria",
  "P. Schick": "Czech Republic",
  "Patrik Schick": "Czech Republic",

  // Borussia Dortmund
  "G. Kobel": "Switzerland",
  "Gregor Kobel": "Switzerland",
  "A. Meyer": "Germany",
  "M. Schlotterbeck": "Germany",
  "Nico Schlotterbeck": "Germany",
  "W. Anton": "Germany",
  "Waldemar Anton": "Germany",
  "N. Süle": "Germany",
  "Niklas Süle": "Germany",
  "R. Bensebaini": "Algeria",
  "Ramy Bensebaini": "Algeria",
  "J. Ryerson": "Norway",
  "Julian Ryerson": "Norway",
  "Y. Couto": "Brazil",
  "Yan Couto": "Brazil",
  "E. Can": "Germany",
  "Emre Can": "Germany",
  "P. Groß": "Germany",
  "Pascal Groß": "Germany",
  "M. Sabitzer": "Austria",
  "Marcel Sabitzer": "Austria",
  "F. Nmecha": "Germany",
  "Felix Nmecha": "Germany",
  "J. Brandt": "Germany",
  "Julian Brandt": "Germany",
  "G. Reyna": "USA",
  "Giovanni Reyna": "USA",
  "K. Adeyemi": "Germany",
  "Karim Adeyemi": "Germany",
  "D. Malen": "Netherlands",
  "Donyell Malen": "Netherlands",
  "J. Bynoe-Gittens": "England",
  "Jamie Gittens": "England",
  "S. Guirassy": "Guinea",
  "Serhou Guirassy": "Guinea",
  "M. Beier": "Germany",
  "Maximilian Beier": "Germany",
  "S. Haller": "Ivory Coast",

  // RB Leipzig
  "P. Gulácsi": "Hungary",
  "Péter Gulácsi": "Hungary",
  "M. Vandevoordt": "Belgium",
  "Maarten Vandevoordt": "Belgium",
  "C. Lukeba": "France",
  "Castello Lukeba": "France",
  "W. Orbán": "Hungary",
  "Will Orban": "Hungary",
  "L. Geertruida": "Netherlands",
  "Lutsharel Geertruida": "Netherlands",
  "L. Klostermann": "Germany",
  "Lukas Klostermann": "Germany",
  "D. Raum": "Germany",
  "David Raum": "Germany",
  "B. Henrichs": "Germany",
  "Benjamin Henrichs": "Germany",
  "A. Haidara": "Mali",
  "Amadou Haidara": "Mali",
  "N. Seiwald": "Austria",
  "Nicolas Seiwald": "Austria",
  "X. Schlager": "Austria",
  "Xaver Schlager": "Austria",
  "K. Kampl": "Slovenia",
  "Kevin Kampl": "Slovenia",
  "C. Baumgartner": "Austria",
  "Christoph Baumgartner": "Austria",
  "X. Simons": "Netherlands",
  "Xavi Simons": "Netherlands",
  "E. Elmas": "North Macedonia",
  "Eljif Elmas": "North Macedonia",
  "A. Nusa": "Norway",
  "Antonio Nusa": "Norway",
  "L. Openda": "Belgium",
  "Loïs Openda": "Belgium",
  "B. Šeško": "Slovenia",
  "Benjamin Šeško": "Slovenia",
  "Y. Poulsen": "Denmark",
  "Yussuf Poulsen": "Denmark",

  // Eintracht Frankfurt
  "K. Trapp": "Germany",
  "Kevin Trapp": "Germany",
  "K. Santos": "Brazil",
  "R. Koch": "Germany",
  "Robin Koch": "Germany",
  "W. Pacho": "Ecuador",
  "Willian Pacho": "Ecuador",
  "A. Theate": "Belgium",
  "Arthur Theate": "Belgium",
  "T. Kristensen": "Denmark",
  "Rasmus Kristensen": "Denmark",
  "N. Collins": "Germany",
  "Nnamdi Collins": "Germany",
  "E. Skhiri": "Tunisia",
  "Ellyes Skhiri": "Tunisia",
  "H. Larsson": "Sweden",
  "Hugo Larsson": "Sweden",
  "M. Dahoud": "Syria",
  "Mahmoud Dahoud": "Syria",
  "F. Chaïbi": "Algeria",
  "Farès Chaïbi": "Algeria",
  "M. Götze": "Germany",
  "Mario Götze": "Germany",
  "F. Ebimbe": "France",
  "Junior Dina Ebimbe": "France",
  "O. Marmoush": "Egypt",
  "Omar Marmoush": "Egypt",
  "H. Ekitike": "France",
  "Hugo Ekitike": "France",
  "I. Matanović": "Croatia",
  "Igor Matanović": "Croatia",

  // VfB Stuttgart
  "A. Nübel": "Germany",
  "Alexander Nübel": "Germany",
  "F. Bredlow": "Germany",
  "D. Zagadou": "France",
  "Dan-Axel Zagadou": "France",
  "J. Chabot": "Germany",
  "Julian Chabot": "Germany",
  "A. Rouault": "France",
  "Anthony Rouault": "France",
  "L. Stergiou": "Switzerland",
  "Leonidas Stergiou": "Switzerland",
  "M. Mittelstädt": "Germany",
  "Maximilian Mittelstädt": "Germany",
  "J. Vagnoman": "Germany",
  "Josha Vagnoman": "Germany",
  "A. Stiller": "Germany",
  "Angelo Stiller": "Germany",
  "A. Karazor": "Germany",
  "Atakan Karazor": "Germany",
  "E. Millot": "France",
  "Enzo Millot": "France",
  "C. Führich": "Germany",
  "Chris Führich": "Germany",
  "E. Demirović": "Bosnia",
  "Ermedin Demirović": "Bosnia",
  "D. Undav": "Germany",
  "Deniz Undav": "Germany",
  "N. Woltemade": "Germany",
  "Nick Woltemade": "Germany",
  "E. Touré": "Mali",
  "El Bilal Touré": "Mali"
};

function processLeague(leagueName) {
  const dir = path.join(__dirname, '..', 'data', 'players', 'active', leagueName);
  if (!fs.existsSync(dir)) return;

  const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));
  let updatedCount = 0;
  let totalProcessed = 0;

  files.forEach(file => {
    const filePath = path.join(dir, file);
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

    data.players.forEach(p => {
      totalProcessed++;
      const matchedNation = REAL_NATIONS[p.name];
      if (matchedNation && p.nation !== matchedNation) {
        p.nation = matchedNation;
        updatedCount++;
      }
    });

    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  });

  console.log(`\n🎉 Processed ${leagueName.toUpperCase()}: ${totalProcessed} players checked, ${updatedCount} nations updated!`);
}

processLeague('serie-a');
processLeague('bundesliga');
