const fs = require('fs');
const path = require('path');

const LALIGA_NATIONS = {
  // Real Madrid
  "T. Courtois": "Belgium",
  "Courtois": "Belgium",
  "A. Lunin": "Ukraine",
  "Lunin": "Ukraine",
  "D. Carvajal": "Spain",
  "Carvajal": "Spain",
  "Éder Militão": "Brazil",
  "E. Militão": "Brazil",
  "David Alaba": "Austria",
  "D. Alaba": "Austria",
  "A. Rüdiger": "Germany",
  "Rüdiger": "Germany",
  "F. Mendy": "France",
  "Ferland Mendy": "France",
  "Fran García": "Spain",
  "J. Vallejo": "Spain",
  "J. Bellingham": "England",
  "Jude Bellingham": "England",
  "E. Camavinga": "France",
  "Eduardo Camavinga": "France",
  "F. Valverde": "Uruguay",
  "Federico Valverde": "Uruguay",
  "L. Modrić": "Croatia",
  "Luka Modrić": "Croatia",
  "A. Tchouaméni": "France",
  "Aurelien Tchouaméni": "France",
  "A. Güler": "Turkey",
  "Arda Güler": "Turkey",
  "D. Ceballos": "Spain",
  "Dani Ceballos": "Spain",
  "Vinícius Júnior": "Brazil",
  "Vinicius Junior": "Brazil",
  "K. Mbappé": "France",
  "Kylian Mbappé": "France",
  "Rodrygo": "Brazil",
  "Endrick": "Brazil",
  "Brahim Díaz": "Morocco",
  "B. Díaz": "Morocco",

  // Barcelona
  "M. ter Stegen": "Germany",
  "Ter Stegen": "Germany",
  "Iñaki Peña": "Spain",
  "I. Peña": "Spain",
  "W. Szczęsny": "Poland",
  "Joan García": "Spain",
  "Pau Cubarsí": "Spain",
  "P. Cubarsí": "Spain",
  "R. Araújo": "Uruguay",
  "Ronald Araújo": "Uruguay",
  "Iñigo Martínez": "Spain",
  "I. Martínez": "Spain",
  "A. Christensen": "Denmark",
  "Andreas Christensen": "Denmark",
  "J. Koundé": "France",
  "Jules Koundé": "France",
  "A. Balde": "Spain",
  "Alejandro Balde": "Spain",
  "E. García": "Spain",
  "Eric García": "Spain",
  "H. Fort": "Spain",
  "Héctor Fort": "Spain",
  "Gavi": "Spain",
  "Pedri": "Spain",
  "F. de Jong": "Netherlands",
  "Frenkie de Jong": "Netherlands",
  "Marc Casadó": "Spain",
  "M. Casadó": "Spain",
  "M. Bernal": "Spain",
  "Fermín López": "Spain",
  "F. López": "Spain",
  "Pablo Torre": "Spain",
  "P. Torre": "Spain",
  "Dani Olmo": "Spain",
  "D. Olmo": "Spain",
  "Lamine Yamal": "Spain",
  "L. Yamal": "Spain",
  "Raphinha": "Brazil",
  "R. Lewandowski": "Poland",
  "Robert Lewandowski": "Poland",
  "Ferran Torres": "Spain",
  "F. Torres": "Spain",
  "Ansu Fati": "Spain",
  "A. Fati": "Spain",
  "Pau Víctor": "Spain",
  "P. Víctor": "Spain",

  // Atletico Madrid
  "J. Oblak": "Slovenia",
  "Jan Oblak": "Slovenia",
  "J. Musso": "Argentina",
  "R. Le Normand": "Spain",
  "J. Giménez": "Uruguay",
  "A. Witsel": "Belgium",
  "C. Azpilicueta": "Spain",
  "Reinildo": "Mozambique",
  "N. Molina": "Argentina",
  "J. Galán": "Spain",
  "C. Lenglet": "France",
  "Koke": "Spain",
  "M. Llorente": "Spain",
  "R. De Paul": "Argentina",
  "C. Gallagher": "England",
  "P. Barrios": "Spain",
  "T. Lemar": "France",
  "A. Griezmann": "France",
  "Antoine Griezmann": "France",
  "J. Álvarez": "Argentina",
  "Julián Álvarez": "Argentina",
  "A. Sørloth": "Norway",
  "Á. Correa": "Argentina",
  "G. Simeone": "Argentina",
  "S. Lino": "Brazil",
  "R. Riquelme": "Spain",

  // Athletic Club
  "Unai Simón": "Spain",
  "U. Simón": "Spain",
  "J. Agirrezabala": "Spain",
  "D. Vivian": "Spain",
  "A. Paredes": "Spain",
  "Yeray": "Spain",
  "Yeray Álvarez": "Spain",
  "Yuri": "Spain",
  "Yuri Berchiche": "Spain",
  "De Marcos": "Spain",
  "I. Lekue": "Spain",
  "J. Gorosabel": "Spain",
  "I. Ruiz de Galarreta": "Spain",
  "B. Prados": "Spain",
  "M. Vesga": "Spain",
  "Unai Gómez": "Spain",
  "O. Sancet": "Spain",
  "Nico Williams": "Spain",
  "N. Williams": "Spain",
  "Iñaki Williams": "Ghana",
  "I. Williams": "Ghana",
  "Álvaro Djaló": "Spain",
  "G. Guruzeta": "Spain",
  "A. Berenguer": "Spain",

  // Real Sociedad
  "Á. Remiro": "Spain",
  "U. Marrero": "Spain",
  "I. Zubeldia": "Spain",
  "N. Aguerd": "Morocco",
  "J. Pacheco": "Spain",
  "H. Traoré": "Mali",
  "Javi López": "Spain",
  "Aihen Muñoz": "Spain",
  "Á. Odriozola": "Spain",
  "M. Zubimendi": "Spain",
  "L. Sučić": "Croatia",
  "B. Turrientes": "Spain",
  "Pablo Marín": "Spain",
  "Brais Méndez": "Spain",
  "T. Kubo": "Japan",
  "Takefusa Kubo": "Japan",
  "M. Oyarzabal": "Spain",
  "Mikel Oyarzabal": "Spain",
  "S. Becker": "Suriname",
  "O. Óskarsson": "Iceland",
  "U. Sadiq": "Nigeria",
  "A. Barrenetxea": "Spain",

  // Villarreal
  "Diego Conde": "Spain",
  "Luiz Júnior": "Brazil",
  "R. Albiol": "Spain",
  "W. Kambwala": "France",
  "L. Costa": "Cape Verde",
  "E. Bailly": "Ivory Coast",
  "J. Foyth": "Argentina",
  "Sergi Cardona": "Spain",
  "Kiko Femenía": "Spain",
  "A. Pedraza": "Spain",
  "D. Parejo": "Spain",
  "P. Gueye": "Senegal",
  "S. Comesaña": "Spain",
  "R. Terrats": "Spain",
  "Álex Baena": "Spain",
  "Á. Baena": "Spain",
  "D. Suárez": "Spain",
  "I. Akhomach": "Morocco",
  "Y. Pino": "Spain",
  "N. Pépé": "Ivory Coast",
  "Ayoze Pérez": "Spain",
  "A. Pérez": "Spain",
  "T. Barry": "France",
  "G. Moreno": "Spain",
  "Gerard Moreno": "Spain",

  // Real Betis
  "Rui Silva": "Portugal",
  "Adrián": "Spain",
  "Marc Bartra": "Spain",
  "D. Llorente": "Spain",
  "Natan": "Brazil",
  "Y. Sabaly": "Senegal",
  "H. Bellerín": "Spain",
  "R. Perraud": "France",
  "R. Rodríguez": "Switzerland",
  "M. Roca": "Spain",
  "J. Cardoso": "USA",
  "W. Carvalho": "Portugal",
  "S. Altimira": "Spain",
  "Isco": "Spain",
  "G. Lo Celso": "Argentina",
  "P. Fornals": "Spain",
  "Abde Ezzalzouli": "Morocco",
  "Ez Abde": "Morocco",
  "Vitor Roque": "Brazil",
  "C. Bakambu": "DR Congo",
  "C. Ávila": "Argentina",
  "A. Ruibal": "Spain",

  // Girona
  "P. Gazzaniga": "Argentina",
  "Pau López": "Spain",
  "D. Blind": "Netherlands",
  "David López": "Spain",
  "L. Krejčí": "Czech Republic",
  "Juanpe": "Spain",
  "M. Gutiérrez": "Spain",
  "Arnau Martínez": "Spain",
  "A. Francés": "Spain",
  "O. Romeu": "Spain",
  "Y. Herrera": "Venezuela",
  "I. Martín": "Spain",
  "J. Solís": "Colombia",
  "D. van de Beek": "Netherlands",
  "G. Misehouy": "Netherlands",
  "V. Tsygankov": "Ukraine",
  "Bryan Gil": "Spain",
  "Portu": "Spain",
  "Y. Asprilla": "Colombia",
  "Abel Ruiz": "Spain",
  "B. Miovski": "North Macedonia",
  "C. Stuani": "Uruguay",

  // Sevilla
  "Ø. Nyland": "Norway",
  "Á. Fernández": "Spain",
  "L. Badé": "France",
  "T. Nianzou": "France",
  "Kike Salas": "Spain",
  "Marcão": "Brazil",
  "A. Pedrosa": "Spain",
  "V. Barco": "Argentina",
  "G. Montiel": "Argentina",
  "Juanlu Sánchez": "Spain",
  "N. Gudelj": "Serbia",
  "L. Agoumé": "France",
  "A. Lokonga": "Belgium",
  "Saúl": "Spain",
  "Saúl Ñíguez": "Spain",
  "D. Sow": "Switzerland",
  "Suso": "Spain",
  "C. Ejuke": "Nigeria",
  "D. Lukebakio": "Belgium",
  "Isaac Romero": "Spain",
  "K. Iheanacho": "Nigeria",

  // Valencia
  "G. Mamardashvili": "Georgia",
  "S. Dimitrievski": "North Macedonia",
  "C. Mosquera": "Spain",
  "C. Tárrega": "Spain",
  "M. Diakhaby": "Guinea",
  "Y. Gasiorowski": "Spain",
  "J. Gayà": "Spain",
  "T. Correia": "Portugal",
  "D. Foulquier": "Guadeloupe",
  "Pepelu": "Spain",
  "H. Guillamón": "Spain",
  "Javi Guerra": "Spain",
  "E. Barrenechea": "Argentina",
  "A. Almeida": "Portugal",
  "Diego López": "Spain",
  "Fran Pérez": "Spain",
  "S. Canós": "Spain",
  "G. Valera": "Spain",
  "Hugo Duro": "Spain",
  "Rafa Mir": "Spain",
  "Dani Gómez": "Spain"
};

const LALIGA_POSITIONS = {
  // Real Madrid
  "D. Carvajal": "RB/RM",
  "Carvajal": "RB/RM",
  "Éder Militão": "CB/RB",
  "E. Militão": "CB/RB",
  "David Alaba": "CB/LB",
  "D. Alaba": "CB/LB",
  "Jude Bellingham": "CAM/CM",
  "J. Bellingham": "CAM/CM",
  "Eduardo Camavinga": "CDM/CM",
  "E. Camavinga": "CDM/CM",
  "Federico Valverde": "CM/RW",
  "F. Valverde": "CM/RW",
  "Luka Modrić": "CM/CAM",
  "L. Modrić": "CM/CAM",
  "Aurelien Tchouaméni": "CDM/CB",
  "A. Tchouaméni": "CDM/CB",
  "Arda Güler": "CAM/RW",
  "A. Güler": "CAM/RW",
  "Vinícius Júnior": "LW/ST",
  "Vinicius Junior": "LW/ST",
  "Kylian Mbappé": "ST/LW",
  "K. Mbappé": "ST/LW",
  "Rodrygo": "RW/ST",
  "Endrick": "ST/CF",
  "Brahim Díaz": "CAM/RW",
  "B. Díaz": "CAM/RW",

  // Barcelona
  "Ronald Araújo": "CB/RB",
  "R. Araújo": "CB/RB",
  "Andreas Christensen": "CB/CDM",
  "A. Christensen": "CB/CDM",
  "Jules Koundé": "RB/CB",
  "J. Koundé": "RB/CB",
  "Eric García": "CB/RB",
  "E. García": "CB/RB",
  "Gavi": "CM/CAM",
  "Pedri": "CM/CAM",
  "Frenkie de Jong": "CM/CDM",
  "F. de Jong": "CM/CDM",
  "Marc Casadó": "CDM/CM",
  "M. Casadó": "CDM/CM",
  "Fermín López": "CAM/CM",
  "F. López": "CAM/CM",
  "Dani Olmo": "CAM/LW",
  "D. Olmo": "CAM/LW",
  "Lamine Yamal": "RW/ST",
  "L. Yamal": "RW/ST",
  "Raphinha": "LW/RW",
  "Ferran Torres": "ST/LW",
  "F. Torres": "ST/LW",
  "Ansu Fati": "LW/ST",
  "A. Fati": "LW/ST",

  // Atletico Madrid
  "Axel Witsel": "CB/CDM",
  "A. Witsel": "CB/CDM",
  "César Azpilicueta": "CB/RB",
  "C. Azpilicueta": "CB/RB",
  "Reinildo": "LB/CB",
  "Nahuel Molina": "RB/RM",
  "N. Molina": "RB/RM",
  "Koke": "CM/CDM",
  "Marcos Llorente": "RB/CM",
  "M. Llorente": "RB/CM",
  "Rodrigo De Paul": "CM/CAM",
  "R. De Paul": "CM/CAM",
  "Conor Gallagher": "CM/CDM",
  "C. Gallagher": "CM/CDM",
  "Pablo Barrios": "CM/CDM",
  "P. Barrios": "CM/CDM",
  "Antoine Griezmann": "ST/CAM",
  "A. Griezmann": "ST/CAM",
  "Julián Álvarez": "ST/LW",
  "J. Álvarez": "ST/LW",
  "Ángel Correa": "ST/RW",
  "Á. Correa": "ST/RW",
  "Giuliano Simeone": "RW/RM",
  "G. Simeone": "RW/RM",
  "Samuel Lino": "LW/LM",
  "S. Lino": "LW/LM",
  "Rodrigo Riquelme": "LW/CAM",
  "R. Riquelme": "LW/CAM",

  // Athletic Club
  "Inigo Lekue": "RB/LB",
  "I. Lekue": "RB/LB",
  "Unai Gómez": "CAM/CM",
  "Oihan Sancet": "CAM/ST",
  "O. Sancet": "CAM/ST",
  "Nico Williams": "LW/RW",
  "N. Williams": "LW/RW",
  "Iñaki Williams": "RW/ST",
  "I. Williams": "RW/ST",
  "Álvaro Djaló": "LW/ST",
  "Alex Berenguer": "LW/RW",
  "A. Berenguer": "LW/RW",

  // Real Sociedad
  "Martin Zubimendi": "CDM/CM",
  "M. Zubimendi": "CDM/CM",
  "Luka Sučić": "CM/CAM",
  "L. Sučić": "CM/CAM",
  "Brais Méndez": "CAM/CM",
  "Takefusa Kubo": "RW/CAM",
  "T. Kubo": "RW/CAM",
  "Mikel Oyarzabal": "LW/ST",
  "M. Oyarzabal": "LW/ST",
  "Sheraldo Becker": "RW/ST",
  "S. Becker": "RW/ST",

  // Villarreal
  "Juan Foyth": "RB/CB",
  "J. Foyth": "RB/CB",
  "Alfonso Pedraza": "LB/LM",
  "A. Pedraza": "LB/LM",
  "Dani Parejo": "CM/CDM",
  "D. Parejo": "CM/CDM",
  "Pape Gueye": "CDM/CM",
  "P. Gueye": "CDM/CM",
  "Álex Baena": "CAM/LW",
  "Á. Baena": "CAM/LW",
  "Yéremy Pino": "RW/LW",
  "Y. Pino": "RW/LW",
  "Nicolas Pépé": "RW/ST",
  "N. Pépé": "RW/ST",
  "Ayoze Pérez": "ST/LW",
  "A. Pérez": "ST/LW",
  "Gerard Moreno": "ST/RW",
  "G. Moreno": "ST/RW",

  // Real Betis
  "Ricardo Rodríguez": "LB/CB",
  "R. Rodríguez": "LB/CB",
  "Marc Roca": "CDM/CM",
  "M. Roca": "CDM/CM",
  "Johnny Cardoso": "CDM/CM",
  "J. Cardoso": "CDM/CM",
  "Isco": "CAM/CM",
  "Giovani Lo Celso": "CAM/CM",
  "G. Lo Celso": "CAM/CM",
  "Pablo Fornals": "CAM/RM",
  "P. Fornals": "CAM/RM",
  "Ez Abde": "LW/RW",
  "Chimy Ávila": "ST/RW",
  "C. Ávila": "ST/RW",
  "Aitor Ruibal": "RB/RW",
  "A. Ruibal": "RB/RW",

  // Girona
  "Daley Blind": "CB/LB",
  "D. Blind": "CB/LB",
  "David López": "CB/CDM",
  "Ladislav Krejčí": "CB/CDM",
  "L. Krejčí": "CB/CDM",
  "Arnau Martínez": "RB/CB",
  "Alejandro Francés": "RB/CB",
  "A. Francés": "RB/CB",
  "Yangel Herrera": "CM/CDM",
  "Y. Herrera": "CM/CDM",
  "Ivan Martín": "CM/CAM",
  "I. Martín": "CM/CAM",
  "Donny van de Beek": "CAM/CM",
  "D. van de Beek": "CAM/CM",
  "Viktor Tsygankov": "RW/CAM",
  "V. Tsygankov": "RW/CAM",
  "Bryan Gil": "LW/LM",
  "Yaser Asprilla": "RW/CAM",
  "Y. Asprilla": "RW/CAM",

  // Sevilla
  "Valentin Barco": "LB/LM",
  "V. Barco": "LB/LM",
  "Juanlu Sánchez": "RB/RM",
  "Nemanja Gudelj": "CDM/CB",
  "N. Gudelj": "CDM/CB",
  "Lucien Agoumé": "CDM/CM",
  "L. Agoumé": "CDM/CM",
  "Albert Sambi Lokonga": "CM/CDM",
  "A. Lokonga": "CM/CDM",
  "Saúl Ñíguez": "CM/LM",
  "Saúl": "CM/LM",
  "Suso": "RW/CAM",
  "Dodi Lukebakio": "RW/ST",
  "D. Lukebakio": "RW/ST",

  // Valencia
  "Yarek Gasiorowski": "CB/LB",
  "Y. Gasiorowski": "CB/LB",
  "Pepelu": "CDM/CM",
  "Hugo Guillamón": "CDM/CB",
  "H. Guillamón": "CDM/CB",
  "Javi Guerra": "CM/CAM",
  "Enzo Barrenechea": "CDM/CM",
  "E. Barrenechea": "CDM/CM",
  "André Almeida": "CAM/CM",
  "A. Almeida": "CAM/CM",
  "Diego López": "LW/RW",
  "Fran Pérez": "RW/RM"
};

function processLaLiga() {
  const dir = path.join(__dirname, '..', 'data', 'players', 'active', 'la-liga');
  if (!fs.existsSync(dir)) return;

  const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));

  let nationUpdated = 0;
  let posUpdated = 0;

  for (const file of files) {
    const filePath = path.join(dir, file);
    const squadObj = JSON.parse(fs.readFileSync(filePath, 'utf-8'));

    for (const p of squadObj.players) {
      // 1. Fill Nation
      if (LALIGA_NATIONS[p.name]) {
        p.nation = LALIGA_NATIONS[p.name];
        nationUpdated++;
      } else if (!p.nation || p.nation === 'Unknown') {
        p.nation = 'Spain'; // Default remaining La Liga youth players to Spain
        nationUpdated++;
      }

      // 2. Fill Secondary Multi-Position
      if (LALIGA_POSITIONS[p.name]) {
        p.position = LALIGA_POSITIONS[p.name];
        posUpdated++;
      }
    }

    fs.writeFileSync(filePath, JSON.stringify(squadObj, null, 2));
  }

  console.log(`\n🎉 La Liga Processing Complete!`);
  console.log(`   ✨ Nations updated: ${nationUpdated}`);
  console.log(`   ⚡ Multi-positions updated: ${posUpdated}`);
}

processLaLiga();
